### PR TITLE
Fix InMemoryCache read type

### PR DESCRIPTION
**Pull request by adnsio**
Fix issue #2589, InMemoryCache read type to correctly extend NormalizedCacheObject

### CODE REVIEW

**Comment by boomyao** [comment]
hi,  code `public read<T>(query: Cache.ReadOptions): T {` at inMemoryCache.ts , but  still throw the same error...

**Comment by jbaxleyiii** [comment]
@kamilkisiela

**Comment by kamilkisiela** [comment]
@jbaxleyiii 
In my opinion, since `class InMemoryCache extends ApolloCache` then `InMemoryCache` should stick to `ApolloCache` and not the other way around.

Thats why `inMemoryCache.read()` should return the same type as `apolloCache.read()`.

The thrown error says that the first one is not compatible with the second one which is true but only for released versions. After diving into source code of the latest version of each package it seems that `apollo-cache-inmemory` uses something from `apollo-cache` that has not been released yet.

Take a look `abstract read<T>...` (5th line) [here](https://unpkg.com/apollo-cache@1.0.1/lib/cache.d.ts)

Not published `apollo-cache` has the same type for `read()...` as the released `apollo-cache-inmemory`.

Proofs:

https://github.com/apollographql/apollo-client/blob/3fe121c1103e12fed1857143d201243ca54582a6/packages/apollo-cache/src/cache.ts#L11

https://github.com/apollographql/apollo-client/blob/3fe121c1103e12fed1857143d201243ca54582a6/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L76

We just need to publish the latest `apollo-cache` instead of merging this PR, because if not that it will break the `apollo-cache-inmemory` again once new `apollo-cache` is released.

**Comment by adnsio** [comment]
@kamilkisiela @jbaxleyiii I will close this pull request, please release `apollo-cache` 👍🏻

**Comment by jbaxleyiii** [comment]
@adnsio you bet!

**Comment by pselden** [comment]
Will this be released soon?

**Pull request closed without merging**
