### PR TITLE
Fix previousData lost with useLazyQuery and variable change

### PR DESCRIPTION
**Pull request by grnnja**
This is a failing test for #7396. I based the new test on:
https://github.com/apollographql/apollo-client/blob/3161e31538c33f3aafb18f955fbee0e6e7a0b0c0/src/react/hooks/__tests__/useLazyQuery.test.tsx#L395
The component in the new test rerenders an extra time between rerender 4 and rerender 5, where loading is still true, but it changes both data and previousData to undefined, which is the problem in #7396. 

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by brainkim** [comment]
Thanks for this! If you’re planning on looking into this, I’m happy to help in any way, and if you wanted a maintainer to expedite an investigation and a fix, this is best way to hurry us up! Either way, ping me and let me know!

**Comment by grnnja** [comment]
Hey @brainkim! I'm not too sure what the intended / correct behavior would look like, so perhaps its best for a maintainer to handle this.

**Comment by brainkim** [comment]
@grnnja I took a look at this and [wrote a comment](https://github.com/apollographql/apollo-client/issues/7396#issuecomment-879228297) on the original issue. If you use the `refetch()` function instead of the `execute()` function, it seems like you get the behavior you’re looking for.

**Comment by grnnja** [comment]
@brainkim Thanks for clearing this up, I didn't realize that `refresh()` behaved differently from `execute())`.

**Pull request closed without merging**
