### PR TITLE
fixes #1412

### LINKED ISSUE #1412: ReduxDataProxy isn't forwarding ApolloReducerConfig
**Intended outcome:**
When calling `client.readQuery()`, I expect it to use `customResolvers` provided when initializing the client.

**Actual outcome:**
It's not using the `customResolvers`

**How to reproduce the issue:**
Follow http://dev.apollodata.com/react/cache-updates.html#cacheRedirect and try reading from the cache with `client.readQuery()`

### PR DESCRIPTION
**Pull request by ksmth**
both `TransactionDataProxy` and `DataProxy` weren’t receiving the `ApolloReducerConfig` and weren’t able to read from the cache as expected when the user provided `customResolvers`

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
Thanks @ksmth! Please make sure to fix the CI errors so I can review the PR. You can run the tests locally with `npm test`.

**Comment by ksmth** [comment]
Ok, now this looks much better ☺️ Looking at the tests now, would it maybe make sense to add a test to check that the proxies actually use the `cusotmResolvers`? So, to cover my initial bug report basically.

**Comment by stubailo** [comment]
@ksmth that would be a great test to add!

**Comment by ksmth** [comment]
So, there will be two errors, but I'm certain that they're not related to the code I added.

```
      const proxy = createDataProxy({
        initialState: {
          apollo: {
            data: {
              'ROOT_QUERY': {
                __typename: 'Query',
              },
              foo: {
                __typename: 'Thing',
                id: 'foo',
                a: 1,
                b: '2',
                c: null,
              },
            },
          },
        },
        config: {
          dataIdFromObject: (object: any) => object.id,
          customResolvers: {
            Query: {
              thing: (_, args) => toIdValue(args.id),
            },
          },
        },
      });

      const queryResult = proxy.readFragment({
        id: 'foo',
        fragment: gql`fragment fooFragment on Thing { a b c } `,
      });

      assert.deepEqual(queryResult, {
        thing: { a: 1, b: '2', c: null },
      });
```

Will fail with:
```
      AssertionError: expected { a: 1, b: '2', c: null } to deeply equal { thing: { a: 1, b: '2', c: null } }
      + expected - actual

       {
      -  "a": 1
      -  "b": "2"
      -  "c": [null]
      +  "thing": {
      +    "a": 1
      +    "b": "2"
      +    "c": [null]
      +  }
       }
```

How to proceed here?

**Comment by stubailo** [comment]
That seems like the expected result - I don't think that test actually calls the custom resolver? I think you would want to use readQuery in the test.

**Comment by ksmth** [comment]
My bad, understood the Assertion wrong ... fixing things now

**Comment by ksmth** [comment]
Yup - getting to know the codebase and how things work. So, it's correct that even if `customResolvers` is missing, `readFragment` will succeed, if a proper `dataIdFromObject` is provided, even without `customResolvers`, because it's reading by ID anyway, is that correct?

**Comment by ksmth** [comment]
So to wrap things up:

I wanted to make sure all reads from the cache respect the `customResolvers`. As it turns out, `readFragment` doesn't use `customResolvers` at all, because it doesn't need to, `id` and the type information from the fragment are enough to figure stuff out based on what info is available in the cache.

Now the only tests that are added are to check whether both `readQuery` implementations make use of any provided `customResolvers`. ✅

**Comment by stubailo** [comment]
@ksmth here's something that would trigger the custom resolver from `readFragment`:

```js
const queryResult = proxy.readFragment({
        id: 'foo',
        fragment: gql`fragment fooFragment on Query { thing { a b c } } `,
      });

      assert.deepEqual(queryResult, {
        thing: { a: 1, b: '2', c: null },
      });
```

**Comment by ksmth** [comment]
I couldn't get it to work with the exact code you posted, it's now this instead:
```
const queryResult = proxy.readFragment({
  id: 'foo',
  fragment: gql`fragment fooFragment on Query {
    thing(id: "bar") { a b c }
  }`,
});
```

With this data in the store:
```
{
  'ROOT_QUERY': {
    __typename: 'Query',
  },
  foo: {
    __typename: 'Query',
    id: 'foo',
  },
  bar: {
    __typename: 'Thing',
    id: 'foo',
    a: 1,
    b: '2',
    c: null,
  },
}
```

It's definitely triggering the custom resolvers, so I think every case should be covered now?

**Pull request merged**
