### PR TITLE
adds a prettier ignore file

### PR DESCRIPTION
**Pull request by jpvajda**
This PR adds a `.prettierignore` file in order to prevent prettier from over writing some formatting choices we've made for our docs. 

### Relates to 

https://github.com/apollographql/apollo-client/pull/9777

### References

https://prettier.io/docs/en/ignore.html#ignoring-files

### CODE REVIEW

**Comment by jpvajda** [comment]
One thing to note on this before merging ,locally I still saw prettier overwriting the error-handling.mdx file as I was testing the use of `*` instead of `-` for markdown bullets, as prettier prefers  `-` and we prefer `*`. So I was curious if we needed to actually merge this file into the repo before it would actually take effect. I spent about an hour troubleshooting it, and coudln't determine why even with this file, Prettier still made the auto-correction to the file. 

A way to test this PR would be to:

0. install the prettier vsCode plugin
1. pull the code down and attempt make a change to the file `error-handling.mdx`
2. if the file is working, Prettier should completely ignore this file
3. if the file isn't working, Prettier will change all bullets from `*` to `-`

**Review by StephenBarlow — APPROVED** [review]
Works for me if it does what it says on the tin!

**Comment by jpvajda** [comment]
Before I merge, I just wanted to get @benjamn approval on this thanks @StephenBarlow !

**Comment by jpvajda** [comment]
@alessbell 👋  This is a pretty straight forward PR for using a prettier ignore file in our repo, So I though this may be something you could review.

**Review by alessbell — APPROVED** [review]

**Pull request merged**
