### PR TITLE
Expose `restore`, `extract` from underline cache to ApolloClient

### LINKED ISSUE #2607: [API Request] -Expose `restore`, `extract` from underline cache to ApolloClient
While using new ApolloClient with Hermes cache, we end up have to directly access the cache to perform `restore`or `extract`

```typescript
const client = new ApolloClient(...);
...
client.cache.restore(...);
// or
client.cache.extract();
```

**Intended outcome:**
We would like to propose a slight change in the API and expose `restore` and `extract` method

```typescript
const client = new ApolloClient(...);
...
client.restore(...);
// or
client.extract();
```
**Version**
- apollo-client@2.0.0

ping @nevir

### PR DESCRIPTION
**Pull request by M-Zuber**
Fixes #2607

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@M-Zuber SO GREAT! Would you add this to the changelog and we can merge it through!

**Comment by M-Zuber** [comment]
Done, let me know if you need anything else

**Comment by jbaxleyiii** [comment]
@M-Zuber the only thing left is to fix the typescript errors! It is dying right now because `initProxy` returns a `DataProxy` type instead of a `Cache` type. If you can switch this, it should just work!

Thanks so much for this great addition! It'll make a lot of things easier to write and explain!

**Comment by M-Zuber** [comment]
👍 
lets see if this does it

**Comment by jbaxleyiii** [comment]
@M-Zuber fantastic!! Thank you so much for doing this!

**Comment by M-Zuber** [comment]
Thank you for being an awesome maintainer!

**Comment by yuit** [comment]
Thanks @jbaxleyiii  and @M-Zuber will try it out today!

**Pull request merged**
