### PR TITLE
fix writeFragment and readFragment issue

### PR DESCRIPTION
**Pull request by jbaxleyiii**
This PR does a few things:

- run newest version of prettier on code base (still need to fix dev tooling to do this for us)
- fix a bug with writeFragment / writeQuery
- remove the lastVariables code

I'm going to run this build against react-apollo locally prior to merging (done, calling this a green build!)

Fixes https://github.com/apollographql/apollo-client/issues/2570, https://github.com/apollographql/apollo-client/issues/2360, and https://github.com/apollographql/apollo-client/issues/2415

### CODE REVIEW

**Comment by dennislaupman** [comment]
writeQuery still doesn't refresh component(s) after update

**Comment by ZelunZhang** [comment]
i have the same problem. writeQuery doesn't refresh components.

**Comment by tylerjbainbridge** [comment]
I have the same problem with writeFragment-- it doesn't refresh components.

**Comment by bamne123** [comment]
Hope this will help, I was also facing same issue, where my `fetchPolicy : 'cache-first'` then i changed to `fetchPolicy: 'cache-and-network'` its start working.

**Comment by scottmcpherson** [comment]
I'm sure everyone is trying to write to the cache differently, but here's what ended up working for me:

```
this.props.client.store.cache.writeQuery({
      query: CURRENT_USER_QUERY,
      data: { currentUser }
})
```

Notice that I'm writing directly to the stores cache

**Comment by rosskevin** [comment]
I have confirmed that the react-apollo `Query` subscription doesn't receive a callback after a cache `readQuery` + `writeQuery` following a mutation. This subscription in `Query` is created from the `ObservableQuery` provided by `this.client.watchQuery(opts)`. Therefore this is not a react-apollo issue, just manifesting here.

I have pinged maintainers and requested this to be reopened.

/related and causes https://github.com/apollographql/react-apollo/issues/2099

**Pull request merged**
