### PR TITLE
Remove unnecessary ternary operator

### PR DESCRIPTION
**Pull request by alexeyraspopov**
A small change: since `addTypename` from `ApolloReducerConfig` is a boolean, there is no need to generate a boolean using ternary operator.

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@alexeyraspopov can you sign the CLA?

**Comment by alexeyraspopov** [comment]
@jbaxleyiii, done. Sorry, got busy, forgot about the PR. Will update it soon.

**Comment by alexeyraspopov** [comment]
@jbaxleyiii, also, how this kind of change can be reflected in CHANGELOG?

**Comment by jbaxleyiii** [comment]
@alexeyraspopov it doesn't need to be since its so small! Thanks! I'll merge in!

**Pull request merged**
