### PR TITLE
Parameterize optimisticResponse

### PR DESCRIPTION
**Pull request by mcmar**
Just saw this in my editor while working with `apollo-client` directly instead of using the `react-apollo` wrappers due to lifecycle. I believe that `react-apollo` already does this, but without the function as an option. Function takes 1 arg of type `TVariables`.

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by mcmar** [comment]
@danilobuerger That is fixed. Please take another look. Thank you

**Comment by danilobuerger** [comment]
Thanks. I looked into what the input could be and it turns out its `TVariables`:
```
      if (typeof mutation.optimisticResponse === 'function') {
        optimistic = mutation.optimisticResponse(mutation.variables);
      } else {
        optimistic = mutation.optimisticResponse;
      }
```
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/data/store.ts#L84-L88

**Comment by mcmar** [comment]
Thank you @danilobuerger 
I've updated it with `TVariables`

**Comment by mcmar** [comment]
@danilobuerger Can you please review and merge this now?

**Pull request merged**
