### PR TITLE
Do not forceUpdate if consuming component is not mounted

### PR DESCRIPTION
**Pull request by wuarmin**
This change would fix the occurrence of the warning "Can't perform a React state update on an unmounted component" using `useQuery` in React.StrictMode.

#6209

best regards

### CODE REVIEW

**Comment by jgonera** [comment]
@wuarmin @brainkim Is anyone still working on this patch?

**Comment by wuarmin** [comment]
There are two failing tests. I have to invest some time, to find out, how they should be changed, or to check if their failing is correct. Can you help? Check out test details.

**Comment by wuarmin** [comment]
It would be great if someone with deeper knowledge of the project could check this 🙏

**Comment by brainkim** [comment]
I’m taking a look. The test suite is finicky. Thanks for the help!

**Comment by wuarmin** [comment]
> I’m taking a look. The test suite is finicky. Thanks for the help!
@brainkim 
Great, Thanks!

**Review by brainkim — APPROVED** [review]
Rebasing against release-3.4 seems to have fixed the breaking tests. I was doing work related to React.StrictMode which may have made the tests more robust maybe 🙈. It’s unfortunate that this might mean we might not get to backport it to 3.3 but 3.4 is looking to be a pretty nice release with a lot of fixes and stuff. Thanks for looking into this @wuarmin.

**Comment by wuarmin** [comment]
@brainkim thank you. I'm looking forward to 3.4.

**Comment by dylanwulf** [comment]
Thank you! I was experiencing this warning when a query unmounted at the same time as `refetchQueries` began. I'm not running in strict mode, but this change seems to have helped! 🎉

**Pull request merged**
