### PR TITLE
apollo-feature-requests#92 - Expose hook to updateQuery after running fetchQuery

### PR DESCRIPTION
**Pull request by pl12133**
### Checklist:
1. If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)

Reference issue - https://github.com/apollographql/apollo-feature-requests/issues/92
CodeSandbox reproduction - https://codesandbox.io/s/yw5qrm5o8z

I haven't received much interest or discussion around the linked feature request so there is not yet any consensus to speak of. Is this a "small change" or should there be further discussion?

I'm very motivated to improve the capabilities of pagination to meet more use cases, but I'm not sure how to proceed without a discussion on the topic (per the CONTRIBUTING guidelines).

2. Make sure all of the significant new logic is covered by tests

I would rather wait until a discussion is had about the implementation.

TODO:
 - [ ] Sign CLA
 - [ ] Discuss implementation
 - [ ] Tests
 - [ ] Docs

----

My application is heavily focused on infinite scrolling lists. I have found that the current tools available for pagination are not able to meet the following use cases:

1. Refetching pages of a connected query and updating the existing query.
2. Removing items from a query after the items have been deleted/moved.

This feature would give the developer full control of what is written to the cache following a query that already has results written to the cache.

### CODE REVIEW

**Comment by pl12133** [comment]
354a04841698b2a10d2cdbd080fef163e3d1705f is a workaround for what looks like https://github.com/apollographql/apollo-client/issues/3480.

**Comment by adamsoffer** [comment]
Thanks @pl12133  Looking forward to seeing this merged so I can paginate my infinite lists!

**Comment by hwillson** [comment]
Thanks very much for working on this @pl12133. We're moving towards a new cache API with Apollo Client 3.0 (`@apollo/client`), that introduces a new way of handling pagination (you can read about it [here](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-field-behavior/#handling-pagination), but more extensive docs are coming soon). We hope people will find that the new cache policies API helps simplify many use cases, including pagination. Due to these chagnes, we can't accept this PR at this time, but thanks again for your contribution.

**Comment by pl12133** [comment]
Thank you @hwillson, I think that new interface should make it easier to achieve my use case.

I solved this problem in a similar way by adding an `index` field on the server to the paginated objects, but handling it on the client side seems more ideal.

**Pull request closed without merging**
