### PR TITLE
[WIP] Support ESModules and AMD bundles in all packages

### PR DESCRIPTION
**Pull request by kamilkisiela**
Make every package tree-shakable.
Standardize bundle naming across all packages.

By having rollup configuration in just one place it makes things easier, for example defining `globals` and external packages or migrating when rollup's API changes.

Reduced size of my app by 5%

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
Deploy preview ready!

Built with commit 54063cb4a0b92172be2f6a290e8fe819435f8fc9

https://deploy-preview-2466--apollo-client-docs.netlify.com

**Comment by jbaxleyiii** [comment]
@kamilkisiela this is awesome! Is it ready? (Still has WIP in the title)

**Comment by kamilkisiela** [comment]
@jbaxleyiii not yet. I'll come back to it on next Monday.

**Comment by jbaxleyiii** [comment]
@kamilkisiela so great! Thank you!

**Comment by jbaxleyiii** [comment]
@kamilkisiela just checking on this 🤗 no worries either way!

**Comment by kamilkisiela** [comment]
@jbaxleyiii expect it to be done in few minutes

**Pull request merged**
