### PR TITLE
Attempt to fix webpack module resolution by renaming `graphql.ts` module

### LINKED ISSUE #8861: Wont compile after upgrading webpack 5
**Intended outcome:**

I was upgrading / bumping packages in my repo. Upgrading webpack, apollo client, ++. It would be great if my solution still compiled / started up after this, but I get an error.. 

**Actual outcome:**

I get the following warning in console:

```shell
WARNING in ./node_modules/@apollo/client/utilities/globals/graphql.js 4:4-10
export 'isType' (imported as 'isType') was not found in 'graphql' (possible exports: removeTemporaryGlobals)
 @ ./node_modules/@apollo/client/utilities/globals/index.js 7:0-54 8:0-22
 @ ./node_modules/@apollo/client/react/index.js 1:0-39
 @ ./node_modules/@apollo/client/index.js 2:0-33 2:0-33
 @ ./src/index.tsx 9:0-48 12:36-50
```

which looks like this on the client: 

image

**How to reproduce the issue:**

Reproduction repo: <https://github.com/thomastvedt/react-apollo-error-template>

- check out repo
- `npm install``
- `npm run start`

Output:
```
$ npm run start

> apollo-client-webpack-error@1.0.0 start
> webpack --config webpack.dev.config.ts

<w> [ReactRefreshPlugin] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
asset main.js 2.37 MiB [compared for emit] (name: main) 1 related asset
asset favicon.ico 24.3 KiB [compared for emit] [from: public/favicon.ico] [copied]
asset index.html 349 bytes [emitted]
orphan modules 163 KiB [orphan] 64 modules
runtime modules 3.25 KiB 6 modules
modules by path ./node_modules/ 1.97 MiB 319 modules
modules by path ./src/ 11.7 KiB
  ./src/index.tsx 9.35 KiB [built] [code generated]
  ./src/index.css 1.11 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./src/index.css 1.26 KiB [built] [code generated]

WARNING in ./node_modules/@apollo/client/utilities/globals/graphql.js 4:4-10
export 'isType' (imported as 'isType') was not found in 'graphql' (possible exports: removeTemporaryGlobals)
 @ ./node_modules/@apollo/client/utilities/globals/index.js 7:0-54 8:0-22
 @ ./node_modules/@apollo/client/react/index.js 1:0-39
 @ ./node_modules/@apollo/client/index.js 2:0-33 2:0-33
 @ ./src/index.tsx 74:0-56 82:15-25 83:13-23 102:0-100 255:18-26 259:21-32 303:17-29 304:13-26 307:41-55

webpack 5.55.0 compiled with 1 warning in 2709 ms

```

**Versions**

```shell
$ npx envinfo@latest --preset apollo --clipboard

  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @apollo/client: ^3.4.15 => 3.4.15 

```

Some (perhaps) relevant links:  
https://github.com/graphql/graphql-js/issues/2721   
https://github.com/apollographql/apollo-client/issues/8178

I'm not a webpack expert, and it is possible that I'm doing something wrong here? How can I tell webpack that I want my 3rd party library (apollo client) to load ESM in stead of CommonJS?

### PR DESCRIPTION
**Pull request by benjamn**
May fix #8861, if my hunch is correct that webpack is resolving the `'graphql'` in
```ts
import { isType } from 'graphql'
```
as importing from `utilities/globals/graphql.ts` module itself, rather than the `graphql` package, as suggested by the `(possible exports: removeTemporaryGlobals)` part of the error message:
```
WARNING in ./node_modules/@apollo/client/utilities/globals/graphql.js 4:4-10
export 'isType' (imported as 'isType') was not found in 'graphql' (possible exports: removeTemporaryGlobals)
```
The only relevant module that exports `removeTemporaryGlobals` is `utilities/globals/graphql.ts`, so renaming that module to something that cannot be confused with the `graphql` package should either fix the problem or at least shed more light on what's going on.

### CODE REVIEW

**Comment by benjamn** [comment]
Incredibly, this renaming fixes the reproduction provided in #8861. A pretty good guess, if I may say so myself!

**Review by brainkim — APPROVED** [review]
I don’t mind this being merged but the module resolution is just wrong and wonder if there is a deeper root cause which can be dealt with here or opened upstream.

**Comment by benjamn** [comment]
@brainkim Looks like this was a result of [`preferRelative: true`](https://webpack.js.org/configuration/resolve/#resolvepreferrelative) in `webpack.config.js`: https://github.com/apollographql/apollo-client/issues/8861#issuecomment-929949542

From my perspective, the deeper root cause of this problem is that webpack's `resolve.preferRelative` setting should not apply to resolution of modules in `node_modules`. If there was a way to disable it (in, say, `@apollo/client/package.json`), that would be nice, but I haven't found a good way (for us) to do that yet.

**Comment by brainkim** [comment]
IMHO no one should ever be using that option and I am shocked that it exists.

**Pull request merged**
