### PR TITLE
Devtools - Trigger Error Code PR after npm Release

### PR DESCRIPTION
**Pull request by phryneas**
This is one of those where we won't know if they work until we merge them 😞

### CODE REVIEW

**Review by alessbell — APPROVED** [review]
This lgtm :)

**Comment by phryneas** [comment]
Seems this is still missing permissions - I've opened a ticket internally.

**Comment by alessbell** [comment]
Do we need repository permissions for apollo client as well when generating the token? That was going to be my one comment before but figured it was worth trying more narrowly-scoped perms first.

**Comment by phryneas** [comment]
I don't think so. Guess we'll find out soon, though :)

**Comment by alessbell** [comment]
Potentially related: https://github.com/benc-uk/workflow-dispatch/issues/52

**Pull request merged**
