### PR TITLE
Adding a section about react native debugger support for apollo dev tools

### PR DESCRIPTION
**Pull request by Gongreg**
Apollo dev tools were just merged into master of react native debugger.
https://github.com/jhen0409/react-native-debugger/pull/298

@peggyrayzis suggested to add a section about it in Apollo documentation.

The updated React Native Debugger is not released for download, but it will be done soon.

### CODE REVIEW

**Comment by danilobuerger** [comment]
🙌Let's wait until its released before merging this.

**Comment by Gongreg** [comment]
Sure @danilobuerger, just added it since I had some time to burn :)

There is one "annoying" feature of Apollo dev tools is that it stops trying to connect after 10 seconds. Not sure if we need to write about it here. To avoid explaining it I just wrote step 3 (turn off and on again).

**Comment by danilobuerger** [comment]
Alright, thanks for the heads up. I will check it out once its released and take a look.

**Comment by Gongreg** [comment]
@danilobuerger, dev tools version [0.9.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.0).
I am really happy to finally get it out :)

**Comment by danilobuerger** [comment]
@Gongreg @jhen0409 Thanks for your awesome work. However, I can't get this to work yet. I don't feel comfortable merging this yet when I am not able to follow the instructions. I will post on your issue tracker to avoid going off topic in this issue.

**Comment by derekr** [comment]
I have it working for me following the instructions FWIW. I did have to toggle developer tools off and on. Super excited about this addition. Thank you!

**Comment by danilobuerger** [comment]
Thanks @Gongreg

**Pull request merged**
