### PR TITLE
Fully remove the graphql-anywhere package

### PR DESCRIPTION
**Pull request by hwillson**
Apollo Client hasn't used `graphql-anywhere` internally for quite some time. This PR removes it fully.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@hwillson are you guys still supporting the `propType` functionality or removing that as well?

**Comment by hwillson** [comment]
@lifeiscontent we're removing it completely from `@apollo/client`, but you can still use the `graphql-anywhere` package directly. If anyone wants to fork and maintain `graphql-anywhere` though, we'll happily promote that project.

**Comment by jhoch** [comment]
@hwillson, Context: I arrived here from a dead link in the Apollo v2.6 docs, and then grepping the repo for `anywhere`, and the CHANGELOG entry saying that `graphql-anywhere` had been removed from the repo.

Is the code for `graphql-anywhere` going to be hosted somewhere else?  Is the package no longer recommended by users of `apollo-client`?

**Comment by fbartho** [comment]
@benjamn @hwillson https://github.com/apollographql/apollo-link-rest/issues/295 Apollo-link-rest depends on `graphql-anywhere` Do you know if the functionality of graphql-anywhere was moved to a different Apollo library that we can migrate to?

**Comment by fbartho** [comment]
> @benjamn @hwillson [apollographql/apollo-link-rest#295](https://github.com/apollographql/apollo-link-rest/issues/295) Apollo-link-rest depends on `graphql-anywhere` Do you know if the functionality of graphql-anywhere was moved to a different Apollo library that we can migrate to?

Hey Friends! This question is still relevant. It’s not obvious where to file this as an issue, so sorry if I keep pinging a merged PR.

**Pull request merged**
