### PR TITLE
Release 3.6.0

### PR DESCRIPTION
**Pull request by hwillson**
Like the [Release 3.5.0 PR](https://github.com/apollographql/apollo-client/pull/8554), this PR will serve to collect significant new features, deprecation warnings, and minor breaking changes that we intend to release in `@apollo/client@3.6.0`.

If you want to test these changes, run
```sh
npm i @apollo/client@3.6.0-beta.n
```
in your application, where the `n` in `-beta.n` comes from the most recent commit message like
```
Bump @apollo/client npm version to 3.6.0-beta.n.
```

Until v3.6.0 is released, we can continue merging smaller changes into `main` and releasing them, without worrying about larger changes on the `release-3.6` branch.

### TODO for the 3.6 release

- [x] https://github.com/apollographql/apollo-client/issues/6916
- [x] https://github.com/apollographql/apollo-client/issues/9204
- [x] https://github.com/apollographql/apollo-client/pull/9223
- [x] https://github.com/apollographql/apollo-client/pull/9222
- [ ] `useBackgroundQuery` and `useFragment` API and usage docs
- [ ] CodeSandbox / example app that demonstrates the new hooks (will be linked to from docs / blog post)
- [ ] Announcement blog post

### CODE REVIEW

**Comment by benjamn** [comment]
@hwillson @brainkim Looks like #9112 was a misfire (I merged before realizing Netlify did not even run on that PR), but today I tracked down the source of the npm `EINTEGRITY` failures and fixed them with 38e3084225acf3469c3a4aeab3e10e854ff70a3e above.

**Comment by benjamn** [comment]
Both #9222 and #9223 are now available in `@apollo/client@3.6.0-beta.9` (and later), and we're looking for feedback on `useQuery` options functions and/or `nextFetchPolicy` functions ([docs](https://deploy-preview-9067--apollo-client-docs.netlify.app/data/queries/#nextfetchpolicy)) before Apollo Client v3.6 is finalized later this month.

There has also been some recent `useQuery` refactoring on this branch (#9459), so any feedback folks may have on the general usability/stability of `useQuery` would also be much appreciated.

For anyone who might be wondering, these two features are interesting because
* `useQuery` options functions allow the application developer to take previous options into account when deciding what options `useQuery` should use next, which allows the options to change elsewhere without getting clobbered the next time `useQuery` is called (likely with the original options)
  * #9223
* `nextFetchPolicy` is usually a string, and usually applies to just one query, but you can define a global `client.defaultOptions.watchQuery.nextFetchPolicy` policy, and here the functional version of `nextFetchPolicy` is valuable, since it allows different starting policies to be handled differently
  * #9222
  * [new documentation](https://deploy-preview-9067--apollo-client-docs.netlify.app/data/queries/#nextfetchpolicy) :tada:

Even if neither of those features matters to you, please try updating your applications with `npm i @apollo/client@beta`, and let us know how that goes!

**Comment by nathanmarks** [comment]
just out of curiosity how far off from release are we? we're trying to upgrade to address some bugs

**Comment by benjamn** [comment]
Now that we've released the first release candidate (RC), `@apollo/client@3.6.0-rc.0`, we will only be fixing bugs and improving stability before the final v3.6 release, which we anticipate by the end of this week (Friday, April 22, 2022).

This release includes support for React 18 and many other improvements. See the [`CHANGELOG.md`](https://github.com/apollographql/apollo-client/blob/release-3.6/CHANGELOG.md) for more details.

**Pull request merged**
