### PR TITLE
Fix formatting by adding newline

### PR DESCRIPTION
**Pull request by nbarbettini**
I noticed the formatting was missing on this section:

image

Turns out it was missing a newline.

### CODE REVIEW

**Comment by nbarbettini** [comment]
Hmm, I thought that would fix it, but the deploy preview doesn't look any different: https://deploy-preview-4650--apollo-client-docs.netlify.com/docs/react/advanced/caching#ignore

**Comment by hwillson** [comment]
Hmm - that is odd @nbarbettini. That section renders properly locally, but not in preview or in production. Thanks for looking into this. cc @trevorblades

**Comment by trevorblades** [comment]
This was happening because of the way that we used to handle versions in the docs, but it should be fixed when https://github.com/apollographql/apollo-client/pull/4650 gets merged. I'll get that in, and you should be able to rebase your branch and see the changes made in the deploy preview 👍

**Comment by trevorblades** [comment]
@nbarbettini there we go, much better! https://5cbe4eef00867f00088ca091--apollo-client-docs.netlify.com/docs/react/advanced/caching#ignore 🎉

**Comment by nbarbettini** [comment]
Woohoo, thanks all! 👍

**Pull request merged**
