### PR TITLE
Remove incorrect non-null assertion.

### PR DESCRIPTION
**Pull request by phryneas**
This was erroring out in a upcoming TypeScript PR at https://github.com/microsoft/TypeScript/pull/60068#issuecomment-2378120575 - the non-null-assertion here is unnecessary and incorrect.

Thank you @andarist for bringing it up.

No changeset since this doesn't touch runtime code or external types.

### CODE REVIEW

**Review by alessbell — APPROVED** [review]

**Review by jerelmiller — APPROVED** [review]
💯

**Comment by jerelmiller** [comment]
Should we have a changeset associated with this?

**Comment by Andarist** [comment]
> Should we have a changeset associated with this?

This is purely an internal change - inconsequential for end users, so I'd say this doesn't need a changeset.

**Comment by phryneas** [comment]
@jerelmiller quoting my initial post :)

> No changeset since this doesn't touch runtime code or external types.

**Comment by jerelmiller** [comment]
Gah if only I'd read a little closer 🤦🏻‍♂️. Thanks!

**Review by jerelmiller — APPROVED** [review]

**Pull request merged**
