### PR TITLE
Improve context types

### PR DESCRIPTION
**Pull request by Hugodby**
* Allow declaration merging for DefaultContext
* Use DefaultContext instead of any
* **Tests:** Linked the package manually
* **Issues:** #9249 #8902

### CODE REVIEW

**Comment by jerelmiller** [comment]
Hey @Hugodby 👋 ! Thanks so much for this contribution. Would you be willing to add a changeset to this PR? You can do so by running `npx changeset` and following the prompts. This will ensure this PR adds the proper version bump and adds an entry to our changelog.

**Comment by Hugodby** [comment]
Hello @jerelmiller , thank you for your message. I just added the changeset.

**Comment by jerelmiller** [comment]
Hey @Hugodby thanks for your patience! We had some intermittent test failures on `main` that we wanted to shore up before we could get to other PRs. 

We will get this PR tended to soon!

**Review by alessbell — APPROVED** [review]
LGTM, thanks @Hugodby!

**Pull request merged**
