### PR TITLE
Invalidate lastResult and lastError when variables change

### PR DESCRIPTION
**Pull request by jamesreggio**
This is a speculative fix for the concerns I raised in #2196.

(Read the issue to understand the fix.)

My only concern with this fix is that I'm still not 100% certain of the purpose of `isTornDown`. Would appreciate a review on that part, in particular.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@jamesreggio so great! Thank you for taking the time to look into this! `isTornDown` is used to signify if the subscription has been unsubscribed. It is used to prevent trying to call the observer if it has already been cleaned up but a data request (i.e. `result()`) is called

**Comment by jamesreggio** [comment]
@jbaxleyiii I don't think `isTornDown` functions in the way that you describe. The only logic it appears to control is the calculation of the value returned by `currentResult()`. It's possible that `isTornDown` has become vestigial through the refactoring.

If that's the case, I think this should be good to go.

**Comment by jbaxleyiii** [comment]
@jamesreggio after thinking through this more, I *think* this is the correct behavior and here is my reasoning.

> More concretely, say you have an `EpisodeDetailsScreen` with an `EpisodeDetailsQuery`. The query accepts an `episodeId` variable. Every time you navigate to the `EpisodeDetailsScreen`, the `react-apollo` recycler will reuse the same instance of the `ObservableQuery`.

Like you mentioned in the issue this is the intention

> Say you navigate to `EpisodeDetailsScreen` for `episodeId: 10`, and then you navigate away. Then you navigate to `EpisodeDetailsScreen` for `episodeId: 20`. The `ObservableQuery` will be recycled for this second navigation, but it will return the results for `episodeId: 10` initially, until the results for `episodeId: 20` have been loaded from the network.

I think this is the correct behavior because it allows you to stay on that "page" in the UI (i.e. showing the current episode's information) while also showing a loading indicator. Once the new query has resolved, it will switch the loading indicator to false and replay the new data on top of the old data. I think the previous release this was actually a bug where the data was cleared out in between and sometimes the loading state itself was never updated.

`currentResult()` should refer to the last valid result of a given query regardless of variables along with the loading state. So that `currentResult().data is potentially stale data if the `loading` key is true.

What do you think?

**Comment by jbaxleyiii** [comment]
I do agree its concerning that `isTornDown` is never set back to false. I'll work on a test case and update the `ObservableQuery` to reset it when resubscribed

**Comment by jamesreggio** [comment]
Thanks for thinking carefully about this.

The scenario you've posed is subtly different from mine. To clarify, I'm considering the following sequence of navigation:

1. Begin at `HomeScreen`
1. Push `EpisodeDetailsScreen` with `episodeId: 10`
1. Pop back to `HomeScreen`
1. Push `EpisodeDetailsScreen` with `episodeId: 20`

It's the final push that will result in the UI displaying data for `episodeId: 10` before the data for `episodeId: 20` loads.

(My argument doesn't rest on correctness as perceived by the user, but if you think about the user's intent in that series of navigation actions, there's no plausible expectation to see any data pertaining to `episodeId: 10` upon navigating to the screen for `episodeId: 20`.)

Judging by this phrase in your response — `(i.e. showing the current episode's information)` — I think you're envisioning a direct navigation from the screen for `episodeId: 10` to the screen for `episodeId: 20`. In that scenario, the recycler wouldn't have a recycled query to offer unless the prior screen was unmounted before the next screen mounts. (In practice, most routers instantiate the new screen prior to disposing the old, in order to facilitate visual transitions.)

However, I think it's possible we're off in the weeds with these examples. I can simplify my argument to this:

Query recycling is a transparent performance optimization, which is to say that as a consumer of the library, I shouldn't have to know that it exists, and I should never have to work around its presence.

When I instantiate a query with a set of variables that I've never queried before, I should not see data immediately. If data is returned to me, and I have to inspect the data to ensure it matches with the variables that I provided, I'm having to work around some aspect of the system that considered it prudent to provide me with data that I didn't ask for.

Does that change your perception of the scenario I've described?

**Comment by jbaxleyiii** [comment]
@jamesreggio thank you for the thoughtful response! I do understand the difference you have mentioned but need to think more about where that fix should be implemented. QueryRecyler has proven to pop up quite a few bugs unfortunately. Working back through your steps with some annotations:

> 1. Begin at `HomeScreen`
At this point in time, no observer exists for `EpisodeDetailsScreen` 

> 2. Push `EpisodeDetailsScreen` with `episodeId: 10`
React Apollo creates an observer tied to `EpisodeDetailsScreen`  with the variable of 10

> 3. Pop back to `HomeScreen`
React Apollo saves the observer of `EpisodeDetailsScreen`  with the variable of 10 and the data is in the store

> 4. Push `EpisodeDetailsScreen` with `episodeId: 20`
React Apollo reuses the observer of `EpisodeDetailsScreen`  and its currentResult shows the previous episode where it should actually show nothing in the store since the variable has changed.

I think this should be changed in React Apollo which should either 1. directly read from the store when reusing an observer or 2. verify that the variables of the reused observer match the new variables before assuming the data is correct in the store.

The reason I don't think the change should be done in apollo-client is because the currentResult of the observer *should* hold the latest (possibly stale) data if that observer has ever had any regardless of the variables. The data + loading indicator can be used to detect the staleness of the data but it should persist until being updated by new information from the server.

I 100% agree that the optimization shouldn't cause you as an application developer to have to work around the system for the correctness of your UI. I'm going to take a crack and this change in React Apollo and see if that is the right place to correct this.

Thoughts?

Btw, this PR did showcase a bug in currentResult and error policies which I've fixed so YAY and highlighted a possible bug with `isTornDown` 🌮

**Comment by jamesreggio** [comment]
> The reason I don't think the change should be done in apollo-client is because the currentResult of the observer should hold the latest (possibly stale) data if that observer has ever had any regardless of the variables.

Makes sense to me. I had originally failed to consider the simple case where a client calls `setVariables` with new variables — you'd certainly want to retain the stale data in that scenario (and my PR breaks this expectation).

> I think this should be changed in React Apollo which should either 1. directly read from the store when reusing an observer or 2. verify that the variables of the reused observer match the new variables before assuming the data is correct in the store.

I'm not convinced that the fix belongs entirely in `react-apollo`, but you have much better insight than I. My hunch is that the optimal fix involves `react-apollo` signaling to the `ObservableQuery` that it is going to be recycled and thus should reset its ephemeral state.

Generally speaking, this is an implementation of the _object pooling_ pattern, which is common in gaming and mobile development. Often there's a `cleanup` or `prepare` method that will reset the object prior to returning it to the pool for eventual reuse. (A well-known example is [`prepareForReuse`](https://developer.apple.com/documentation/uikit/uicollectionreusableview/1620141-prepareforreuse) from UIKit's recycler view.)

I worry about isolating the logic entirely to `react-apollo` because I expect you'll need to copy complex conditionals between packages in order to calculate the potential staleness of the data being returned. Perhaps an `ObservableQuery.prepareForReuse()` method that nullifies `lastResult` and `lastError` will work?

**Comment by jbaxleyiii** [comment]
hmm that is a very very interesting idea! It would make it much easier to implement a queryRecyler in multiple view layers instead of it residing in the client package. I think we should do that!

I'll work on it and fix the issue in `react-apollo` for backwards compat and then add a check to see if the new method exists and if it does just use it. For the 2.0 of react-apollo it will just use that method

**Comment by jamesreggio** [comment]
Sounds great to me. Do you mind @mentioning me on the relevant PRs? I'd be interested in seeing them.

**Comment by jbaxleyiii** [comment]
Closed for https://github.com/apollographql/apollo-client/pull/2214 and a future follow up for a new recycle api

**Pull request closed without merging**
