### PR TITLE
Release 2.5.0

### PR DESCRIPTION
**Pull request by benjamn**
This PR tracks changes that are slated to be released in the next minor version of `apollo-client`.

PRs that introduce minor breaking changes should be merged into the `release-2.5.0` branch instead of `master`, so that we can keep releasing patch updates in the meantime.

### CODE REVIEW

**Comment by danilobuerger** [comment]
@benjamn Whats the release schedule on this? I would like to get 2 PRs in there as well with minor breaking changes.

**Comment by benjamn** [comment]
@danilobuerger Do you have the authority to add those PRs to the milestone? https://github.com/apollographql/apollo-client/milestone/15

If not, just let me know which ones you have in mind!

**Comment by danilobuerger** [comment]
@benjamn Thanks! That worked. For when is the released planned so I get my PRs ready in time?

**Comment by benjamn** [comment]
The tallest tent-post is https://github.com/apollographql/apollo-client/pull/4338, which I would say needs at least another week of work/testing. Internally, though, our sprint goals are more about finishing the local state work so our own teams can dogfood it, and less about the final 2.5.0 release, so I think we're pretty flexible about when we merge this PR. Within the next two weeks, let's say?

**Comment by danilobuerger** [comment]
Alright, perfect.

**Comment by mbrowne** [comment]
Great work on this! Which parts of this are ready for community feedback at this point?

**Comment by hwillson** [comment]
@mbrowne I'm finishing up `react-apollo` changes that accompany these changes, which should be done today. We'll then be cutting a new `react-apollo` beta, and will open the floodgates for community testing/feedback/etc. So🤞`apolo-client@beta` and `react-apollo@beta` will include all local state changes later today, making it easier to try them out. If you have any specific feedback in the meantime though, we're always reading/listening!

**Comment by ceelian** [comment]
@hwillson will local state changes go into apollo-angular as well?

**Comment by mbrowne** [comment]
@hwillson My main feedback so far is what I said at https://github.com/apollographql/apollo-client/pull/4338#issuecomment-457290592, but I'll summarize here how I think a change to the apollo-client API might better support these use cases...

The main issue seems to be that you can't currently just get an object out of the cache without knowing in advance which fields to fetch. For people using a schema for their local state, this might not be a problem because you could get the field names for any type from the schema. But of course it can be very convenient to put objects in local state without always having to define a schema. Say you want to get the current user from local state. Currently if you just do this:

```gql
{
    currentUser @client
}
```

It says you must specify a selection of subfields. It would be great if apollo-client could be smart enough to just return the whole object (only in the case of local state of course) if you don't specify sub-fields. It wouldn't necessarily need to be through the GraphQL query API...something like `cache.getRawObject(...)` could work too. I'd be interested to hear what you or anyone else here thinks about this...

**Comment by luciannojunior** [comment]
@benjamn any updates on the release date?

**Comment by mbrowne** [comment]
FYI, I opened two new issues related to this release:
https://github.com/apollographql/apollo-client/issues/4469
https://github.com/apollographql/apollo-client/issues/4476

Both might fall in the category of feature requests more than issues, but on the other hand they affect the overall design of local state, so might be worth considering prior to finalizing this release.

Thanks for all the great work, Apollo team!

**Comment by hwillson** [comment]
Sorry for being behind on all the great comments/questions here. I'll try to answer them all at once:

https://github.com/apollographql/apollo-client/pull/4361#issuecomment-461191681: @ceelian Getting the local state changes into Apollo Angular would be great! If someone working on that project wants to get them in, then awesome!

https://github.com/apollographql/apollo-client/pull/4361#issuecomment-461206162: @mbrowne As things stand currently, that will be a bit tricky to accommodate. But I definitely get your point. I've noted this down, and will circle back on it (after the 2.5 launch). Thanks!

https://github.com/apollographql/apollo-client/pull/4361#issuecomment-461617246: @KeithGillette Very interesting idea! I've noted this down as well and will put some thought into it (after the 2.5 launch).

https://github.com/apollographql/apollo-client/pull/4361#issuecomment-463802439: @luciannojunior We're cutting `apollo-client` and `react-apollo` RC's today. So 🤞 we're publishing 2.5 next week.

https://github.com/apollographql/apollo-client/pull/4361#issuecomment-466037691: @mbrowne Thanks for opening those issues - both are great points. I'll add more comments in both of them, but in a nutshell #4469 will likely get moved to the feature request repo for now, and as you mentioned #4476 is by design. Apollo Link was never really meant to be a plugin system for Apollo Client; its focus was intended to be on the network request side of things, which `@client` no longer fits into. I definitely get your point though, and on a related note we've been talking a bit internally about what a true plugin system for Apollo Client would look like, which would help address this issue. More details on that hopefully soon.

Thanks all!

**Comment by KeithGillette** [comment]
Thanks, @hwillson! Looking forward to seeing this functionality in a stable release & the potential follow-on of `@client(override: true)` option!

@ceelian — I am using local resolver functionality on `apollo-client@2.5.0-beta.0` with `apollo-angular@1.5.0`. I am curious what sort of Apollo Angular integration you are looking for…

**Comment by hwillson** [comment]
Hi all - the Apollo Client 2.5.0 release candidate is now ready for testing. If you're interested in trying it out, update to `apollo-client@next` (and optionally `react-apollo@next`). Thanks!

**Comment by benjamn** [comment]
@hwillson Just a note that we should probably keep `release-x.y.0` branches around, in case we need to backport any bug fixes.

**Comment by hwillson** [comment]
Oops - great point @benjamn, will do!

**Pull request merged**
