### PR TITLE
Improve missing field warning

### PR DESCRIPTION
**Pull request by cesarsolorzano**
This PR improves the context of the "missing field" warning.

### CODE REVIEW

**Comment by helfer** [comment]
Thanks @cesarsolorzano! I think this might be pretty hard to read sometimes. Maybe we can print just the first 100 characters? For example, we could do `console.warn(JSON.stringify(result, null, 2)).substring(0, 100)`

**Comment by cesarsolorzano** [comment]
I agree. What do you think about using the operation name instead of the `result`?

**Comment by helfer** [comment]
Maybe we can use both? Because sometimes there's no operation name. If we use both, we should put the operation name first.

**Comment by cesarsolorzano** [comment]
I updated the PR! What do you think?

**Comment by helfer** [comment]
@cesarsolorzano hm, now that I see that it requires a lot of code changes just to pass the operation name in there I'm actually not so sure any more. I don't think this is important enough to make the code more complicated, so we should just revert that commit and then merge it, if you're okay with it. Sorry for the extra work!

**Pull request merged**
