### PR TITLE
fix more object assign

### PR DESCRIPTION
**Pull request by borisnieuwenhuis**
TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

unfortunately my editor settings are such that it hides directories called data, previous pr [#1643] was not complete

### CODE REVIEW

**Comment by borisnieuwenhuis** [comment]
no clue why i fails

**Comment by borisnieuwenhuis** [comment]
$ git clone -b move-types https://github.com/apollographql/react-apollo
Cloning into 'react-apollo'...
fatal: Remote branch move-types not found in upstream origin
Unexpected end of command stream


??

**Comment by helfer** [comment]
I think you just needed to rebase :wink:

**Comment by helfer** [comment]
Thanks! ❤️

**Pull request merged**
