### PR TITLE
Feature/remove unused @client meta

### PR DESCRIPTION
**Pull request by justinmakaila**
### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

In reference to #3475... Wish I could say a consensus was reached, but there was no activity for days and this is mission critical stuff... the client is currently spitting out invalid queries after manipulating the operations...

### CODE REVIEW

**Comment by justinmakaila** [comment]
Trying to get `apollo-utilities` hooked up to my project repo, advice around that would be great...

**Comment by hwillson** [comment]
Thanks for submitting this PR @justinmakaila! Unfortunately, this isn't something we're ready to accept. The changes you're proposing are fairly significant and have far reaching affects across the `apollo-client` codebase. I think we need to step back here a bit, and discuss the best way forward back in https://github.com/apollographql/apollo-client/issues/3475. I realize there hasn't been much traction in the issue thread yet, but it would definitely help if you could supply a small runnable reproduction that shows this issue happening (with the latest version of `apollo-client`), as a starting point. That will help move things along. I'll close this PR for now, but we can always re-open it in the future if/as needed. Thanks again for taking the time to work on this!

**Comment by hwillson** [comment]
Re-opening this to take another look (as discussed with @justinmakaila via Slack).

**Comment by hwillson** [comment]
Sorry for the long delay here @justinmakaila. We're working on a new version of `apollo-link-state` that is tightly integrated directly into Apollo Client. As part of that work, we're re-visiting how `@client` is interpreted. We'll definitely review your changes here as part of that work. More details coming shortly. Thanks!

**Comment by justinmakaila** [comment]
YESSSSSSS

**Pull request merged**
