### PR TITLE
Avoid all sub-package imports from graphql npm package.

### LINKED ISSUE #7184: Using link/schema and @graphql-tools/schema in combination and bundled by webpack results in "Cannot use GraphQLSchema from another module or realm"
**Intended outcome:**

Using `SchemaLink` with `@graphql-tools/schema`'s `makeExecutableSchema` works as expected when bundled with webpack

**Actual outcome:**

> Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

It seems that link/schema pulls in CommonJS instead of ESM when bundled with webpack, so it's different classes.

Related issue in the `@graphql-tools` repo: https://github.com/ardatan/graphql-tools/issues/1790

**How to reproduce the issue:**

Minimal repo: https://github.com/stoically/apollo-client-link-schema-webpack

**Fix**

Instead of directly reaching into `graphql` like so

https://github.com/apollographql/apollo-client/blob/d470c964db46728d8a5dfc63990859c550fa1656/src/link/schema/index.ts#L1-L2

import from the top level, like so

```js
import { execute, GraphQLSchema } from 'graphql';
```

Though, I guess the actual fix would be to dive into webpack and check what's going wrong

**Workaround**

webpack.config.js

```js
const path = require("path")

  resolve: {
    alias: {
      "graphql/execution/execute": path.resolve(
        __dirname,
        "./node_modules/graphql/execution/execute.mjs"
      ),
      "graphql/validation/validate": path.resolve(
        __dirname,
        "./node_modules/graphql/validation/validate.mjs"
      ),
    },
```

**Other things I tried which didn't work out**

- https://consiiii.me/2020/10/13/graphql-issue/
  ```js
  webpackConfig.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto",
    });
  webpackConfig.resolve = {
    extensions: [".mjs", ".ts", ".tsx", ".js", ".jsx"],
  };
  ```

- https://github.com/webpack/webpack/issues/6459#issuecomment-373723979 & https://github.com/webpack/webpack/issues/6796#issuecomment-374980347
  ```js
  const mainFields = ["main", "module"];
  // or const mainFields = ["module", "main"];
  webpackConfig.module.rules.push({
    test: /\.mjs$/,
    resolve: { mainFields },
  });
  webpackConfig.resolve = {
    mainFields,
    alias: {
      graphql: path.resolve(__dirname, "./node_modules/graphql/index.js"),
    },
  };
  ```

**Versions**

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.4/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 81.0.2
  npmPackages:
    @apollo/client: 3.3.0-beta.13 => 3.3.0-beta.13

### PR DESCRIPTION
**Pull request by stoically**
Fixes #7184 (and https://github.com/ardatan/graphql-tools/issues/1790)

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Review by benjamn — APPROVED** [review]
@stoically As I wrote in the commit message for 8a334f7381e57ff0c7ca6569abfe10828853deae, I think we can go even further here:

> Since we don't control the contents of the `graphql` package, and nested subdirectories within the `graphql` package do not have their own `package.json` files with "main" and "module" entry points (like our `@apollo/client/*` sub-packages do), it is unfortunately not safe to reach into the package to import specific items, as demonstrated by #7184.
>
> This could cause a bundle size regression for bundlers that do not perform any tree-shaking, but it's the responsibility of the `graphql` package maintainers to support selective sub-package imports, if they want to. Until that happens, `@apollo/client` must import from the `graphql` package in the only supported way: directly from the top-level package.

**Comment by AdrienLemaire** [comment]
@benjamn @stoically when upgrading `@apollo/client` to v3.3.0-beta-14, I'm getting many errors related to grapqhl.

```
ERROR in ./node_modules/graphql/index.mjs 42:0-48:205
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)
 @ ./node_modules/@apollo/client/core/LocalState.js
 @ ./node_modules/@apollo/client/core/ApolloClient.js
 @ ./node_modules/@apollo/client/core/index.js
 @ ./node_modules/@apollo/client/main.cjs.js
 @ ./src/components/ApolloPersistentProvider.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/graphql/index.mjs 60:0-97:42
Can't reexport the named export 'BreakingChangeType' from non EcmaScript module (only default export is available)
 @ ./node_modules/@apollo/client/core/LocalState.js
 @ ./node_modules/@apollo/client/core/ApolloClient.js
 @ ./node_modules/@apollo/client/core/index.js
 @ ./node_modules/@apollo/client/main.cjs.js
 @ ./src/components/ApolloPersistentProvider.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/graphql/index.mjs 29:0-40:50
Can't reexport the named export 'DEFAULT_DEPRECATION_REASON' from non EcmaScript module (only default export is available)
 @ ./node_modules/@apollo/client/core/LocalState.js
 @ ./node_modules/@apollo/client/core/ApolloClient.js
 @ ./node_modules/@apollo/client/core/index.js
 @ ./node_modules/@apollo/client/main.cjs.js
 @ ./src/components/ApolloPersistentProvider.tsx
 @ ./src/index.tsx
```

After debugging the issue, I believe e145a860a10c12fdc4d863379f32e4080597323b is the reason for this issue.

 No problem with `v3.3.0-beta-13`.

**Comment by stoically** [comment]
@AdrienLemaire Might want to open a new issue with something to reproduce as well

**Comment by ivanprotasov** [comment]
> @benjamn @stoically when upgrading `@apollo/client` to v3.3.0-beta-14, I'm getting many errors related to grapqhl.
> 
> ```
> ERROR in ./node_modules/graphql/index.mjs 42:0-48:205
> Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)
>  @ ./node_modules/@apollo/client/core/LocalState.js
>  @ ./node_modules/@apollo/client/core/ApolloClient.js
>  @ ./node_modules/@apollo/client/core/index.js
>  @ ./node_modules/@apollo/client/main.cjs.js
>  @ ./src/components/ApolloPersistentProvider.tsx
>  @ ./src/index.tsx
> 
> ERROR in ./node_modules/graphql/index.mjs 60:0-97:42
> Can't reexport the named export 'BreakingChangeType' from non EcmaScript module (only default export is available)
>  @ ./node_modules/@apollo/client/core/LocalState.js
>  @ ./node_modules/@apollo/client/core/ApolloClient.js
>  @ ./node_modules/@apollo/client/core/index.js
>  @ ./node_modules/@apollo/client/main.cjs.js
>  @ ./src/components/ApolloPersistentProvider.tsx
>  @ ./src/index.tsx
> 
> ERROR in ./node_modules/graphql/index.mjs 29:0-40:50
> Can't reexport the named export 'DEFAULT_DEPRECATION_REASON' from non EcmaScript module (only default export is available)
>  @ ./node_modules/@apollo/client/core/LocalState.js
>  @ ./node_modules/@apollo/client/core/ApolloClient.js
>  @ ./node_modules/@apollo/client/core/index.js
>  @ ./node_modules/@apollo/client/main.cjs.js
>  @ ./src/components/ApolloPersistentProvider.tsx
>  @ ./src/index.tsx
> 
> ...
> ```
> 
> After debugging the issue, I believe [e145a86](https://github.com/apollographql/apollo-client/commit/e145a860a10c12fdc4d863379f32e4080597323b) is the reason for this issue.
> 
> No problem with `v3.3.0-beta-13`.

We have the same issues on our prod project - @apollo/client/core/LocalState.js can't get  'BREAK' from 'graphql'. We have "graphql": "^15.4.0",

**Comment by benjamn** [comment]
@AdrienLemaire @ivanprotasov Please see https://github.com/apollographql/apollo-client/issues/7348#issuecomment-731209144, and, if that doesn't help, definitely open a new issue. Thanks!

**Comment by AdrienLemaire** [comment]
I confirm that adding ".mjs" to my webpack `resolve: { extensions: [] }` list fixed the issue, thanks!

**Comment by xpdmk** [comment]
Looks like one subdirectory import from graphql has been missed:
https://github.com/apollographql/apollo-client/blob/0728754db9ae0b72ba69cbee727d53a3b732ec11/src/link/http/createHttpLink.ts#L2

**Pull request merged**
