### PR TITLE
fix undefined issue with fetchMore and subscribeToMore

### PR DESCRIPTION
**Pull request by noghartt**
This PR fix some issues with `currentObservable` when we use `useQuery` hook.

**Related issues**
- #6437
- #7543
- #7974

### CODE REVIEW

**Comment by arieller** [comment]
is this relevant to useLazyQuery? because it's still crashing

**Comment by phongjimmy** [comment]
this problem still available, using with Nextjs
Any news for this pr

**Comment by joziahg** [comment]
Could we get this merged?

**Comment by brainkim** [comment]
Merged in #8553 with plans to release in 3.4. Thank you @noghartt

**Pull request closed without merging**
