### PR TITLE
Adds failing test for fetchMore utilizing a connection

### PR DESCRIPTION
**Pull request by jonmanzo**
Per request #1873, related to #1906 

Can confirm issue described in #1906 by altering the assertion from
```javascript
        for (let i = 1; i <= 20; i++) {
          assert.equal(comments[i - 1].text, `comment ${i}`);
        }
```
to
```javascript
        for (let i = 1; i <= 10; i++) {
          assert.equal(comments[i - 1].text, `comment ${i + 10}`);
        }
        for (let i = 11; i <= 20; i++) {
          assert.equal(comments[i - 1].text, `comment ${i}`);
        }
```

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@jonmanzo thank you! I'll update our bot to not require changelog for test changes only as well!

**Comment by jbaxleyiii** [comment]
@shadaj can you take a look at this?

**Comment by jonmanzo** [comment]
@jbaxleyiii If it would be helpful, I'd be happy to PR the changes I made locally to get this working, though i suspect they're not optimal based on recent commits in that space.

**Comment by shadaj** [comment]
Hi @jonmanzo, turns out the issue was introduced when I removed a check during a refactor in the `data` resolver to not write to the store during a `fetchMore`. I'll be opening a PR in a bit that should fix the issue!

**Comment by shadaj** [comment]
@jonmanzo just filed a PR against your fork at https://github.com/TeneoMedia/apollo-client/pull/1

**Comment by jonmanzo** [comment]
@shadaj Merged, retested and looks Good!  Thanks for the quick resolution!

**Comment by shadaj** [comment]
Awesome! I just added one more commit that adds an item to the changelog, since now we have non-test changes.

**Comment by jbaxleyiii** [comment]
@jonmanzo @shadaj great work everyone!! I'll merge this and add it to the next release!

**Pull request merged**
