### PR TITLE
Remove i from GraphiQL

### PR DESCRIPTION
**Pull request by Paddy-Hamilton**
### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@Paddy-Hamilton can you sign the CLA? Thanks so much!

**Comment by stubailo** [comment]
@Paddy-Hamilton upon further reading this paragraph is actually referring to the tool called `GraphiQL`: https://github.com/graphql/graphiql

So maybe we can add a link to make it more clear but it's not actually a typo.

**Comment by Paddy-Hamilton** [comment]
@stubailo Ah, that makes more sense now. I agree, adding a link to GraphiQL is a good idea.
Thanks :)

**Comment by stubailo** [comment]
Would love to reopen/merge the PR to change it to a link!

**Comment by Paddy-Hamilton** [comment]
As this branch was closed I shall create a new PR.

**Comment by stubailo** [comment]
Thanks!

**Pull request closed without merging**
