### PR TITLE
Fix reference to a field

### PR DESCRIPTION
**Pull request by patrikniebur**
Fix field reference word

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by trevorblades** [comment]
Looks good @patrikniebur! Could you rebase?

**Comment by patrikniebur** [comment]
Can you squash commit message in an easy way or do I need to rebase again?

**Comment by trevorblades** [comment]
I can squash, but I think you still need to rebase first :\ I'll try to get it in as soon as the rebase is pushed, so you won't need to do this again!

**Comment by patrikniebur** [comment]
It lets me do the merge, which I just did

**Comment by trevorblades** [comment]
Merged! Thanks @patrikniebur 🎉

**Pull request merged**
