### PR TITLE
Check if result has errors with graphQLResultHasError method

### PR DESCRIPTION
**Pull request by valentijnnieman**
Added the `graphQLResultHasError` to check not only if `result.errors` is `null`, but also empty. Was done in another place here https://github.com/apollographql/apollo-client/pull/2435 but not everywhere. This caused my mutations to get caught as an error, even though they succeeded.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@valentijnnieman great! Can you add a test case making sure this is working correctly and resolve the conflicts?

**Comment by valentijnnieman** [comment]
@jbaxleyiii Thank you for your comment! Could you maybe point me in the right direction of what to test? As far as I can tell, the `graphQLResultHasError` is already tested. Also, I think the conflicts have already been resolved.

**Comment by valentijnnieman** [comment]
I could still use some help with this! The test in `QueryManager/index.ts` on line `293` `  it('empty error array (handle non-spec-compliant server) #156'` should pick this up, but doesn't. On my system, I do a `mutate` with a `.then()` and `.catch()`, where the `.catch(errors)` fires when our `java-graphql` backend returns `errors` to be an empty array `[]`. When I made the changes to include the `graphQLResultHasErrors` method, the `catch()` does not fire!

**Comment by valentijnnieman** [comment]
@jbaxleyiii I've written a test - I was looking at queries before, but the issue was with mutations! The problem was that mutations didn't have the `graphQLResultHasError` method and so if mutations have `errors` set to an empty array, it resulted in an error.

**Pull request merged**
