### PR TITLE
feat(refetch): add optional parameter to include queries on standby when refetching

### PR DESCRIPTION
**Pull request by sondremare**
https://github.com/apollographql/apollo-client/issues/2754

### CODE REVIEW

**Comment by sondremare** [comment]
@jbaxleyiii Sorry to nag, but do you think this is something that I will be able to get merged? Or should I try and find another solution?

**Comment by jbaxleyiii** [comment]
@sondremare sorry for the delay! I'm open to merging, can you walk me through the use case for this?

**Comment by sondremare** [comment]
Ok. So we use a 3rd party pub/sub service provider to keep up to date on real time events in our app. Lets say we load some resources by graphql when you open the app, but then another user changes something, and we want that change to be reflected in our app. We then use updateQuery and updateFragment to make that happen. However, if the app has been in background or inactive for quite some while, we are unable to recover to proper state via the pub/sub provider. We then do a refetch of observed queries instead. 

However, if you have visited a certain screen (screen A) in our app and loaded the content relevant for that screen (which is now in cache). But then navigated back to another screen (screen B), then Screen A is then dismounted. Being that it is dismounted, the query for screen A is given a fetch-policy of "standby". 
User then goes inactive while on screen B. 

Time passes, user comes online again. 
We do a refetch of observable queries. Screen A is skipped because it now has a fetch-policy of "standby". So the next time the user navigates to screen A, it will use the non-refetched cache. And that cache might be outdated. For some screens in our app, it very often is.

Hope this description was ok to follow @jbaxleyiii

**Comment by sondremare** [comment]
@jbaxleyiii sorry to nag again.

**Comment by jbaxleyiii** [comment]
@sondremare no reason to apologize! We had an offsite / planning week for work last week so I was 90% MIA! Picking back up now!

**Comment by jbaxleyiii** [comment]
@sondremare perfect explanation! Lets do this!

**Comment by sondremare** [comment]
Great :D thanks

**Comment by jbaxleyiii** [comment]
Looks like travis is having trouble today! https://www.traviscistatus.com/ As soon as its cleared I'll merge in and it will be part of the release this week!

**Comment by sondremare** [comment]
@jbaxleyiii can you merge it now?

**Comment by kennethlynne** [comment]
This is seriously taking ages, is not the PR ready for merging?

**Pull request merged**
