### PR TITLE
Enable optimistic read of cache using client

### PR DESCRIPTION
**Pull request by jay1337**
To fix this issue : https://github.com/apollographql/apollo-client/issues/2222

Tests and doc should be updated...

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@jay1337 great start! Adding tests for this should be able to be done following the patterns [here](https://github.com/apollographql/apollo-client/blob/e261f052d4c432479f5cd02a7bde006449efae5f/packages/apollo-client/src/__tests__/ApolloClient.ts#L24-L850) and [here](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/__tests__/optimistic.ts#L1262)

Let me know if you have any questions!

**Comment by jay1337** [comment]
Hey !

**Comment by jbaxleyiii** [comment]
@jay1337 are you able to finish this? Or do you need me to? I'd love to get this shipped!

**Comment by jay1337** [comment]
Honestly I don't know when I will have time for that. If you can do it... I think it would take you far less time than what it would take me.

**Comment by jbaxleyiii** [comment]
@jay1337 no worries! Thank you so much for all that you have already done for the 2.0 line! It wouldn't be nearly what it is without your investigations and help! I'll happily pick this up and get it shipped!

**Comment by jay1337** [comment]
@jbaxleyiii Thanks :)

**Comment by jbaxleyiii** [comment]
@jay1337 I'm going to close this one down and open it back up when I have some time to bring it in!

**Comment by danielgreane** [comment]
Hey,
What other work was needed on this? Seems to be working 
We have a few places in our codebase where we depend on optimistic fragment and query reads (for offline support), I've run this PR locally and seems to be working fine. Is it just regression that's blocking it from being merged?

**Comment by jay1337** [comment]
@hwillson you're welcome !

**Pull request merged**
