### PR TITLE
Added missing fragmentMatcher to diffQueryAgainstStore options

### PR DESCRIPTION
**Pull request by msimulcik**
Fixes [#1526](https://github.com/apollographql/apollo-client/issues/1526)

TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
Thanks @msimulcik ! Could you add some tests to make sure the code actually works and we don't regress?

**Comment by msimulcik** [comment]
Sure. Would it be enough to cover only the case when I call mutation and expect updateQueries and reducer on query with union type to be called? I'm thinking about adding it to [test/client.ts](https://github.com/apollographql/apollo-client/blob/master/test/client.ts)

**Comment by helfer** [comment]
@msimulcik yes, I think that would be enough for now. I can add any other test cases if necessary 🙂

**Comment by helfer** [comment]
@msimulcik Actually, let me merge this and release a patch version. Would be great if you could add the test in a separate PR though.

**Comment by msimulcik** [comment]
I'm on it now. I had to go to sleep yesterday :)

**Pull request merged**
