### PR TITLE
Correct useLazyQuery types

### PR DESCRIPTION
**Pull request by sztadii**
I forked the repo because I was going to improve the error message of MockProvider,
but I realized that the latest version will give enough details, so I do not need to improve anything.
I walk around and I found one TODO, so I thought I will help with that.

### CODE REVIEW

**Comment by sztadii** [comment]
@benjamn looks like many recent PRs are failing.
Unfortunately, I do not have access to fix the netflity scripts :(

**Comment by sztadii** [comment]
@benjamn looks like it is failing because of this PR https://github.com/apollographql/apollo-client/pull/9287

**Comment by sztadii** [comment]
@benjamn looks like this PR https://github.com/apollographql/apollo-client/pull/9287 needs to be reverted. There many many plugins incompatible with version 3.0.0.
To merge this PR I created the branch from the last working commit. 
Probably your team need to discuss https://github.com/apollographql/apollo-client/pull/9287

**Comment by sztadii** [comment]
@benjamn can you look at this PR or assign someone who can approve it?

**Comment by benjamn** [comment]
@sztadii Thanks for flagging this. I will bring the reversion of #9287 up at today's team meeting.

**Review by brainkim — APPROVED** [review]

**Comment by sztadii** [comment]
@benjamn @brainkim I think we should revert that #9287, cause the number of PR is increasing.
I think we should not merge if the CI pipeline is failing and ignoring the CI will make some issues in the feature.

**Comment by sztadii** [comment]
@benjamn @brainkim it looks like this PR will solve 2 issues 🥳 #9116 and #9102.

**Review by benjamn — APPROVED** [review]
Thanks again @sztadii!

**Comment by benjamn** [comment]
@sztadii The accidental `gatsby@3` update has been reverted in #9329. That seems to fix the docs/Netlify-related tests, but let us know if anything is still broken for you. Thanks!

**Pull request merged**
