### PR TITLE
Fix minor spelling error

### PR DESCRIPTION
**Pull request by GGAlanSmithee**
Since this is just a small spelling fix, I guess I dont have to add myself to authors etc?

BTW, maybe the error message would be more actionable if it stated that it is the `uri` parameter which is missing, instead of `endpoint`? If you want me to, I could change that as well.

### CODE REVIEW

**Comment by helfer** [comment]
@GGAlanSmithee Thanks for the PR. If you could improve the error message, that would be great. And please make sure to sign the CLA!

**Comment by helfer** [comment]
@GGAlanSmithee ping

**Comment by GGAlanSmithee** [comment]
@helfer sorry about the delay. Updated the PR. Not sure how you feel regarding the link, i'll format it to your liking.

**Comment by helfer** [comment]
@GGAlanSmithee Thanks! Can you update the test that's failing now as well? It's just the one that checks this specific error message. 🙂

**Comment by GGAlanSmithee** [comment]
Hmm, trying to fix this inline in github making it a bit hard.. Should be OK now.. maybe some bad escaping in the string or something? Will fix this as soon as get the time to set up the project and run tests locally.

**Comment by helfer** [comment]
@GGAlanSmithee would be great if you could fix the test. If not, it might be quicker if I close the PR and we implement this in another PR.

**Pull request closed without merging**
