### PR TITLE
clearing out errors when fetchMore is called

### LINKED ISSUE #2533: fetchMore after being offline
This issue ticket branched off from #1413

**Intended outcome:**
`fetchMore` failing for follow up requests after encountering network errors

**Actual outcome:**
`fetchMore` should work after being offline

**How to reproduce the issue:**
https://github.com/sreucherand/react-apollo-error-template

1. Turn off network
1. Try to Fetch more. See the error
1. Turn on network
1. Try to Fetch more again

**Version**
- apollo-client@1.9.0

### PR DESCRIPTION
**Pull request by prybalko**
This fixes #2533. Does this seem like a reasonable amendment?

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by prybalko** [comment]
^

**Comment by jbaxleyiii** [comment]
@prybalko this may work, can you add a test to show the issue and how this fixes it?

**Comment by kennethlynne** [comment]
Please get this in

**Comment by jbaxleyiii** [comment]
@kennethlynne would you be able to pick up this PR and add a couple test cases for it?

**Comment by sondremare** [comment]
I will take a look at it, later this week (maybe tomorrow).

**Comment by sondremare** [comment]
For my testcase, where we fetchmore while offline, then come online and try again. This fix does not cut it. But I will continue to look into it

**Comment by sondremare** [comment]
I still receive the same error even with this fix
```
Uncaught (in promise) TypeError: Cannot set property 'networkStatus' of undefined
    at QueryStore.initQuery (queries.js:65)
    at QueryManager.fetchQuery (QueryManager.js:181)
    at ObservableQuery.js:163
    at <anonymous>
```

**Comment by sondremare** [comment]
I need some help here @jbaxleyiii. This is how I have observed fetch-more to work in apollo.
1) User opens page with associated query. Query is given an id 1, and fetched from backend
2) User wants to fetch more. Query is given a new id of 2, and the fetchMoreForQueryId is set to the original query's id, namely 1.
3) Fetch more fails due to spotty/no network. 
4a) User regains network and tries to fetch more again. Null pointers and hell breaks loose. Query is unable to recover
4b) User is still without network and tries to fetch more again, same thing occurs. Null pointers and hell breaks loose.

Not having as much intimate knowledge of the workings of apollo, I am unsure of how to recover here. When fetch more fails. should we reassign the original query back to query id 1, since we have that in cache. And only error out the fetchMore (query with id 2)? Or is there something major/minor I am missing here?

**Comment by jbaxleyiii** [comment]
@sondremare I'll take a look! This is definitely something that needs to be fixed!

**Comment by sondremare** [comment]
@jbaxleyiii You probably have seen it, but I have a PR here https://github.com/apollographql/apollo-client/pull/2906 that seems to fix the problem if used alongside react-apollo 2.1.0-beta, according to discussion in https://github.com/apollographql/apollo-client/issues/2539

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2533#issuecomment-388516303, this is no longer an issue (verified against `apollo-client` 2.3.1). Thanks very much for working on this!

**Pull request closed without merging**
