### PR TITLE
refactor to use lodash.isEqual instead of custom isEqual

### PR DESCRIPTION
**Pull request by capaj**
I was trying out a hermes cache and ran into this issue: https://github.com/convoyinc/apollo-cache-hermes/issues/414

now in order to solve this issue I think the best option is to support comparing cyclic objects in `isEqual`. Current custom implementation does not support them and runs into an infinite recursion.
Thankfully lodash does support cyclic objects just fine and since it does mirror the behaviors of the current custom `isEqual`, I hope it could be used instead. `lodash.isequal` package is already required by react-apollo so people using apollo-client in react won't see any bundle size change.

The only other way of resolving the hermes cache issue I see could be to offer a way to let a cache override the `isDifferentFromLastResult` implementation, but since `isEqual` is in the util package, IMHO it would be only a matter of time when someone would run into this problem in the future when reusing the `isEqual` on other places in apollo monorepo.

### Checklist:

- [X] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

I also inadvertently made some formatting changes as I saved the files. Hope that it's okay-it's just some formatting. 

NOTE that `apollo-utilities` package will need to be bumped by a major as I have removed the util function from the package.

### CODE REVIEW

**Comment by hammadj** [comment]
Related issue: #4824

**Comment by capaj** [comment]
@benjamn so the tests for `isEqual` in this repo will be testing already very well tested lodash implementation? Seems a like someone needs a tin foil :cowboy_hat_face:. You don't think @jdalton's implementation passes your small suite of tests? Well it does. That was the first thing I've tried.
I don't think it's necessary to test your dependecies-that's what semver is for. Anyways I will leave this PR open just in case you change your mind. I will open the one you requested as another one and you can decide which one you like better.

**Comment by capaj** [comment]
opened an alternative fix PR here: https://github.com/apollographql/apollo-client/pull/4915
I would prefer if this one got merged, but if you are keen to have your own suite of tests on `isEqual`, then #4915 is the way to go.

**Comment by benjamn** [comment]
I didn't say anything about tests in my previous comment, so I don't understand what you're objecting to. There's no reason to remove `isEqual` from `apollo-utilities`, nor to add new dependencies to the other packages.

**Comment by capaj** [comment]
@benjamn do you really think having a utility function like this is beneficial to the apollo-client's codebase: https://github.com/capaj/apollo-client/blob/3e992f93328a94cdb5ef66795cef417d6df25698/packages/apollo-utilities/src/util/isEqual.ts#L6
?

I know you can't merge this and release it just with a simple patch bump. I am not asking you to. I just think wrapping lodash with an extra function is not desirable in any JS codebase. SO IMHO best would be to deprecate it, release a patch. Then remove it and release a new major with the function removed.

**Comment by benjamn** [comment]
Adding this to the 3.0 milestone so we can revisit whether `isEqual` needs to exist in the context of other breaking changes.

**Pull request closed without merging**
