### PR TITLE
Remove the declaration of graphql-tag/bundledPrinter

### PR DESCRIPTION
**Pull request by kamilkisiela**
thanks to apollographql/graphql-tag#63 `graphql-tag@^1.3.2` contains declaration of `print` function.

### CODE REVIEW

**Comment by kamilkisiela** [comment]
And why we have [this](https://github.com/apollographql/apollo-client/blob/7d3cc53ddbc503c5143a071f4e4d8d0a626e41a6/typings.d.ts#L6-L13) in `apollo-client` and not in `graphql-tag`?

**Comment by helfer** [comment]
@kamilkisiela I have no idea why that is in apollo-client and not in graphql-tag. Can you please remove it as well (if necessary with an extra PR to graphql-tag)?

**Comment by kamilkisiela** [comment]
@helfer sure

**Comment by helfer** [comment]
Thanks @kamilkisiela!

**Pull request merged**
