### PR TITLE
remove a bunch of act calls in useSuspenseQuery test

### PR DESCRIPTION
**Pull request by phryneas**
Since this test suite is extremely slow in React 19, I want to try if removing `act` where possible speeds it up in any way.

### CODE REVIEW

**Comment by phryneas** [comment]
With this PR:

```sh
% hyperfine --runs 5 -- 'yarn test useSuspenseQuery --selectProjects "ReactDOM 18" --silent'
Benchmark 1: yarn test useSuspenseQuery --selectProjects "ReactDOM 18" --silent
  Time (mean ± σ):     10.244 s ±  1.850 s    [User: 6.877 s, System: 0.606 s]
  Range (min … max):    9.359 s … 13.551 s    5 runs
% hyperfine --runs 5 -- 'yarn test useSuspenseQuery --selectProjects "ReactDOM 19" --silent'
Benchmark 1: yarn test useSuspenseQuery --selectProjects "ReactDOM 19" --silent
  Time (mean ± σ):     68.795 s ±  1.287 s    [User: 9.550 s, System: 0.811 s]
  Range (min … max):   68.105 s … 71.078 s    5 runs
```

On `main`:
```sh
% hyperfine --runs 5 -- 'yarn test useSuspenseQuery --selectProjects "ReactDOM 18" --silent'          main
Benchmark 1: yarn test useSuspenseQuery --selectProjects "ReactDOM 18" --silent
  Time (mean ± σ):      9.385 s ±  0.907 s    [User: 6.011 s, System: 0.599 s]
  Range (min … max):    8.907 s … 11.004 s    5 runs
% hyperfine --runs 5 -- 'yarn test useSuspenseQuery --selectProjects "ReactDOM 19" --silent'          main
Benchmark 1: yarn test useSuspenseQuery --selectProjects "ReactDOM 19" --silent
  Time (mean ± σ):     77.302 s ±  1.008 s    [User: 14.714 s, System: 1.897 s]
  Range (min … max):   76.564 s … 78.775 s    5 runs
```

So, this shaves off about 10s, but does not make the big difference.

**Comment by phryneas** [comment]
I did some further investigation, and there are a few test impacted by this. I have very small sample sizes, so some of these numbers might be hiccups.

Tests that significantly changed from bad change to good change (positive numbers bad, negative numbers good)

NAME | PR improvement 19
-- | --
useSuspenseQuery `skip` option works with `startTransition` | 92
useSuspenseQuery `fetchMore` works with startTransition when setting errorPolicy as default option in ApolloClient constructor | 79
useSuspenseQuery works with startTransition to change variables | 72
useSuspenseQuery `fetchMore` works with startTransition to allow React to show stale UI until finished suspending | 70
useSuspenseQuery `skipToken` works with `startTransition` when used for options | 65
useSuspenseQuery applies updated `fetchPolicy` on next fetch when it changes between renders | 57
useSuspenseQuery fetchMore does not cause extra render | 57
useSuspenseQuery properly resolves when `skip` becomes false when returning a result that is deeply equal to data in the cache | 56
-- | --
useSuspenseQuery re-suspends the component when changing queries and using a "network-only" fetch policy | -69
useSuspenseQuery validates the GraphQL query as a query | -131
useSuspenseQuery `refetch` works with startTransition to allow React to show stale UI until finished suspending | -183
useSuspenseQuery applies `context` on next fetch when it changes between renders | -248
useSuspenseQuery applies `errorPolicy` on next fetch when it changes between renders | -252
useSuspenseQuery returns errors after calling `refetch` when errorPolicy is set to "all" | -256
useSuspenseQuery defaults refetchWritePolicy to "overwrite" | -263
useSuspenseQuery throws errors when errors are returned after calling `refetch` | -300
useSuspenseQuery tears down subscription when throwing an error on refetch | -360
useSuspenseQuery does not oversubscribe when suspending multiple times | -551
useSuspenseQuery works with useDeferredValue | -5821

**Comment by jerelmiller** [comment]
@phryneas is this something we can close now that you've got the updates to the render stream library?

**Comment by phryneas** [comment]
Absolutely!

**Pull request closed without merging**
