### PR TITLE
WIP: Add error logging for query mismatch

### PR DESCRIPTION
**Pull request by NiallBrickell**
When a server result and query are mismatched, Apollo silently catches the error (from readFromStore.ts:readStoreResolver) and returns an empty data object. This has been causing a lot of grief when running tests with mockNetworkInterface from apollo-test-utils.

Added a line to emit a warning when we get an error reading data from the store.

### CODE REVIEW

**Comment by helfer** [comment]
@NiallBrickell Thanks for the PR! Can you make sure this warning is not printed in production? 

You can import `isProduction` from `utils/environment` and then wrap the call in ` if (!isProduction()) { /* ... */ }`.

**Comment by helfer** [comment]
@NiallBrickell are you still interested in this? If so, I think we should maybe try to do the validation earlier in the process. We could either do it when the data is written to the store, or in the network interface (as a validation middleware / plugin). What do you think?

**Comment by NiallBrickell** [comment]
@helfer agreed - I'd vote for validation when writing the data to the store but I'm not too familiar with the codebase. Can take a look at it this weekend and get back to you then.

**Comment by NiallBrickell** [comment]
@helfer sorry it's taken me a while to get back - I'm not going to have any time in the near future to take a look at this. If it can wait I'm happy to revisit in a few weeks.

**Comment by cesarsolorzano** [comment]
I think this is resolve in #1638 🎉 , closing this.

**Pull request closed without merging**
