### PR TITLE
Remove reference to GlobalFetch in Typescript

### LINKED ISSUE #5367: Apollo Boost incompatible with TypeScript 3.6
TypeScript 3.6 removed the GlobalFetch object definition which is still used in packages/apollo-boost/src/index.ts

Observed behavior: Compiling prints this error: **TS2304: Cannot find name 'GlobalFetch'**
Excepted behavior: No compilation errors.

Someone had a pull request but it didn't get merged, this should be easy to fix.
https://github.com/apollographql/apollo-client/pull/5359

Other related issues https://github.com/apollographql/apollo-link/issues/1094

### PR DESCRIPTION
**Pull request by abdonrd**
The same PR as https://github.com/apollographql/apollo-link/pull/1095 for `apollo-boost`.

Fix #5367

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by abhijeet1403** [comment]
Need this fix asap. Can someone merge it?

**Comment by abdonrd** [comment]
Friendly ping to @benjamn! 🙏

**Comment by danlourenco** [comment]
What's the hold up on this one? We can't update our project to TS 3.7.3 until this issue is resolved.

**Comment by ecrofeg** [comment]
@StephenBarlow 🙏  we're stuck on TS 3.5 because of this :(

**Comment by abdonrd** [comment]
Rebased on master!

**Comment by abdonrd** [comment]
Thanks @hwillson! Can we spect a patch release soon? 🙏 

( And yes! I look forward to v3 final release! )

**Comment by hwillson** [comment]
@abdonrd It should be available now: https://github.com/apollographql/apollo-client/releases/tag/v2.6.8

**Comment by abdonrd** [comment]
Great, thanks @hwillson!

**Comment by smollweide** [comment]
Hi @abdonrd,
with upgrade from 0.4.4 to 0.4.7 I get an ts error with this configuration:

```ts
import fetch from 'node-fetch';

const client = new ApolloClient({
  uri: GRAPHQL_URL,
  fetch,
  cache: new InMemoryCache(),
});
```

But if I ignore the ts error everything is working fine:

```ts
import fetch from 'node-fetch';

const client = new ApolloClient({
  uri: GRAPHQL_URL,
  // @ts-ignore
  fetch,
  cache: new InMemoryCache(),
});
```

Was there a breaking change with 0.4.7?

THANK you

**Pull request merged**
