### PR TITLE
Add flow-types to library level

### LINKED ISSUE #1819: Support flow type without configuration
I want to typecheck using `flow` in my project but it isn't working without configuration because there is no `apollo.umd.js.flow` file.

As in apollographql/graphql-tag#98, copying `index.js.flow` to `apollo.umd.js.flow` should do the job just fine.

### PR DESCRIPTION
**Pull request by michalkvasnicak**
This PR adds support for flow type without need to configure `.flowconfig` in a project.

It's basically the same as in apollographql/graphql-tag#97.

This is good for library authors too, for example I wanted to typecheck in my library [react-apollo-graphql](https://github.com/michalkvasnicak/react-apollo-graphql) but I didn't want to force users to configure their `.flowconfig` just to typecheck apollo-client's stuff. So I made my own typings.

With this PR I can get rid of my own types and use yours :)

Closes #1819

### CODE REVIEW

**Comment by hunaczech** [comment]
+1

**Comment by michalkvasnicak** [comment]
I tested this in our fairly big project. Fixed a few errors.

For example `Request` definitions was causing an error because you can't have optional fields and then `[extra: string]: any`. [See try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwBLAO0I3ygEMBjDMAcTjgBMAlDARwFcMAzsQDeqMGGDAwdGrwGCwsRGCr4CAsRKk41OKoQCeYAAYASANYYDxsHChgufQYQB0YAJJk22GgCMYjAIkAOZkNIS8+IxkcMRQcLxepGSakmA6cHpERmYAbjQw-DZ2Djz8Qm6e3lh+AWBBoeGR0bGKCUnkqVIA2jRsbCSEJHBhMADSVgBc9YT45MEAutM0ZAYANJrevrzBAHI0ALYYAPzTQnNkwRviTvgGp2Ar65r5c7WCDwDyvgBWGHSEa62LLhYZkfZHB7neZgAA+YDIvBgMA2AF9NJhcARiORKNR6IwAEJ9RzlERdaSyeQCRTwJCqdQUjJZQwmCxWYr2UnOSpeHz+QIhMIRKII1rxRJsZJM3T6HKmfKFDCc0pOCoePk1AX1IVNUUxOLtKWdcS9fqDMEFCYGM6zeZLR6rIFbHYQk62i5XTS3e7LJ0vGhvAUCL6-f6AzSZKigkZuqF2y5whFIlGodGoOgjISPaYsdjc7MAXjAogAkNhZjRrdNZvw1loVFhKzTA4w4OYaEZJgBKNMAbgzWeIvmmxM4ZWcYGLwlRfaAA).

Also I changed `BatchingNetworkInterfaceOptions` and `NetworkIntefaceOptions` definitions to be compatible. So you can assign `BatchingNetworkInterfaceOptions` to `NetworkIntefaceOptions`. And changed definition for `NetworkInterfaceOptions.uri` to `string` instead of `?string`. I thinks this is good, because `NetworkInterface` is throwing and error if you don't define `uri` so we can typecheck this so user will get an error sooner than in runtime.

**Comment by michalkvasnicak** [comment]
Btw `index.js.flow` could be splitted to multiple files e.g. `/transport/networkInterface.js.flow`, etc. So keeping it in sync with typescript definitions could be easier and more readable in the future.

**Comment by stubailo** [comment]
I'll leave this to @jbaxleyiii to look at soon!

**Comment by jbaxleyiii** [comment]
@michalkvasnicak I'll take a look at this today! I agree that breaking it apart would be much better! We talked about doing it the first time around but opted to ship it as an enhancement / make it optional in order to get feedback from users like yourself! Thank you so much for the work on this!

I'll review it and report back today!

**Comment by jbaxleyiii** [comment]
@michalkvasnicak are you using react-apollo as well? It would be great to do the same setup there if you don't mind!

**Comment by jbaxleyiii** [comment]
@michalkvasnicak great work! Thank you so much for this!

**Comment by jbaxleyiii** [comment]
@michalkvasnicak this is great! If you could update the changelog, I'll merge it in and it can be part of the next release!

**Comment by michalkvasnicak** [comment]
@jbaxleyiii I don't use `react-apollo` directly, but we use it in another project, I can take a look at flow stuff there as well.

**Comment by jbaxleyiii** [comment]
@michalkvasnicak thank you again for this! It will be released as 1.8!

**Pull request merged**
