### PR TITLE
Add `createSchemaInterface` (WIP)

### PR DESCRIPTION
**Pull request by raix**
Usage:
```js
const client = new ApolloClient({
  networkInterface: createSchemaInterface(schema, { foo: 'context' }),
});
```

Let me know if I need to add documentation / examples etc.

cc @helfer 

fixes: #1553

### CODE REVIEW

**Comment by raix** [comment]
Seems like filesize test fails `The total gzipped size of index.min.js exceeds 27 kB.`

**Comment by helfer** [comment]
@raix yeah, importing like that from `graphql` in the main library is not going to work. The `graphql` bundle is really large. Maybe we can move this functionality into `apollo-test-utils` or a separate package? Bundle size is pretty important, so if it doesn't fit, we'll have to split it out.

**Comment by stubailo** [comment]
I think a separate package might be nice in this case.

**Comment by raix** [comment]
Ok

**Pull request closed without merging**
