### PR TITLE
Do not swallow execute errors

### PR DESCRIPTION
**Pull request by DimitryDushkin**
Fix for https://github.com/apollostack/apollo-client/issues/1132
2 of 2 PR. 1st is https://github.com/af/apollo-local-query/pull/2

### CODE REVIEW

**Comment by DimitryDushkin** [comment]
Possible something like `this.observables[queryId].error(err)` will be better. I'll try to check it today.

**Comment by helfer** [comment]
@DimitryDushkin thanks for the PR. I think the error should actually be thrown anyway through a different path that ends up calling the error handler (see the PR #950 that has more info on this). Are you using a custom network interface or something that makes that not be the case for you?

**Comment by DimitryDushkin** [comment]
@helfer I'm using https://github.com/af/apollo-local-query and without this change error is swallowed.

**Comment by helfer** [comment]
Alright, let's try it!

**Pull request merged**
