### PR TITLE
fix 'window is not defined'

### PR DESCRIPTION
**Pull request by yasupeke**
This PR is a fix for the errors that occur during SSR.

### CODE REVIEW

**Comment by benjamn** [comment]
@yasupeke Are you passing `connectToDevtools: true` explicitly to the `ApolloClient` constructor?

**Comment by yasupeke** [comment]
@benjamn Yes, passing. Should I check the `typeof window ! == 'undefined'` before passing it to the constructor?

**Comment by krisgardiner** [comment]
Just logged this issue myself, this would indeed fix it! https://github.com/apollographql/apollo-client/issues/7453

**Comment by Zack0711** [comment]
Also logged this issue too. Check the file history and find out it is caused from this commit (83d0b0a) . `defaultConnectToDevTools` has been set as the default value of `connectToDevTools` and directly use `connectToDevTools` to decide if need attach the client instance to window and set up `onBroadcast` instead of `shouldConnectToDevTools` which will check the type of window.

I think maybe it can simply add `shouldConnectToDevTools` back and set it value according to `connectToDevTools` and the type of window

**Review by benjamn — APPROVED** [review]
Looks good to me. Thanks @yasupeke!

**Pull request merged**
