### PR TITLE
Ensure that heuristics warnings are not logged in production

### PR DESCRIPTION
**Pull request by joshuabalfe**
### Checklist:

- [x] ~~If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~~
- [x] ~~Make sure all of the significant new logic is covered by tests~~
- [x] ~~If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.~~

### Overview

This PR ensures that heuristics warnings (`'WARNING: heuristic fragment matching going on!'`) don't get fired in production.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@joshuabalfe would you mind rebasing [this commit](https://github.com/apollographql/apollo-client/pull/2611/commits/63d5b2f6c73631dbadb7e459f38b5a69b6214b80) on top of master? If you can do that and add to the changelog, I'm happy to merge this!

**Comment by joshuabalfe** [comment]
@jbaxleyiii Rebased with changelog and version bump 👍

**Comment by jbaxleyiii** [comment]
@joshuabalfe thanks! Sorry to nit, could you put the change under `vNext` and reset the version? That way we can merge a couple other changes in as well without conflicts!

Thank you again for this work!

**Comment by joshuabalfe** [comment]
Amended

**Pull request merged**
