### PR TITLE
Added default query options

### PR DESCRIPTION
**Pull request by khankuan**
The default `fetchPolicy` is set to "cache-first". In some scenarios, we may want to use a different default policy, for example, to use "network-only" to maintain data integrity. To accommodate for different types of applications and scenarios, we can add an additional constructor `defaultWatchQueryOptions` that would define the default options for all queries, which can still be overwritten in each query.

### CODE REVIEW

**Comment by helfer** [comment]
Thanks for the PR @khankuan, what are some other use-cases besides the fetchPolicy? If fetch-policy is the only use-case of this that we can think of, we should just make a default fetchPolicy option instead of a general defaultVariables option, which would affect a lot more code than simply setting the fetchPolicy.

**Comment by khankuan** [comment]
At the moment that is the only use case I could think of. Will make a change soon. Cheers :)

**Comment by helfer** [comment]
Sorry I had to revert this, it broke the tests in react-apollo. `pollInterval` expects fetchPolicy to not be `cache-first` or `cache-only`. That means it's not possible to set the default fetchPolicy the way we did it in your PR. If you're still interested, let's figure out a different way to implement it so polling doesn't break.

**Comment by Xiphe** [comment]
@helfer & @khankuan, did you manage to implement this in some other way?

**Comment by khankuan** [comment]
@Xiphe Nope I ended up setting `network-only` at various places and embrace the use of cache by default.

**Pull request merged**
