### PR TITLE
Fix cache normalization for mixed fields

### PR DESCRIPTION
**Pull request by dferber90**
#### Summary

Given a query

```gql
query {
  animals {
    species {
      name
    }
  }
}
```

which gets executed twice where `species` could either be of GQL type `Dog` or `Cat`, and where the responses have the species types inlined with no `dataId` and occur sequentially, in this order:

```js
animals: [{
  __typename: 'Animal',
  species: {
    __typename: 'Cat',
    name: 'cat',
  },
}],
```

```js
animals: [{
  __typename: 'Animal',
  species: {
    __typename: 'Dog',
    name: 'dog',
  },
}],
```

the store should finally contain

```js
{
  '$ROOT_QUERY.animals.0.species': { name: 'dog' },
  ROOT_QUERY: {
    animals: [{
      generated: true,
      id: 'ROOT_QUERY.animals.0',
      type: 'id',
      typename: 'Animal',
    }],
  },
  'ROOT_QUERY.animals.0': {
    species: {
      generated: true,
      id: '$ROOT_QUERY.animals.0.species',
      type: 'id',
      typename: 'Dog',
    },
  },
}
```

However, without this PR it would wrongly contain `'$ROOT_QUERY.animals.0.species': undefined` (and some other stuff).

#### Description

It seems that the cache attempted to do cleanup of a generated object in case the reference to it gets replaced with one where we're actually provided a non-generated id. However, this also ran when a generated object's type changed, thus accidentally removing the newly generated object.

Details are in #3419

closes #3419

### CODE REVIEW

**Comment by dferber90** [comment]
🤕 This bug is still relevant and causing us issues in production

It would be helpful to get a rough idea on when somebody will get to review this, so that we can figure out whether it's worth to create a workaround in the meantime.

Thanks!

**Comment by dferber90** [comment]
It has been two weeks :( Anyone?

**Comment by tdeekens** [comment]
This is now affecting us too.

**Comment by n1ru4l** [comment]
@jbaxleyiii

**Comment by hwillson** [comment]
At a first quick glance this looks awesome @dferber90 - thanks very much for working on this! I've slotted this in for a more thorough review, and will have updates to you shortly. 🤞 this should be merged in sometime tomorrow (and will be included in next Tuesday's release).

**Comment by dferber90** [comment]
🎈Excellent, thanks for taking the time! I'm looking forward to the release

**Pull request merged**
