### PR TITLE
New `fulfillsVariables` field on ApolloQueryResult

### PR DESCRIPTION
**Pull request by dallonf**
This is an attempt to solve the problem I described in https://github.com/apollographql/react-apollo/issues/447 . I did this by adding a new field to `ApolloQueryResult` called `fulfillsVariables` - I'm not happy with the name and would absolutely like to bikeshed on it if you're OK with the general approach. 

Basically, it's true if the current value of the `data` prop is the data you've most recently asked for from that query. It may be out of date, but it's not for a different set of variables entirely. It's false in the scenario where you've just called `setVariables` and the query is still returning data from the previous variables.

This is mainly useful for `fetchPolicy: 'cache-and-network'`.

I understand this is a pretty huge addition, so I'd appreciate feedback!

TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes) **...ish? I asked for feedback in that issue on react-apollo (https://github.com/apollographql/react-apollo/issues/447) on how this might be done but never got a response**
- [x] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily **...sorry, rebasing is a mystery to me. ☹️ Could you let me know what commands you would like me to run?**
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion **I think I'll hold off on this until I get some feedback on the approach, since as I mentioned above there wasn't really consensus on this design**

### CODE REVIEW

**Comment by stubailo** [comment]
Have you tried using the `networkStatus`? http://dev.apollodata.com/react/api-queries.html#graphql-query-data-networkStatus

You should be able to check for `data.networkStatus === 2` to check if new variables are being loaded.

**Comment by dallonf** [comment]
See the issue I described in https://github.com/apollographql/react-apollo/issues/447 ... even when networkStatus is 2 or `setVariables`, there are still two possible states the data can be in (although I think this only applies to `fetchPolicy: 'cache-and-network'`), which are very difficult to distinguish: 

* Some data that resolves the query with its new variables is in the cache is now immediately available to you, and another request is going out to make sure that data is up to date
* There was insufficient data in the cache to resolve the query with the new variables; so you are still receiving the results of the query with the old variables.

**Comment by stubailo** [comment]
That's a good distinction! I definitely think we need some API to give more information about query status, other than just network status. For example, whether the data is stale, this information, and maybe some other things.

**Comment by jbaxleyiii** [comment]
@dallonf should the current `stale` status be improved to take care of this functionality?

**Comment by dallonf** [comment]
To be honest, I'm a bit fuzzy on how `stale` works or what it means. Is there any documentation on it? I can't find any in a quick search. 

As best as I can remember when I was originally looking into this, `stale` means something different, maybe along the lines of "This data has probably changed and ought to be refetched" rather than "This data does not satisfy the query with its current variables". That said, maybe it would be a good idea to merge the concepts, since the former doesn't seem to have much utility to me...? But I may be misunderstanding its purpose.

**Comment by jbaxleyiii** [comment]
@dallonf I'll look into it and get back to you! @helfer do you know who implemented it?

**Comment by dallonf** [comment]
@jbaxleyiii @helfer Any update on this?

**Comment by jbaxleyiii** [comment]
@dallonf sorry to leave you waiting! This approach looks great to me! Would you be able to resolve the conflicts and we can work to include this!

**Comment by dallonf** [comment]
Ok, thanks! I'll see what I can do about the conflicts. Might be a few days before I can get to it

**Comment by dallonf** [comment]
I swear I'll get to this someday :P

**Comment by jbaxleyiii** [comment]
@dallonf lets see if we can rework this in a link / the 2.0 branch. I'm going to close this for now but I will come back to it next week!

**Comment by dallonf** [comment]
Hahaha I _just_ got some free time to fix the merge conflicts... let me know if there's anything I can do to help. I haven't looked too closely at 2.0 yet.

**Pull request closed without merging**
