### PR TITLE
Edits for updateQuery/updateFragment docs

### PR DESCRIPTION
**Pull request by StephenBarlow**

### CODE REVIEW

**Review by brainkim — APPROVED** [review]
I an sorry for the woopsies!

**Comment by StephenBarlow** [comment]
@brainkim oh god no the whoopsies were mine!

**Comment by brainkim** [comment]
@StephenBarlow Yes I know I was saying I feel sorry 4 u ☠️

**Comment by StephenBarlow** [comment]
WRECKED

**Pull request merged**
