### PR TITLE
Use done.fail(e) instead of done(e) for forced failures

### PR DESCRIPTION
**Pull request by jamesreggio**
I hate to be the harbinger of bad news, but it looks like some of the tests have been failing silently.

I'm not 100% certain about this, but it appears that Jest and Jasmine have different semantics for the `done` function, used with async tests. Specifically, while Jasmine recognizes `done(e)` to be a failure, Jest just views any invocation of `done` to be a success, regardless of the presence of an argument.

From what I can tell, to force a failure in Jest you have to use, _sigh_, an undocumented method: `done.fail(e)`. I only discovered this after finding https://github.com/facebook/jest/issues/1801 after a fair bit of Googling. Any Jest experts are welcome to suggest an alternative.

I've manually transformed all of the sites I could find within the `apollo-client` package, but the same needs to be done for all of the other packages in the repo.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
oh no! That's no good at all! Thank you for bringing this up! I'll take a look!

**Comment by jbaxleyiii** [comment]
@jamesreggio this also explains why the jest 21 build was failing. jest 21 supports throwing via done(error).

**Comment by jbaxleyiii** [comment]
@jamesreggio I'm going to close this in favor of the jest 21 PR but THANK YOU for bringing this up!

**Comment by jbaxleyiii** [comment]
Actually jest 21 appears to not respect the enumerability of object keys so it broke nearly all of our store related tests 👎 So I think we have to stay at jest 20 for now which stinks because 21 has a nice perf jump

**Comment by jamesreggio** [comment]
Wow... I can't believe that they're going to change the semantics of `done` in Jest 21.

If the existing `done` function ignores arguments, it's easy to pass a bare `done` as the recipient of any callback without concern about the arguments passed to the callback. As soon as it begins interpreting arguments as an error condition, all kinds of existing tests are going to break.

For example, the event argument received by the `onPress` callback will change this test from passing to failing.

```
it('fires the onPress callback', done => {
  const wrapper = shallow(<TouchableOpacity onPress={done} />);
  wrapper.find('TouchableOpacity').simulate('press');
});
```

I'd keep a careful eye on whether they waffle and retract that semantic change, because I think many Jest users are in for a world of hurt.

**Comment by jamesreggio** [comment]
I shared this FUD on the most relevant Jest PR I could find, over here: https://github.com/facebook/jest/pull/4016#issuecomment-331970980

And just for notice, I didn't use a `codemod` to make the updates in this branch, so it's quite possible that I missed something.

In fact, my main concern is the relative un-greppability of the bare usage of `done` as the recipient of error callbacks, i.e.:

```
somePromise
  .then(() => done())
  .catch(done);
```

...wherein the payload to the `catch` callback is anticipated to fail the test.

All that to say, just keep an eye out for things I may have missed.

**Comment by jbaxleyiii** [comment]
cherry picked and moved to https://github.com/apollographql/apollo-client/pull/2213

**Pull request closed without merging**
