### PR TITLE
chore: update static-typing.md to add "graphql" as install dependency

### PR DESCRIPTION
**Pull request by langarus**
The graphql package is required by the generated files and thus should be included in the initial suggested packages to be installed.

### CODE REVIEW

**Review by alessbell — APPROVED** [review]
Thanks for the PR!

**Comment by alessbell** [comment]
@langarus can you please sign the CLA? Once you have I can get this merged, thanks!

**Comment by langarus** [comment]
> @langarus can you please sign the CLA? Once you have I can get this merged, thanks!

thank you, just signed it!

**Comment by phryneas** [comment]
Merging it - thank you for the PR! :)

**Pull request merged**
