### PR TITLE
Support TypeScript types for DataProxy.writeFragment and DataProxy.wr…

### PR DESCRIPTION
**Pull request by bradleyayers**
…iteQuery data.

This change allows the type of data to be passed into `ApolloClient.writeFragment` and `ApolloClient.writeQuery`. This is useful to make user TypeScript code more concise by allowing data structure to be checked inline rather than having to be pulled out into a variable.

Old pattern:

```ts
const cacheData: types.Fragment = {
  title
};
client.writeFragment({
  id: nodeId,
  fragment: Fragment,
  data: cacheData
});
```

New pattern:

```ts
client.writeFragment<types.Fragment>({
  id: nodeId,
  fragment: Fragment,
  data: {
    title
  }
});
```

### CODE REVIEW

**Comment by bradleyayers** [comment]
I'd still like to have this merged in, is there anything I can do to help nudge it along?

**Comment by jbaxleyiii** [comment]
@bradleyayers I'll take a look this week and get back to you! Sorry for the delayed response!

**Comment by jbaxleyiii** [comment]
@bradleyayers back at it for this PR! Would you be interested in applying the same changes to the master branch (the official 2.0?)

**Comment by bradleyayers** [comment]
Sure, I'll take a look at this when I get a chance.

**Comment by jbaxleyiii** [comment]
@bradleyayers I'm going to close this for now, please feel free to reopen if you want to and get time for it!

**Pull request closed without merging**
