### PR TITLE
Always return a Promise from resetStore

### PR DESCRIPTION
**Pull request by jesstelford**
Be consistent in the result of calling `client.resetStore()`

Note: I'm not familiar with the tests, and unfortunately don't have time to learn TypeScript / investigate - is someone able to point me in the right direction?

### CODE REVIEW

**Comment by jesstelford** [comment]
Oh no, [not again!?](https://github.com/apollographql/launchpad/pull/6#issuecomment-303849848) :(

**Comment by helfer** [comment]
Hey @jesstelford does this actually make a difference for you if it returns a promise or null? I.e. have you run into a case where your code broke because no promise was returned? As far as I can tell, in any functioning instance of Apollo Client that shouldn't happen.

**Comment by jesstelford** [comment]
I did! I've since wrapped it in a `Promise.resolve(client.resetStore())` so I could move on.

If I get time, I'll try back out to that change and derive a reproducable test case.

From a more architectural stand point, I feel a function which returns a promise in one instance should _always_ return a Promise, even if it is a super edge case. Similarly related is this excellent post about [Releasing the Zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony):

> Note that this applies to not just callbacks, but also to Promises and any other control-flow abstractions. If your API is frequently returning a Promise for a value that you know right now, then either you are leaving performance on the table, or your Promise implementation releases H̵͘͡e ̡wh́o͠ ̶Prom̀͟͝i̴s̀es̀ o҉̶nl̨͟y̧ ̛̛m̴͠͝a̡̛͢d̡n̴̡e͝s̸s͠, T̢҉̸h̴̷̸̢ȩ͡ ͘͠N͢͢e͏͏͢͠z̛͏͜p̸̀̕͠ȩ́͝͝r҉̛́͠d̴̀i̴̕҉͞a̴̡͝͠n̢͜͟͢͟ ̶̴̢͝h̷̕͠í̸̧̛͜v̶̢͢͡e̕͡-̸̀͝m̷͜i̛͘͞ņ̛͘͟҉d̶̶̡̧͜ ̷̛͞o̵̢͘͟͞f̶̢̀͢͢ ̶̧͟͡c̕͝h̶̀͘͘à͏o҉̴́͢s̸͘͘͝͞.̨͢͞.
> 
> So, don’t do that.

**Comment by mtripathivid** [comment]
Just testing apollo-client

**Comment by jbaxleyiii** [comment]
@jesstelford I agree that it should always return a promise, would you be able to add a test case for this change and update the changelog? I'd be happy to merge it through!

**Comment by jbaxleyiii** [comment]
This will be done in the 2.0 branch now

**Pull request closed without merging**
