### PR TITLE
Add code coverage metrics

### PR DESCRIPTION
**Pull request by thomasrockhu**
Hi, Tom from [Codecov](https://codecov.io) here.

Some of our engineers are huge fans of `apollo` and `graphql`, and I thought it would be useful to add more useful code coverage metrics to this repository. Codecov is a hosted code coverage provider with awesome features. You can checkout your first reports [here](https://codecov.io/gh/thomasrockhu/apollo-client).

I would love all the feedback you have, and please don't hesitate to reach out if you have any questions.

Cheers,
Tom

Codecov ❤️'s open source and will be free forever for OSS

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by benjamn** [comment]
@thomasrockhu Thanks for the contribution!

We were actually using Codecov until recently. @hwillson and I decided to remove it because of too much noise in reporting tiny fractional changes in code coverage that were not related to the contents of PRs: #6265. Any thoughts?

**Comment by thomasrockhu** [comment]
Hey @benjamn! Thanks for getting back to me here. I'd love to help out here if I can to tighten up the integration. What would be the ideal coverage situation for you all?

If you were seeing issues, is there a PR or commit I can take a look at? Would love to help debug or explain something that went awry.

**Comment by thomasrockhu** [comment]
Hi @benjamn, just wanted to circle back and see what I can do to help!

**Comment by jpvajda** [comment]
@benjamn reading through this chjange and given it's age, I'm curious if this is still relevant, and if we could close the PR.  cc @hwillson

**Comment by thomasrockhu** [comment]
Thanks @jpvajda. Closing this out in favor of [this PR](https://github.com/apollographql/apollo-client/pull/9678)

**Pull request closed without merging**
