### PR TITLE
Add `.d.cts` files for cjs bundles

### PR DESCRIPTION
**Pull request by phryneas**
An experiment in the context of stuff Danny Choudhury is currently doing for Redwood - maybe as a temporary fix until we can do the major with `exports`.

### CODE REVIEW

**Comment by jerelmiller** [comment]
Would this fix https://github.com/apollographql/apollo-client/issues/11895 as well by chance?

**Comment by phryneas** [comment]
> Would this fix https://github.com/apollographql/apollo-client/issues/11895 as well by chance?

Not by itself, but then they could at least import `@apollo/client/main.cjs` manually and get correct types.

**Comment by phryneas** [comment]
So, I guess we go forward with this for now, but we'll keep the right to break directly importing `.cjs` files in the next major, in favor of an `exports` field?

**Review by alessbell — APPROVED** [review]

**Review by jerelmiller — APPROVED** [review]

**Pull request merged**
