### PR TITLE
Refactor markMutationResult to be a method of QueryManager

### PR DESCRIPTION
**Pull request by morrys**
Hi guys,
this PR, through a small refactor, allows you to export the functions that implement the cache update logics following a mutation.

The main changes:
  * creation of the public method `generateUpdateQueriesInfo` in QueryManager
  * removal of the generateUpdateQueriesInfo constant within the mutate function
  * creation & export of the `markMutationOptimistic` function
  * refactor & export of the `markMutationResult` function, the main change is the addition of the queryManager parameter in order to use the generateUpdateQueriesInfo function

This is the PR of my comment to the issue [Apollo Client 3.0 Roadmap](https://github.com/apollographql/apollo-feature-requests/issues/33#issuecomment-556297370)

> Hi guys,
> I would like to propose you to export the function [markMutationResult](https://github.com/apollographql/apollo-client/blob/release-3.0/src/core/QueryManager.ts#L1439) and to be able to use the function [ generateUpdateQueriesInfo](https://github.com/apollographql/apollo-client/blob/release-3.0/src/core/QueryManager.ts#L179) through the QueryManager.
> 
> These changes allow easier integration into [the library](https://morrys.github.io/wora/docs/apollo-offline) that I created for Apollo offline capabilities.
> 
> In apollo-client 2.x.x they were accessible through the client store.
> 
> if you are interested, let me know so I will be able to offer you a PR, as soon as I can.
> 
> Thanks,
> Lorenzo

### CODE REVIEW

**Comment by morrys** [comment]
@hwillson @benjamn any news about this PR?
I'd like to have your opinion.

Thanks

**Comment by darahayes** [comment]
These changes would be really useful. We have some offline use cases that use `markMutationInit` and `markMutationComplete` (available through the `store` in Apollo Client 2.x but not in 3.x) for adding optimistic responses while holding off on actually calling the mutation until some time later (such as going online/offline). Until we have this PR merged, I don't see how that is possible in Apollo 3.0

**Comment by morrys** [comment]
@hwillson @benjamn, I can resolve conflicts this week but is it possible to know if this change can be accepted?

thanks

**Comment by wtrocki** [comment]
@benjamn since we have rc.0 version now would you still consider adding this change? We can rebase this with @morrys 

This change is critical for Apollo community and developers who are building additional features and libraries on top of Apollo Client. 

@morrys would you consider clean up changes little bit (there are some methods moved or changed that are not essential to PR itself. Hopefuly this will make it easy to accept this PR

**Comment by morrys** [comment]
@benjamn I can resolve the conflict in a short time but I noticed that the typescript formatter is different.

Any advice to make sure we use the same formatting configurations?

**Comment by morrys** [comment]
hi @hwillson and @benjamn,
I saw that you have officially released version 3.0.
Is it possible to have news about the integration of this PR?

Thank you

**Comment by austinamorusocfc** [comment]
Any eta on this?

**Comment by morrys** [comment]
Hi @hwillson, @benjamn ,
Almost a year has passed since the opening of this PR and this is the third time there are conflicts.

Is it possible to know if you intend to accept this PR or if it is not part of your plans and therefore should close it?

Thanks

**Comment by benjamn** [comment]
@morrys Thanks for the ping(s). I apologize for keeping you waiting for so long. To be transparent, this PR slipped through the cracks of my GitHub notifications, and I was only reminded about it when I saw [your recent twitter poll](https://twitter.com/m0rrys/status/1315594825438310400) this past weekend. Since we are mutuals on Twitter, I would welcome you to send me DM there if you're ever having trouble getting my attention here.

You've rebased a few times now, so I'm happy to rebase this time. I'm pretty familiar with everything that's changed recently, so I think I can resolve the conflicts quickly. Also, the default branch for this repository has changed from `master` to `main` since you first opened this PR, in case that wasn't apparent.

As for the substance of the changes, I like the separation of `markMutationOptimistic` from `markMutationResult`, but I'm not comfortable exporting them, because that implies some level of commitment to stability and backwards compatibility. The `markMutationResult` function is intentionally not a stable public API, because (as you've seen) its type signature and behavior change fairly often—and we have plans to change them again soon! I don't want to create a situation where the merge conflicts you've seen in this PR become unexpected breaking changes for your application.

That said, I would be open to making `markMutation{Result,Optimistic}` _methods_ of the `QueryManager` (rather than loose functions), so you can access them via `client["queryManager"].markMutationResult`, even though `client.queryManager` is private in TypeScript. In my mind, this abuse of the type system makes it clear that these are not stable public APIs (because `QueryManager` is not a public API), and may change in patch/minor releases of the library. If we turn these functions into methods, you would be able to access them in your code, and you would just need to be extra careful about your `@apollo/client` versions.

After I rebase, if you want to add some basic tests that capture your expectations, I can reach out to you when/if we're thinking about making a change that would cause your tests to fail.

What do you think about that compromise?

**Comment by morrys** [comment]
Hi @benjamn, I want to clarify that I made the pool to try to better understand the open source world.

Unfortunately, GitHub lacks the ability to send DMs to users and writing on twitter seems too intrusive.

As for your proposal, I find it a fair compromise 👍 
For the moment I don't see the need to add tests because it is enough to follow the repository to understand when the compatibility is broken.

The important thing when extending the functionality of a library is to have a more or less simple way to reuse the code of it

**Comment by morrys** [comment]
Hi @benjamn,
as for this PR in draft, now that version 3.x has been released, could you point me to some documentation that will help me better understand the new cache management?

Also, what about apollo-cache-persist do you plan to upgrade it to support apollo v3?

**Review by benjamn — APPROVED** [review]
@morrys Please take a look at the changes post-rebase! I think I've preserved your intentions, but let me know if I changed anything you were depending on (for example, `generateUpdateQueriesInfo` no longer exists outside of `markMutationResult`).

I also retargeted this PR against `release-3.3` rather than `main`, so I'm happy to go ahead and merge it so you can try out these changes in the next beta release of v3.3.

**Comment by benjamn** [comment]
Also, since I force-pushed to your branch, here's a backup of your original branch (before my rebase): https://github.com/apollographql/apollo-client/tree/original-morrys-mark-mutation-refactor

**Comment by morrys** [comment]
@benjamn tomorrow I will take a look at the PR and I will let you know.

Thanks

**Comment by morrys** [comment]
Perfect :)

I had refactored generateUpdateQueriesInfo just to be able to use it in the markMutationResult function.

**Pull request merged**
