### PR TITLE
Do not add __typename only to root mutations in apollo-utilities

### LINKED ISSUE #2224: addTypenameToSelectionSet do not add __typename to root query
The function `addTypenameToSelectionSet` in `tranform.ts` from `apollo-utilities` do not add `__typename` field to the root query.
But the `match` function of `HeuristicFragmentMatcher` expects cached root query objects cached to have the `__typename` field (when it's called by `graphql-anywhere` in function `executeSelectionSet` through `execContext.fragmentMatcher`).

### PR DESCRIPTION
**Pull request by valerybugakov**
It seems that __typename is required for `executeSelectionSet` for root queries. 
Fixes #2224

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@valerybugakov I'm good with this! Would you be able to add a test to make sure it isn't reverted?

**Comment by valerybugakov** [comment]
@jbaxleyiii tests have been updated appropriately: check out `should correctly add typenames` and `should be able to apply a MutationTransformer correctly`. I think they cover the issue, aren't they?

**Comment by jbaxleyiii** [comment]
@valerybugakov the CI is failing on a few tests. Can you take a look?

**Comment by valerybugakov** [comment]
@jbaxleyiii I'm getting same errors on master too. It seems that they are not related to changes from this PR.

**Comment by jbaxleyiii** [comment]
@valerybugakov gotcha! I've changed the base to the 2.0 branch. Can you add a commit or something to trigger the build?

**Comment by valerybugakov** [comment]
@jbaxleyiii triggered build again

**Comment by valerybugakov** [comment]
hey @jbaxleyiii, any chance for this to be merged soon? After 2.0 upgrade still have the same issue.

**Comment by jbaxleyiii** [comment]
Deploy preview ready!

Built with commit f940a9da56c9f277f2255331c172a0b4724e70e1

https://deploy-preview-2230--apollo-client-docs.netlify.com

**Comment by jbaxleyiii** [comment]
@valerybugakov I'm happy to merge this but I would like to see a test verifying the change? I see the tests were updated to add `__typename` to some of the documents, but want to see a test specifically showing how

```diff
+  docClone.definitions.forEach( 
-    const isRoot = definition.kind === 'OperationDefinition'; 
+    ({ kind, operation, selectionSet }: OperationDefinitionNode) => { 
-    addTypenameToSelectionSet( 
+      const isRootMutation = 
-      (definition as OperationDefinitionNode).selectionSet, 
+        kind === 'OperationDefinition' && operation === 'mutation'; 
-      isRoot, 
+      addTypenameToSelectionSet(selectionSet, isRootMutation); 
-    ); 
+    }, 
-  }); 
+  ); 
```
changes the behavior for mutations and queries. Essentially what I'm lacking is context to when this breaks in your application and a test showing what now works but didn't would be super helpful! 👍 

Happy to merge then 💯

**Comment by valerybugakov** [comment]
@jbaxleyiii I've investigated my issue to come up with some test case. Basically I receive an error because `IntrospectionMatcher` cannot find `__typename` in `ROOT_QUERY` cache entry here:

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/fragmentMatcher.ts#L125-L131

It's called when I spread a fragment into root of the query:

```gql
query Something {
 ...fragmentSpread
}

fragment fragmentSpread on RootQueryType {
  field
}
```

It would be nice to have a support for such spreads.

**Comment by jbaxleyiii** [comment]
@valerybugakov can you take a look at the test failures?

**Comment by valerybugakov** [comment]
@jbaxleyiii @stubailo all tests should be ok now

**Comment by jbaxleyiii** [comment]
@valerybugakov the CI is still failing on most of the tests?
```
Test Suites: 6 failed, 9 passed, 15 total
Tests:       44 failed, 3 skipped, 256 passed, 303 total
Snapshots:   2 passed, 2 total
Time:        43.618s
Ran all test suites.
```

**Pull request closed without merging**
