### PR TITLE
fix: address React StrictMode error when query resolves after unmount

### PR DESCRIPTION
**Pull request by grxy**
### Motivation
`useQuery` can log a warning in React's `StrictMode` when a component is unmounted before the query has been resolved.

### Changes
- Adds a failing test to demonstrate the issue
- Checks if a component is mounted before running the `forceUpdate` function

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

Resolves https://github.com/apollographql/react-apollo/issues/3635

### CODE REVIEW

**Comment by benjamn** [comment]
@grxy Would you mind rebasing?

**Comment by nodabladam** [comment]
I believe I am experiencing the same problem.  It would be great to get this into apollo 3

**Comment by rajohan** [comment]
Got the same problem, tried your solution by manually making the changes in the node_modules folder and it fixes it. Would be nice to get this added.

**Comment by joonhocho** [comment]
This seems to break SSR. https://github.com/apollographql/apollo-client/issues/6386

**Pull request merged**
