### PR TITLE
Pass non-optimistic query to subscribeToMore  #3062

### PR DESCRIPTION
**Pull request by bendenoz**
Subscriptions will make optimistic queries in the cache become non-optimistic with `subscribeToMore`. See #3062  for unwanted effects

This PR addresses this issue

### Checklist:

- [X] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by hkjorgensen** [comment]
It would be great to get this merged! Currently, subscriptions and optimistic updates don't work when used together.

**Comment by hkjorgensen** [comment]
@jbaxleyiii @peggyrayzis sorry for the spam, but this fix looks ready-ish for an annoying bug when using subscriptions. Can one of you take a look so we can get the ball rolling, please :-)

**Comment by bendenoz** [comment]
rebased with master

**Comment by bendenoz** [comment]
thanks 👍

**Pull request merged**
