### PR TITLE
Set pollInterval to undefined when calling stopPolling

### PR DESCRIPTION
**Pull request by leoasis**
This PR fixes the bug in https://github.com/apollographql/react-apollo/issues/483

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by leoasis** [comment]
Let me know if there is a better way (or if this is good enough) to write the test that doesn't rely too much on doing `setImmediate`s (because of Promises) and maybe also a better way to detect we're not polling from the subscription handler.

**Comment by helfer** [comment]
@leoasis Thanks! This looks fine. Did you run the test before implementing the fix to make sure it fails without the fix?

**Comment by leoasis** [comment]
@helfer yes, I did. If you comment out the line I added in `stopPolling` the test fails when reaching the line that executes with `done(new Error('should not start polling, already stopped'));`

**Comment by helfer** [comment]
Excellent, that's what I like to hear 🙂 Thanks @leoasis !

**Pull request merged**
