### PR TITLE
Fix mutations

### PR DESCRIPTION
**Pull request by jbaxleyiii**
@jay1337 @seeden this *should* fix the mutations / queries bug in react-apollo (the `rc7`).

Could you try it out for me? (its released)

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
Deploy preview ready!

Built with commit eec6a6ff7e958e049d908210724e53d04b194470

https://deploy-preview-2375--apollo-client-docs.netlify.com

**Comment by seeden** [comment]
Hi @jbaxleyiii 

It is **not working**. I used next versions:
```js
    "apollo-cache-inmemory": "^0.2.0-rc.4",
    "apollo-client": "^2.0.0-rc.7",
    "apollo-link": "^0.8.0",
    "apollo-link-http": "^0.8.0",
    "apollo-link-batch-http": "^0.4.0",
    "apollo-link-retry": "^0.8.0",
    "apollo-link-dedup": "^0.6.0",
    "react-apollo": "^2.0.0-rc.0",
```

**Comment by bkniffler** [comment]
@jbaxleyiii @seeden This release definitely resolved the issue I reported at https://github.com/apollographql/apollo-client/issues/2333#issuecomment-338222643

Thanks for your hard work!

**Comment by seeden** [comment]
@bkniffler really? It is working for you? I have tried rc7 but without success :(

**Comment by bkniffler** [comment]
Yes, I'm pretty sure.  I was using previous version of cache-inmemory and apollo-client and tried the mutation 10 minutes ago, but no change in my ui. After updating these packages it works.

**Comment by seeden** [comment]
@bkniffler  can you paste your library versions? Thanks

**Comment by bkniffler** [comment]
Sure: 

```
    "apollo-cache-inmemory": "^0.2.0-rc.4",
    "apollo-client": "^2.0.0-rc.7",
    "apollo-fetch": "^0.6.0",
    "apollo-link": "^0.8.0",
    "apollo-link-http": "^0.8.0",
```

**Comment by bkniffler** [comment]
oh, and  "react-apollo": "2.0.0-rc.0", "graphql-tag": "2.5.0"

**Comment by jay1337** [comment]
@jbaxleyiii It solves the issue of React components not updated after a mutation changing the data. But I have still many issues opened...

**Pull request merged**
