### PR TITLE
Expose dataIdFromObject in addition to dataId

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
As discussed in [#1657 (comment)](https://github.com/apollographql/apollo-client/issues/1657#issuecomment-299536799)

TODO:
- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@helfer I think I can use some help with the rebasing (I'm afraid I'll break something while doing so 😕)

**Comment by helfer** [comment]
You can just remove all commits after the one I made, then run `git fetch`, then `git rebase origin/master` and finally `git push --force`.

**Comment by MichaelDeBoey** [comment]
@helfer I think it went well 🙂

**Comment by MichaelDeBoey** [comment]
@helfer It looks like there's something wrong with Travis? 😕

**Comment by helfer** [comment]
Actually for the docs, I think if you add a typedoc string to the definition of `public dataIdFromObject`, it will show up automatically in our API docs. Maybe that's the best place to document it.

**Comment by MichaelDeBoey** [comment]
Docs are added in apollographql/react-docs/#221

Should I still add a typedoc string to the definition?

**Comment by MichaelDeBoey** [comment]
@helfer You're welcome! 🙂
Travis seems to fail now, but don't know why 😕
My changes passed, you only changed the text so strange that doesn't pass 😕

**Comment by helfer** [comment]
It seems that the react-apollo tests are quite brittle at the moment, which is why we're seeing these test failures.

**Comment by MichaelDeBoey** [comment]
Looks good now I think 🙂

**Comment by MichaelDeBoey** [comment]
@helfer I think we need to release this one, 'cause the docs are already online, so that may cause confusion If we don't release this one I think? 😕

**Comment by helfer** [comment]
I'll release it soon. Not many people read the docs on weekends, so I'm sure it will be fine 🙂

**Pull request merged**
