### PR TITLE
Remove nested fragments with client directive

### LINKED ISSUE #5192: Nested fragment spreads with `@client` directive is not removed from query
**Intended outcome:**

Nested fragment spreads with `@client` directive which is not used in query is removed from query.

**Actual outcome:**

Fragment spreads with `@client` directive remains on query.
This violates GraphQL Spec.
https://graphql.github.io/graphql-spec/June2018/#sec-Fragments-Must-Be-Used
> Defined fragments must be used within a document.

As an actual problem, GraphQL server returns 422 error because of this.

**How to reproduce the issue:**

I think this problem is caused by `removeDirectivesFromDocument` function in `apollo-utilities`. Add below test case to `packages/apollo-utilities/src/__tests__/transform.ts` and it fails.
``` js
  it('should remove nested fragment spreads and definitions associated with the removed directive', () => {
    const query = gql`
      query Simple {
        networkField
        field @client {
          ...ClientFragment
        }
      }

      fragment ClientFragment on Thing {
        ...NestedFragment
      }

      fragment NestedFragment on Thing {
        otherField
        bar
      }
    `;

    const expected = gql`
      query Simple {
        networkField
      }
    `;

    const doc = removeDirectivesFromDocument(
      [{ name: 'client', remove: true }],
      query,
    );
    expect(print(doc)).toBe(print(expected));
  });
```

test result
```sh
Summary of all failing tests
 FAIL  packages/apollo-utilities/src/__tests__/transform.ts
  ● removeDirectivesFromDocument › should remove nested fragment spreads and definitions associated with the removed directive

    expect(received).toBe(expected) // Object.is equality

    - Expected
    + Received

      query Simple {
        networkField
      }

    + fragment NestedFragment on Thing {
    +   otherField
    +   bar
    + }
    +

      222 |       query,
      223 |     );
    > 224 |     expect(print(doc)).toBe(print(expected));
          |                        ^
      225 |   });
      226 |
      227 |   it('should not remove fragment spreads and definitions used without the removed directive', () => {

      at Object.<anonymous> (src/__tests__/transform.ts:224:24)
```
**Versions**

  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 63.0.1
    Safari: 12.1.2
  npmPackages:
    apollo-boost: file:packages/apollo-boost => 0.4.4
    apollo-cache: file:packages/apollo-cache => 1.3.2
    apollo-cache-inmemory: file:packages/apollo-cache-inmemory => 1.6.3
    apollo-client: file:packages/apollo-client => 2.6.4
    apollo-utilities: file:packages/apollo-utilities => 1.3.2

### PR DESCRIPTION
**Pull request by HsuTing**
### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

I have tried to fix #5192. And if this “pr” cause any problems,please let me know.

### CODE REVIEW

**Comment by HsuTing** [comment]
Does this `pr` have any problems? It`s important to me for fixing some error. Please merge ASAP.

**Comment by mrerichoffman** [comment]
I'm also interested in getting this merged ASAP.

**Comment by giautm** [comment]
Ant updates? I have same issue with apollo-link-rest.

**Comment by giautm** [comment]
@benjamn Hi, can you review this issue?

**Comment by hwillson** [comment]
Sorry for the long delay in responding. If you still think this is an issue, would you mind rebasing / re-creating this PR? Thanks!

**Comment by hwillson** [comment]
If anyone is interested in rebasing this PR (against `main`) we'll take another look. Closing for now. Thanks!

**Comment by giautm** [comment]
@hwillson : I just reopen PR and rebase, please take a look: https://github.com/apollographql/apollo-client/pull/6892

**Pull request closed without merging**
