### PR TITLE
Add broken link checker and circle ci integration

### PR DESCRIPTION
**Pull request by evans**
Here is a list of broken links:

/docs/react/ - http://localhost:4000/docs/react/essentials/get-started
/docs/react/essentials/get-started.html - http://localhost:4000/docs/react/essentials/direct-access.html
/docs/react/features/server-side-rendering.html - http://localhost:4000/docs/react/features/auth.html
/docs/react/advanced/subscriptions.html - http://localhost:4000/docs/react/advanced/boost-migration
/docs/react/advanced/caching.html - http://localhost:4000/docs/react/recipes/fragment-matching.html
/docs/react/advanced/caching.html - http://localhost:4000/docs/react/advanced/docs/link/links/state
/docs/react/recipes/2.0-migration.html - http://localhost:4000/docs/react/api/react-apollo/mutations.html#graphql-mutation-options-update
/docs/react/recipes/meteor.html - http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.constructor
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L78
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L201
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L225
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L253
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L279
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L294
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L303
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L320
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L392
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L412
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L67
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L113
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L153
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L240
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L376
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L428
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L282
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L466
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L497
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/ObservableQuery.ts#L489
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L42
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L34
/docs/react/api/apollo-client.html - https://github.com/apollostack/apollo-client/blob/master/core/networkStatus.ts#L4
/docs/react/api/react-apollo.html - http://localhost:4000/docs/react/api/mutations.html
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/features/cache-updates.html#normalization
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/features/fragments.html
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/features/cache-updates.html
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/setup#graphql-config-name
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/setup#compose
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/network-layer.html#MutationBatching
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/caching.html#direct
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/caching.html#writequery-and-writefragment
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/caching.html#readquery
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/basics/caching.html#readfragment
/docs/react/basics/mutations.html#optimistic-ui - http://localhost:4000/docs/react/features/cache-updates.html#updateQueries
/docs/react/basics/setup.html - http://localhost:4000/docs/react/features/subscriptions.html
/docs/react/basics/setup.html - http://localhost:4000/docs/react/basics/caching.html
/docs/react/basics/setup.html - http://localhost:4000/docs/react/recipes/server-side-rendering.html
/docs/react/basics/queries.html#graphql-query-data-loading - http://localhost:4000/docs/react/reference/index.html#ApolloError
/docs/react/basics/queries.html#graphql-query-data-loading - http://localhost:4000/docs/react/recipes/pagination.html
/docs/react/basics/queries.html#graphql-query-data-loading - http://localhost:4000/docs/react/basics/cache#ApolloClient.readQuery
/docs/react/basics/queries.html#graphql-query-data-loading - http://localhost:4000/docs/react/basics/cache#ApolloClient.readFragment
/docs/react/features/caching.html#updating-the-cache-after-a-mutation - http://localhost:4000/docs/react/features/apollo-client-..ient.html#DataProxy
/docs/react - https://www.apollographql.com/docs/why-apollo.html
/docs/react - https://www.apollographql.com/docs/integrations.html
/docs/react - https://www.apollographql.com/docs/react-apollo-migration.html
/docs/react - https://www.apollographql.com/docs/essentials/get-started.html
/docs/react - https://www.apollographql.com/docs/essentials/queries.html
/docs/react - https://www.apollographql.com/docs/essentials/mutations.html
/docs/react - https://www.apollographql.com/docs/essentials/local-state.html
/docs/react - https://www.apollographql.com/docs/features/error-handling.html
/docs/react - https://www.apollographql.com/docs/features/pagination.html
/docs/react - https://www.apollographql.com/docs/features/optimistic-ui.html
/docs/react - https://www.apollographql.com/docs/features/server-side-rendering.html
/docs/react - https://www.apollographql.com/docs/features/performance.html
/docs/react - https://www.apollographql.com/docs/features/developer-tooling.html
/docs/react - https://www.apollographql.com/docs/advanced/boost-migration.html
/docs/react - https://www.apollographql.com/docs/advanced/subscriptions.html
/docs/react - https://www.apollographql.com/docs/advanced/network-layer.html
/docs/react - https://www.apollographql.com/docs/advanced/caching.html
/docs/react - https://www.apollographql.com/docs/advanced/fragments.html
/docs/react - https://www.apollographql.com/docs/recipes/authentication.html
/docs/react - https://www.apollographql.com/docs/recipes/2.0-migration.html
/docs/react - https://www.apollographql.com/docs/recipes/static-typing.html
/docs/react - https://www.apollographql.com/docs/recipes/react-native.html
/docs/react - https://www.apollographql.com/docs/recipes/babel.html
/docs/react - https://www.apollographql.com/docs/recipes/webpack.html
/docs/react - https://www.apollographql.com/docs/recipes/meteor.html
/docs/react - https://www.apollographql.com/docs/recipes/recompose.html
/docs/react - https://www.apollographql.com/docs/api/apollo-client.html
/docs/react - https://www.apollographql.com/docs/api/react-apollo.html
/docs/react - https://www.apollographql.com/docs/essentials/get-started
/docs/react - https://www.apollographql.com/docs/integrations.html#vue
/docs/react - https://www.apollographql.com/docs/integrations.html#ember
/docs/react - https://www.apollographql.com/docs/integrations.html#polymer

### CODE REVIEW

**Comment by hwillson** [comment]
Just a quick update here - as soon as https://github.com/apollographql/hexo-typescript-api-box/pull/9 is merged, we'll be able to wrap up this PR.

**Comment by abernix** [comment]
I like the prospect of the broken link checker, but I'm opposed to it being integrated into per-repository deployments of the documentation (like it is here, only existing within `apollo-client`) rather than at a higher level where it can benefit all of them equally.

Can we consider another option here? Namely, by using a `npm test` command powered by the `meteor-theme-hexo` (or even via the existing [`chexo`](https://github.com/abernix/chexo) package?) without making the command substantially more verbose [as is happening here](https://github.com/apollographql/apollo-client/pull/3313/files#diff-d34809464730fe7381f1acde5e58c8e1R18).  This extra boilerplate just complicates the `package.json` and makes more places for us to update this logic as it evolves.  This is in the same regard as my comments on https://github.com/apollographql/engine-docs/pull/138.

(As another option, I've also just been using [this tool](https://www.deadlinkchecker.com/) to check our site in its entirety.)

That said, I think we should absolutely fix the broken links, which https://github.com/apollographql/hexo-typescript-api-box/pull/9 will _mostly_ do.

**Comment by hwillson** [comment]
Great points @abernix - thanks! I was on the fence here a bit as well, especially since the link checker does noticeably slow down CI. I'm all for adjusting this PR just to fix the outstanding links, then addressing the link checker somewhere else.

**Comment by hwillson** [comment]
I've merged the link checker and fixed links here, but kept the link checker disabled for now (until we decide how we want to handle this). Thanks!

**Pull request merged**
