### PR TITLE
useSubscription: keep subscription Concast alive if new in-flight subscription subscribes at the same time last in-flight subscription unsubscribes

### PR DESCRIPTION
**Pull request by Hsifnus**
### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

This PR attempts to address the `useSubscription` React hook issue outlined in https://github.com/apollographql/apollo-client/issues/10695. It is also related to https://github.com/apollographql/apollo-client/issues/10693 but does not directly address it outside of the case in which unsubscription and resubscription to the same subscription observable happens in the same frame.

### CODE REVIEW

**Comment by phryneas** [comment]
Could you please try if an approach like in https://github.com/apollographql/apollo-client/pull/10629 would solve the problem as well? That would make it a much smaller change and only affect people that use the `useSubscription` hook regarding bundle size.

**Comment by Hsifnus** [comment]
> Could you please try if an approach like in #10629 would solve the problem as well? That would make it a much smaller change and only affect people that use the `useSubscription` hook regarding bundle size.

Figured out a way to immediately stop receiving subscription values in `useSubscription` while effectively deferring unsubscription from the `Concast` via `setTimeout` in 8f7156b

As such, I have shifted the PR to impact `useSubscription` instead of `Concast`.

**Comment by phryneas** [comment]
@Hsifnus I believe you could circumvent the additional subscription doing something like this - what do you think?

```diff
@@ -117,8 +117,10 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
       return;
     }
 
+    let subscriptionStopped = false;
     const subscription = observable.subscribe({
       next(fetchResult) {
+        if (subscriptionStopped) return;
         const result = {
           loading: false,
           // TODO: fetchResult.data can be null but SubscriptionResult.data
@@ -142,6 +144,7 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
         }
       },
       error(error) {
+        if (subscriptionStopped) return;
         setResult({
           loading: false,
           data: void 0,
@@ -151,6 +154,7 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
         ref.current.options?.onError?.(error);
       },
       complete() {
+        if (subscriptionStopped) return;
         if (ref.current.options?.onComplete) {
           ref.current.options.onComplete();
         } else if (ref.current.options?.onSubscriptionComplete) {
@@ -163,14 +167,9 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
       // immediately stop receiving subscription values, but do not unsubscribe
       // until after a short delay in case another useSubscription hook is
       // reusing the same underlying observable and is about to subscribe
-      const ignoredSubscription = observable.subscribe({
-        next() {},
-        error() {},
-        complete() {},
-      });
-      subscription.unsubscribe();
+      subscriptionStopped = true;
       setTimeout(() => {
-        ignoredSubscription.unsubscribe();
+        subscription.unsubscribe();
       });
     };
   }, [observable]);
```

**Comment by Hsifnus** [comment]
> @Hsifnus I believe you could circumvent the additional subscription doing something like this - what do you think?
> 
> ```diff
> @@ -117,8 +117,10 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
>        return;
>      }
>  
> +    let subscriptionStopped = false;
>      const subscription = observable.subscribe({
>        next(fetchResult) {
> +        if (subscriptionStopped) return;
>          const result = {
>            loading: false,
>            // TODO: fetchResult.data can be null but SubscriptionResult.data
> @@ -142,6 +144,7 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
>          }
>        },
>        error(error) {
> +        if (subscriptionStopped) return;
>          setResult({
>            loading: false,
>            data: void 0,
> @@ -151,6 +154,7 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
>          ref.current.options?.onError?.(error);
>        },
>        complete() {
> +        if (subscriptionStopped) return;
>          if (ref.current.options?.onComplete) {
>            ref.current.options.onComplete();
>          } else if (ref.current.options?.onSubscriptionComplete) {
> @@ -163,14 +167,9 @@ export function useSubscription<TData = any, TVariables extends OperationVariabl
>        // immediately stop receiving subscription values, but do not unsubscribe
>        // until after a short delay in case another useSubscription hook is
>        // reusing the same underlying observable and is about to subscribe
> -      const ignoredSubscription = observable.subscribe({
> -        next() {},
> -        error() {},
> -        complete() {},
> -      });
> -      subscription.unsubscribe();
> +      subscriptionStopped = true;
>        setTimeout(() => {
> -        ignoredSubscription.unsubscribe();
> +        subscription.unsubscribe();
>        });
>      };
>    }, [observable]);
> ```

Looks like that would be the most straightforward way of circumventing the second subscription. Implemented something similar to that in [c890e45](https://github.com/apollographql/apollo-client/pull/10718/commits/c890e45ea26bcdd552e74bfa84968e2dc5cc26bb)

**Review by phryneas — APPROVED** [review]
Looks good to me - let's get this in!

**Pull request merged**
