### PR TITLE
Add operationName in Redux actions whenever that's possible

### LINKED ISSUE #1619: feature suggestion: operationName included in redux actions whenever possible
Hello!

In the process of incorporating apollo-client in my app that heavily uses its own redux store, I find myself wanting `operationName` to be found in all Apollo dispatched actions where available (if the query/mutation name exists). For example, a component's initial query dispatches an `APOLLO_QUERY_RESULT` whose payload contains `operationName`, but subsequent cached queries dispatch `APOLLO_QUERY_RESULT_CLIENT` whose payload doesn't have `operationName`. Is it feasible to provide `operationName` everywhere it can apply? My workaround right now is to look into the `action.document` for the query name (which I assume is how operationName is determined).

I'm watching these action types in order to keep my original redux store in sync with the apollo-client store. I can't quite fully rely on the apollo-client store right now because:

1. I've built a lot of convenience around reselect and redux's `connect` that has me quite reliant on the way I grab props. With apollo-client, I lose the dependency injection and instead have to manually pass down props.
2. My client side models carry extra properties for UX needs. I'd have to perform some hefty refactoring to decouple client only properties in a way that compliments react-apollo's ability to automatically update UI based on server (cache) changes.

I'm new at GraphQL and Apollo so this has been my approach without much guidance. Anyone go through a similar experience?

Thanks 😃

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #1619

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@helfer That were the only ones that I've found in `actions.ts` that didn't have `operationName` and had a `documentNode` where I could get the `operationName` from.

**Comment by helfer** [comment]
Ok, I think `QUERY_RESULT_CLIENT` and `QUERY_STOP` should probably also have the operation name.

**Comment by MichaelDeBoey** [comment]
@helfer Can you point me in the right direction to find the POJO please?

Also no tests I had to change for `QUERY_RESULT_CLIENT`, don't know if that's normal?

**Comment by MichaelDeBoey** [comment]
@helfer Did you have the time to look at this?

**Comment by helfer** [comment]
@MichaelDeBoey I didn't have time until now, sorry. For `QUERY_STOP` I think you can use something like `this.observableQueries[queryId].observableQuery.options.query` to get the operationName if necessary.

**Comment by MichaelDeBoey** [comment]
@helfer I added the `operationName` to the `APOLLO_QUERY_STOP` like you said, but I can't find how I should resolve the failing tests 😕
Maybe you can point me in the right direction?

**Comment by MichaelDeBoey** [comment]
I also don't understand the massive coverage drop 😕

**Comment by MichaelDeBoey** [comment]
@helfer Can you point me in the right direction to solve the failing tests?

**Comment by MichaelDeBoey** [comment]
@helfer Can you point me in the right direction to solve the failing tests please?

**Comment by helfer** [comment]
Hey @MichaelDeBoey, I was at some conferences for the last week, so I didn't have time to review it again. I'll take a look now.

PS: Yes, drop in coverage is because of failing tests, no need to worry about that 🙂

**Comment by helfer** [comment]
Ok, I think the test failures are probably due to the latest commit that added the operationName to the STOP_QUERY action. I think the function now throws an error, but it's caught somewhere unexpected and thus all the error messages are very confusing. If you're okay with it, we can simply rebase and remove that commit, then merge into master, because I don't think it's critical to have operationName on that action.

Let me know what you think.

**Comment by MichaelDeBoey** [comment]
@helfer Yeah no problem for me 🙂

**Comment by MichaelDeBoey** [comment]
@helfer I think this one looks good now? 🙂

**Comment by helfer** [comment]
LGTM, thanks @MichaelDeBoey ! :heart:

**Comment by MichaelDeBoey** [comment]
You're welcome @helfer 😉

**Pull request merged**
