### PR TITLE
Added webpackbin to issue template

### PR DESCRIPTION
**Pull request by jbaxleyiii**
@helfer @stubailo I created a webpackbin for apollo 💯 

This should make it even easier for people to create reproductions (it includes apollo-client, react-apollo, and a server built using graphql-tools!)

https://www.webpackbin.com/bins/-KjAoAmOoExoJhPIpPu1

I've also submitted it to be a boilerplate https://github.com/cerebral/webpackbin/issues/21

### CODE REVIEW

**Comment by helfer** [comment]
Looks interesting! Would you recommend we use this in place of https://github.com/apollographql/react-apollo-error-template ?

**Comment by jbaxleyiii** [comment]
@helfer it could be an easier on ramp, I think they both are valuable!

**Comment by helfer** [comment]
Ok, sounds good to me!

**Comment by stubailo** [comment]
This is dope! 👌

**Pull request merged**
