### PR TITLE
Document changes in #8875

### PR DESCRIPTION
**Pull request by brainkim**

### CODE REVIEW

**Comment by brainkim** [comment]
Commits are messed up, hold while I fix.

**Comment by StephenBarlow** [comment]
@brainkim I have pushed some edits that make _assumptions!_ Please review and make sure I did not make dreaded _false_ assumptions 🙏

**Comment by brainkim** [comment]
These *assumptions* do not make a *something* out of *u* and *me*. Good callout about the cache stuff. Thanks!

**Review by benjamn — APPROVED** [review]
Made a couple formatting tweaks, but this LGTM. Thanks for taking care of this @brainkim!

**Comment by benjamn** [comment]
Let's use the `release-3.5` branch to collect docs changes like this.

**Pull request merged**
