### PR TITLE
Merge QueryBaseOptions, QueryOptions, and ModifiableQueryOptions into one type.

### PR DESCRIPTION
**Pull request by DCtheTall**
### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by DCtheTall** [comment]
This PR fixes [#6177](https://github.com/apollographql/apollo-client/issues/6177)

**Comment by DCtheTall** [comment]
@hwillson friendly ping 😄

**Comment by DCtheTall** [comment]
@hwillson friendly ping. Is this something you want to support?

**Review by benjamn — APPROVED** [review]
Great improvement, @DCtheTall!

I changed the target branch to `release-3.3` just because the removal of `QueryBaseOptions` (which was exported) could theoretically be a disruptive change, but I don't anticipate that being a problem for many people, and the fix is easy (just use `QueryOptions` instead).

**Comment by DCtheTall** [comment]
> I changed the target branch to release-3.3 just because the removal of QueryBaseOptions (which was exported) could theoretically be a disruptive change, but I don't anticipate that being a problem for many people, and the fix is easy (just use QueryOptions instead).

@benjamn totally understand/agree. I did a search on GitHub for its usage and found it is used virtually nowhere, but I can understand the desire to gate a potentially breaking change behind a release.

**Pull request merged**
