### PR TITLE
Added recipe for cache persistence

### PR DESCRIPTION
**Pull request by peggyrayzis**
Hold off on merging until we publish `apollo-cache-persist`.

### CODE REVIEW

**Comment by jamesreggio** [comment]
Looks delicious 🍜

**Comment by nevir** [comment]
Might want to point people to fs-based persistence due to [Android's dumb size limits](https://github.com/facebook/react-native/issues/12529) (2mb serialized per key)

**Comment by jamesreggio** [comment]
Instead of that, I'm going to set the `maxSize` default to 1 MB and call out the risks of going larger.

**Comment by nevir** [comment]
👍

**Comment by jamesreggio** [comment]
Added 1MB default `maxSize` and ample commentary here: https://github.com/apollographql/apollo-cache-persist/pull/11/files#diff-04c6e90faac2675aa89e2176d2eec7d8R194

Thanks @nevir!

**Pull request merged**
