### PR TITLE
cache: `readQuery` returns now the query result

### LINKED ISSUE #2308: InMemoryCache.readQuery returns the result directly
Here's the line that is responsible for that:
https://github.com/apollographql/apollo-client/blob/91f5116ce830151e6bedf92e10550c607984e11c/packages/apollo-cache-inmemory/src/readFromStore.ts#L52-L55

**Intended outcome:**
`InMemoryCache.readQuery()` should return `Cache.DiffResult`

**Actual outcome:**
It returns query's results directly instead of keeping it under `result` property.

**How to reproduce the issue:**
Check the code I provided in description above.

**Version**
- apollo-client@^2.0.0-rc.0

**This will be a breaking change**
In ApolloClient 1.0: `proxy.readQuery()` returns results directly
In ApolloClient 2.0: `proxy.readQuery()` returns results under `result` property (`Cache.DiffResult`)

```ts
apollo.mutate({
  /* ... */
  update(proxy, result) {
    const data = proxy.readQuery(/* ... */); <--- to .result, or not to .result that is the question
    
    proxy.writeQuery({
      /* ... */
      data: update(data, result.data),
    });
  }
})
```

### PR DESCRIPTION
**Pull request by kamilkisiela**
instead of `Cache.DiffResult`.

Fixes #2308

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Will fix those issues later today

**Comment by kamilkisiela** [comment]
Also, @jbaxleyiii if we'll change 
`readQuery<T>(): Cache.DiffResult<T>` to `readQuery<T>(): T`

shouldn't we also do something with `readFragment<T>(): Cache.DiffResult<T>` ?

**Comment by jbaxleyiii** [comment]
@kamilkisiela for sure! The direct reads should return the results, not a diffResult

**Comment by kamilkisiela** [comment]
I pushed my changes but somehow GitHub does not trigger any WebHooks for travis-cs, appveyor etc... Weird

**Comment by jbaxleyiii** [comment]
@kamilkisiela I rebased and adjusted this branch to just be the commits in your reference!

**Comment by jbaxleyiii** [comment]
Deploy preview ready!

Built with commit e9d43ac3c52bed050d3e5231a28540e799cfd195

https://deploy-preview-2320--apollo-client-docs.netlify.com

**Comment by jbaxleyiii** [comment]
@kamilkisiela I added a test on master to recreate `readQuery` not returning the result directly and it seems to be working as expected? https://github.com/apollographql/apollo-client/commit/0bbf08ebc6c0adb32605e55ee70884145d6cdd71#diff-59fb0f109da155cce309fd688f8482ba

**Comment by kamilkisiela** [comment]
@jbaxleyiii It's working for sure, the only problem is with mismatch between Type of readQuery's result and what it actually returns.

```ts
apollo.mutate({
  // ...
  update: (proxy, prev) => {
    const data = proxy.readQuery({/*...*/});

    proxy.writeQuery({
      /*... */,
      data: this.pushItem(data, result.data.createItem),  // <--- this will throw an issue 
      // Cache.DiffResult !== Query 
    });
  }
});

const pushItem = (prev: Query, item: Item): Query => {
  return {
      ...prev,
      allItems: [...prev.allItems, item]
    };
};
```

**Comment by kamilkisiela** [comment]
@jbaxleyiii done!

**Comment by jbaxleyiii** [comment]
YAY! Thank you!

**Pull request merged**
