### PR TITLE
chore: separate type imports in useSuspenseQuery.ts and useBackgroundQuery.ts

### PR DESCRIPTION
**Pull request by alessbell**
Hopefully closes https://github.com/apollographql/apollo-client/issues/11131 - opening a PR to test a snapshot release here.

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by diegohennrich** [comment]
I was facing the same issue:

- NodeJS 18.x
- Apollo 3.8.1

You must change the type also on the useReadQuery.ts file:

import type { QueryReference} from "../cache/QueryReference.js";

Could you do that and release a new one?

**Comment by alessbell** [comment]
Wanted to also get @phryneas's take on this (welcome back! 😅), but this seems worth merging.

**Comment by alessbell** [comment]
> You must change the type also on the useReadQuery.ts file

Thanks, @diegohennrich - updated and cutting a new snapshot release now.

**Comment by phryneas** [comment]
@alessbell totally in favor of the change - there might be tooling other than `tsc` out there that is lagging behind, so backwards compat with something like this is always good.

Could you also adjust the lint rule accordingly as part of the PR?

**Review by jerelmiller — APPROVED** [review]
Thanks for updating!

**Comment by alessbell** [comment]
@phryneas yep, also my thinking there thanks for confirming 👍 

> Could you also adjust the lint rule accordingly as part of the PR?

Added `import/consistent-type-specifier-style` rule for this in [0bad299](https://github.com/apollographql/apollo-client/pull/11134/commits/0bad2991f7e383ee9a8890590c9ed73314ebf8b1).

**Pull request merged**
