### PR TITLE
chore(sourcemaps): exclude sourcemaps in lib/dist

### PR DESCRIPTION
**Pull request by maapteh**
The client packages are not including their `src` in NPM, either Apollo team should include it or we exclude sourcemaps, i choose the last :) (can do first as well, just tell me what is preferred).

Also i made the change to what explicitly add to npm by adjusting the .npmignore's for each package  which now only pushes the lib and some markdowns and of course the package.json.

relates to issue #3699

### CODE REVIEW

**Comment by maapteh** [comment]
Lot of new tickets since then have been opened like #4462 it would be nice to know what to do. I like clean consoles without warnings :)

**Comment by shrugs** [comment]
would also close https://github.com/parcel-bundler/parcel/issues/2185

**Comment by cruhl** [comment]
This is still a major headache for me.

**Comment by hwillson** [comment]
Thanks for this @maapteh. We're re-visiting our entire bundling and build infrastructure for Apollo Client 3.0, and will be including sourcemaps, so I'll close this off. Thanks again!

**Comment by maclockard** [comment]
@hwillson source maps still point to non existent files as of @apollo/client 3.1.0

**Comment by hwillson** [comment]
Thanks for the heads up @maclockard!  Would you mind opening a new issue to track this?

**Comment by maclockard** [comment]
turns out there is already an issue here: #3699!

**Pull request closed without merging**
