### PR TITLE
Expose rewriteURIForGET at base module level

### PR DESCRIPTION
**Pull request by jimshepherd**
Expose rewriteURIForGET so deep linking is not required. Specifically to address update of apollo-upload-client to support Apollo Client v3.

Addresses issue:
#5958 

apollo-upload-client related PR:
https://github.com/jaydenseric/apollo-upload-client/pull/175

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by dohomi** [comment]
any news about this issue?

**Comment by benjamn** [comment]
We are still considering this change, but importing from `@apollo/client/link/http/rewriteURIForGET` is a fine workaround for now. I've moved this to the [Post 3.0 milestone](https://github.com/apollographql/apollo-client/milestone/17) for now, to help clear out the [Release 3.0 milestone](https://github.com/apollographql/apollo-client/milestone/14) in preparation for the release next Tuesday (July 14th).

**Comment by jaydenseric** [comment]
@benjamn are you aware that `@apollo/client/link/http/rewriteURIForGET` contains ESM? It is unusable.

**Comment by hwillson** [comment]
@jaydenseric that's a bug; we'll fix it. Thanks!

**Comment by benjamn** [comment]
Of course I’m aware of that, but how does that make it “unusable”? Any modern bundler can resolve and import that module. If you just mean browsers/unpkg can’t import it directly (without a bundler), that’s a more general problem with the web platform right now (hopefully to be solved by package import maps).

**Comment by jaydenseric** [comment]
Also, for native Node.js ESM compat the export should be a default export using `module.exports = theExport`, preferably without an annoying `.default` from transpilation.

The best way to publish dual ESM/CJS support whilst avoiding the [dual package hazard](https://nodejs.org/api/esm.html#esm_dual_package_hazard) is this:

https://nodejs.org/api/esm.html#esm_approach_1_use_an_es_module_wrapper

Use the `package.json` `exports` field with conditional exports, and document both named ESM exports from the main package entrypoint but also public deep imports. This is the pattern I am moving all my own packages to, e.g.

https://github.com/jaydenseric/graphql-upload/blob/a3b7b31406aa47567ced0b60eea1cd764db8932c/package.json#L32-L40

https://github.com/jaydenseric/graphql-upload#class-graphqlupload

Private code can't be accessed from outside the package, CJS and ESM consumers have a nice API, and Webpack v5+ can still get at the ESM and treeshake.

To support deep imports of ESM in browsers, you could additionally transpile sibling ESM `.mjs` versions of the individual CJS  `.js` files, although there are nuances to discuss about that.

**Comment by jaydenseric** [comment]
@benjamn I'm starting to feel a little frustrated about your lack of understanding of ESM in Node.js, and the needs of consumers both in relation to this and just how slow things move in Apollo repos even when there are issues and PRs doing most of the work for you.

**Comment by benjamn** [comment]
@jaydenseric I'm not going to take that kind of abuse from you. My previous comment was a good-faith question to find out where you were coming from. Based on your (nearly simultaneous) comment, it sounds like you're jumping through some hoops to accommodate the complexities of the current Node.js ESM situation, which is overcomplicated to say the least. I would encourage you to have a little faith in the long-term state of the ecosystem, and offer concrete advice where you think you can help. If you can't offer that advice without a tinge of personal insult, please don't bother helping. Thanks!

**Comment by jaydenseric** [comment]
@benjamn 

> My previous comment was a good-faith question to find out where you were coming from.

I initially wrote https://github.com/apollographql/apollo-client/pull/6109#issuecomment-657927798 before [your comment](https://github.com/apollographql/apollo-client/pull/6109#issuecomment-657927503), at great effort, to be friendly and helpful. This is despite feeling very reasonable frustration that this PR has been ignored for nearly 3 months, only to be dismissed as unimportant without truly understanding the context that we went to trouble to document.

I took it in good faith that it was unintentionally slipping through the cracks, but then when you commented "Of course I’m aware of that, but how does that make it “unusable”?" I interpreted that as an emotional, defensive response instead of a good faith question. If I was mistaken, I apologize.

> I'm starting to feel a little frustrated

It's not what anyone wants to hear, but it's the truth and expressing feelings or giving feedback should not always be perceived as a personal attack.

> about your lack of understanding of ESM in Node.js, and the needs of consumers

An empirical observation about something negatively impacting the community. It's a one line change that would enable a feature the community of a > 1k star project has been waiting for patiently for some time.

> how slow things move in Apollo repos

Again, an observation. Someone went to the trouble to raise this PR months ago.

> even when there are issues and PRs doing most of the work for you

This is to caveat that I don't expect team Apollo to rush out and do a bunch of free work for us on demand; we are figuring out and solving real problems ourselves to the benefit of the whole community and Apollo, a for-profit business. I don't even need the feature myself for anything that brings income - my involvement is altruistic.

My tone would be less frustrated if this was a one off inefficiency. But there are been numerous critical PRs (some with security implications) that have been delayed for months or even years.

> it sounds like you're jumping through some hoops to accommodate the complexities of the current Node.js ESM situation, which is overcomplicated to say the least.

Following the official, stable Node.js API (that had been publicly in the works for years) for ESM is not "jumping through hoops". It's literally our job that we get paid for to understand how Node.js, bundlers and browsers work. Tens of thousands of developers and millions of users rely on us having a basic understanding. It's also polite to have a basic understanding before saying things like "Of course I’m aware of that, but how does that make it “unusable”?" to an expert.

> offer concrete advice where you think you can help. If you can't offer that advice without a tinge of personal insult, please don't bother helping.

I've been helping Apollo for years in very meaningful ways, without insult.

> I'm not going to take that kind of abuse from you.

It's not healthy to always perceive constructive feedback as "abuse". This language is a big escalation in tone that frankly makes me feel uncomfortable.

Let's both press reset on this interaction? No hard feelings.

**Comment by jaydenseric** [comment]
BTW, here is a more direct explanation of why the deep import of ESM is not a viable workaround:

```js
const { createUploadLink } = require('apollo-upload-client');
```

Node.js would crash trying to resolve that module if it internally required a deep path containing ESM.

**Pull request closed without merging**
