### PR TITLE
AC3: Remove nested fragments with client directive

### LINKED ISSUE #5192: Nested fragment spreads with `@client` directive is not removed from query
**Intended outcome:**

Nested fragment spreads with `@client` directive which is not used in query is removed from query.

**Actual outcome:**

Fragment spreads with `@client` directive remains on query.
This violates GraphQL Spec.
https://graphql.github.io/graphql-spec/June2018/#sec-Fragments-Must-Be-Used
> Defined fragments must be used within a document.

As an actual problem, GraphQL server returns 422 error because of this.

**How to reproduce the issue:**

I think this problem is caused by `removeDirectivesFromDocument` function in `apollo-utilities`. Add below test case to `packages/apollo-utilities/src/__tests__/transform.ts` and it fails.
``` js
  it('should remove nested fragment spreads and definitions associated with the removed directive', () => {
    const query = gql`
      query Simple {
        networkField
        field @client {
          ...ClientFragment
        }
      }

      fragment ClientFragment on Thing {
        ...NestedFragment
      }

      fragment NestedFragment on Thing {
        otherField
        bar
      }
    `;

    const expected = gql`
      query Simple {
        networkField
      }
    `;

    const doc = removeDirectivesFromDocument(
      [{ name: 'client', remove: true }],
      query,
    );
    expect(print(doc)).toBe(print(expected));
  });
```

test result
```sh
Summary of all failing tests
 FAIL  packages/apollo-utilities/src/__tests__/transform.ts
  ● removeDirectivesFromDocument › should remove nested fragment spreads and definitions associated with the removed directive

    expect(received).toBe(expected) // Object.is equality

    - Expected
    + Received

      query Simple {
        networkField
      }

    + fragment NestedFragment on Thing {
    +   otherField
    +   bar
    + }
    +

      222 |       query,
      223 |     );
    > 224 |     expect(print(doc)).toBe(print(expected));
          |                        ^
      225 |   });
      226 |
      227 |   it('should not remove fragment spreads and definitions used without the removed directive', () => {

      at Object.<anonymous> (src/__tests__/transform.ts:224:24)
```
**Versions**

  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 63.0.1
    Safari: 12.1.2
  npmPackages:
    apollo-boost: file:packages/apollo-boost => 0.4.4
    apollo-cache: file:packages/apollo-cache => 1.3.2
    apollo-cache-inmemory: file:packages/apollo-cache-inmemory => 1.6.3
    apollo-client: file:packages/apollo-client => 2.6.4
    apollo-utilities: file:packages/apollo-utilities => 1.3.2

### PR DESCRIPTION
**Pull request by giautm**
### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

This is updated PR for https://github.com/apollographql/apollo-client/pull/5201, close #5192

### CODE REVIEW

**Comment by giautm** [comment]
Don't know why TS report this error. 🤔 
```
  ● Test suite failed to run

    src/utilities/graphql/__tests__/transform.ts:258:18 - error TS2345: Argument of type 'DocumentNode | null' is not assignable to parameter of type 'ASTNode'.
      Type 'null' is not assignable to type 'ASTNode'.

    258     expect(print(doc)).toBe(print(expected));
                         ~~~
    src/utilities/graphql/__tests__/transform.ts:296:18 - error TS2345: Argument of type 'DocumentNode | null' is not assignable to parameter of type 'ASTNode'.
      Type 'null' is not assignable to type 'ASTNode'.

    296     expect(print(doc)).toBe(print(expected));
```

**Comment by giautm** [comment]
Hi @hwillson, I hope this PR will release in 3.2.0. Can you review it?

**Comment by giautm** [comment]
What's wrong with `bundlesize`? 🤔

**Comment by giautm** [comment]
Hi @hwillson, can you review this PR?

**Comment by giautm** [comment]
hi @benjamn, can you review this PR?

**Comment by giautm** [comment]
Hi @hwillson, base on this [comment](https://github.com/apollographql/apollo-client/pull/5201#issuecomment-896213561). Can you review this PR please?

**Comment by alessbell** [comment]
Closing in favor of https://github.com/apollographql/apollo-client/pull/10560.

**Pull request closed without merging**
