### PR TITLE
fix(types): use correct type for headers

### PR DESCRIPTION
**Pull request by alias-mac**
When passing the headers property to `createHttpLink` one might think that it is ok to pass them as `Headers` interface, but that doesn't work because there is several places in the code that expect headers to be passed as an object.

Basically the main problem is using code like:
```ts
const apolloLink = createHttpLink({
  uri: 'some-url',
  headers: new Headers({foo: 'bar'}),
});
```
Keep in mind that the code above is simplified and the idea is that headers passed in are of type `Headers`.

TypeScript won't complain because Apollo accepts `any` in this type, but that isn't quite true (based on the code).
I believe that the type here should be stricter to what Apollo is actually expecting to be passed in, and perhaps revisit this later to support [`Headers` interface](https://developer.mozilla.org/en-US/docs/Web/API/Headers).

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by alias-mac** [comment]
Sorry for the ping @benjamn, @brainkim, @jcreighton and @hwillson, but if I rebase this, can it be merged? Thanks!

**Comment by alias-mac** [comment]
Any chance to get this reviewed and merged? Let me know what changes you don't agree with. Thanks!
 @benjamn, @brainkim, @jcreighton and @hwillson

**Review by jerelmiller — APPROVED** [review]
This looks like a positive change to me and I see no reason not to include this. Thanks for your patience @alias-mac!

**Comment by jerelmiller** [comment]
@alias-mac I just merged in `main` and looks like there is now some code that fails type checking that wasn't here the last time you updated this PR. Would you be willing to take a look at this and get this updated? I'd be happy to get this merged in once tests are passing.

**Comment by alessbell** [comment]
Hi @alias-mac 👋 I went to add a changeset here so we can get this merged in and made a mess of the git history as you can see :) I'm going to close this one out and open a new PR that includes your commit, thanks!

**Pull request closed without merging**
