### PR TITLE
fix: remove error thrown by inFlightLinkObservables

### PR DESCRIPTION
**Pull request by alessbell**
~Closes https://github.com/apollographql/apollo-client/issues/11543.~

Edit: unrelated to the above issue but still cleanup nonetheless :)

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
@alessbell thank you for looking into this. I removed these lines and the error persisted. Let me give it one more shot though.

**Comment by efstathiosntonas** [comment]
@alessbell tried it again, removed the lines from `core.cjs`, restarted metro server with --reset-cache but the issue persists.

**Comment by alessbell** [comment]
@efstathiosntonas thanks for opening the issue, that's helpful info. If you have a reproduction you can share (the empty react-native project where you transferred over your client setup, if you're able to share it), that would also help a lot, otherwise I can spin one up. Thanks!

**Comment by efstathiosntonas** [comment]
@alessbell here's a demo repo, please note that i cannot reproduce it: https://github.com/efstathiosntonas/bare-react-native-expo-svg-transformer-issue (don't mind about the repo name)

**Review by jerelmiller — APPROVED** [review]

**Pull request merged**
