### PR TITLE
Release 3.0

### PR DESCRIPTION
**Pull request by benjamn**
This PR tracks changes that are slated to be released in the next major version of Apollo Client, based on the [Apollo Client 3.0 roadmap](https://github.com/apollographql/apollo-feature-requests/issues/33).

PRs that introduce major or minor breaking changes should be merged into the `release-3.0` branch instead of `master`, so that we can keep releasing patch updates in the meantime. That doesn't mean everything here is a breaking change by any means—just that this branch is more experimental/unstable than `master`.

If there are minor breaking changes that we want to release before 3.0, we might also create a `release-2.7` branch and pull request, similar to [Release 2.5](https://github.com/apollographql/apollo-client/pull/4361) and [Release 2.6](https://github.com/apollographql/apollo-client/pull/4586).

Changes so far:
- [x] Merge React Apollo hooks (`@apollo/react-hooks`) into Apollo Client: https://github.com/apollographql/apollo-client/pull/5357
- [x] The `FragmentMatcher` abstraction has been replaced with a `possibleTypes` option for the `InMemoryCache` constructor: https://github.com/apollographql/apollo-client/pull/5073
  - [x] Fully eliminate the concept of heuristic fragment matching: https://github.com/apollographql/apollo-client/pull/5684
- [x] Eliminate "generated" cache IDs to avoid normalizing objects without meaningful IDs: https://github.com/apollographql/apollo-client/pull/5146
- [x] Remove `freezeResults` option, assuming always true: https://github.com/apollographql/apollo-client/pull/5153
- [x] Implement `InMemoryCache` garbage collection and eviction: https://github.com/apollographql/apollo-client/pull/5310
- [ ] ~Stop returning unwanted `__typename` fields in cache results: https://github.com/apollographql/apollo-client/pull/5311~
- [x] Stop calling `addTypenameToDocument` before `InMemoryCache` reads/writes: https://github.com/apollographql/apollo-client/pull/5320
- [x] Update `optimism` to use lighter-weight dependency API in `EntityCache`: https://github.com/apollographql/apollo-client/pull/5325
- Removal of deprecated methods (ongoing):
  - [x] `ApolloClient#initQueryManager`
  - [x] `QueryManager#startQuery`
  - [x] `ObservableQuery#currentResult`
- [x] Merge Apollo Link common + HTTP functionality into core: https://github.com/apollographql/apollo-client/pull/5412
- [x] Reenable Rollup `preserveModules` option, and consolidate `utils`/`utilities` directories: https://github.com/apollographql/apollo-client/pull/5437
- [x] Enable customization of cache normalization behavior: https://github.com/apollographql/apollo-client/pull/5443
- [x] Example Apollo Client applications in `examples/bundling`, with analysis tools: https://github.com/apollographql/apollo-client/pull/5449
- [x] Provide `toReference` helper function in `FieldFunctionOptions`: https://github.com/apollographql/apollo-client/pull/5506
- [x] Avoid reading from cache in `ObservableQuery#getCurrentResult`: https://github.com/apollographql/apollo-client/pull/5565
- [x] Never merge fields in cache unless objects have same identity: https://github.com/apollographql/apollo-client/pull/5603
- [x] Finer-grained `InMemoryCache` result caching: https://github.com/apollographql/apollo-client/pull/5617
- [x] Support `cache.identify(entity)` for computing entity ID strings: https://github.com/apollographql/apollo-client/pull/5642
- [x] Support eviction of specific entity fields: https://github.com/apollographql/apollo-client/pull/5643
- [x] Stop paying attention to `previousResult` in `InMemoryCache`: https://github.com/apollographql/apollo-client/pull/5644
- [x] Improve optimistic update performance by limiting cache key diversity: https://github.com/apollographql/apollo-client/pull/5648
- [x] Allow `getFieldValue` to read from foreign `Reference` objects: https://github.com/apollographql/apollo-client/pull/5651
- [x] Storage and invalidation for custom field `read` functions: https://github.com/apollographql/apollo-client/pull/5667
- [x] Refactor custom field `merge` function processing: https://github.com/apollographql/apollo-client/pull/5712
- [x] Unify `FieldFunctionOptions` between `read` and `merge` functions: https://github.com/apollographql/apollo-client/pull/5722
- [ ] Move query transformations and printing to the `gql` tag instead of internally in Apollo Client + apollo-link-http. Change link API to recieve `string` instead of `DocumentNode`
- [ ] Improve preformance for SSR initilization and direct read (boot from SSR)
- [ ] Support keeping errors in the cache

### CODE REVIEW

**Comment by benjamn** [comment]
@hwillson Ok, I've merged my own PRs that were approved and seemed ready (everything except #5154), so you should be good to start merging other folks' PRs into `master` and then merge `master` into `release-3.0` ahead of your restructuring work.

**Comment by hwillson** [comment]
Netlify is failing after merging in `master` because of the updated docs theme's built in link checking capabilities. 

<details><summary>Broken links</summary>
<p>

```
12:33:26 PM: 3 broken links found on /docs/react/recipes/recompose/
12:33:26 PM: - /docs/react/api/react-apollo/#optionsnotifyonnetworkstatuschange
12:33:26 PM: - /docs/react/api/react-apollo/#datanetworkstatus
12:33:26 PM: - /docs/react/api/react-apollo/#configprops
12:33:26 PM: 1 broken links found on /docs/react/v2.6/advanced/fragments/
12:33:26 PM: - /docs/react/advanced/boost-migration/
12:33:26 PM: 1 broken links found on /docs/react/v2.6/advanced/subscriptions/
12:33:26 PM: - /docs/react/advanced/boost-migration/
12:33:26 PM: 1 broken links found on /docs/react/v2.6/advanced/update-store/
12:33:26 PM: - /docs/react/v2.6/advanced/LINK PLZ/
12:33:26 PM: 1 broken links found on /docs/react/v2.6/essentials/get-started/
12:33:26 PM: - /docs/react/advanced/boost-migration/
12:33:26 PM: 1 broken links found on /docs/react/v2.6/recipes/authentication/
12:33:26 PM: - /docs/react/essentials/get-started/#configuration-options
12:33:26 PM: 3 broken links found on /docs/react/v2.6/recipes/recompose/
12:33:26 PM: - /docs/react/api/react-apollo/#optionsnotifyonnetworkstatuschange
12:33:26 PM: - /docs/react/api/react-apollo/#datanetworkstatus
12:33:26 PM: - /docs/react/api/react-apollo/#configprops
12:33:26 PM: 1 broken links found on /docs/react/v2.5/advanced/caching/
12:33:26 PM: - /docs/react/api/react-apollo/#mutation
12:33:26 PM: 1 broken links found on /docs/react/v2.5/advanced/fragments/
12:33:26 PM: - /docs/react/advanced/boost-migration/
12:33:26 PM: 1 broken links found on /docs/react/v2.5/advanced/subscriptions/
12:33:26 PM: - /docs/react/advanced/boost-migration/
12:33:26 PM: 1 broken links found on /docs/react/v2.5/advanced/update-store/
12:33:26 PM: - /docs/react/api/react-apollo/#optionsupdate
12:33:26 PM: 1 broken links found on /docs/react/v2.5/essentials/get-started/
12:33:26 PM: - /docs/react/advanced/boost-migration/
12:33:26 PM: 1 broken links found on /docs/react/v2.5/essentials/mutations/
12:33:26 PM: - /docs/react/api/react-apollo/
12:33:26 PM: 2 broken links found on /docs/react/v2.5/essentials/queries/
12:33:26 PM: - /docs/react/api/react-apollo/#datanetworkstatus
12:33:26 PM: - /docs/react/api/react-apollo/
12:33:26 PM: 1 broken links found on /docs/react/v2.5/recipes/authentication/
12:33:26 PM: - /docs/react/essentials/get-started/#configuration-options
12:33:26 PM: 3 broken links found on /docs/react/v2.5/recipes/recompose/
12:33:26 PM: - /docs/react/api/react-apollo/#optionsnotifyonnetworkstatuschange
12:33:26 PM: - /docs/react/api/react-apollo/#datanetworkstatus
12:33:26 PM: - /docs/react/api/react-apollo/#configprops
12:33:26 PM: error
12:33:26 PM: The GraphQL query from /opt/build/repo/docs/node_modules/gatsby-theme-apollo-docs/src/components/template.js failed.
12:33:26 PM: Errors:
12:33:26 PM:   23 broken links found
```

</p>
</details>

I'll get this fixed tomorrow.

**Comment by dylanwulf** [comment]
Hello! I hope you don't mind, I have a quick question. I noticed you have "Move query transformations and printing to the gql tag" in the list of changes. In my project, I have a custom Link which transforms some of my queries. Will this still be possible in v3?

**Comment by benjamn** [comment]
@dylanwulf Short answer: yes!

Longer answer: exporting the `gql` tag from `@apollo/client` is the first step towards the goal of controlling both parsing and printing, so that we can eventually eliminate the runtime dependencies on `graphql/language/parser` and `graphql/language/printer`. We are also contemplating a breaking change of passing a query _string_ into the link chain, rather than a parsed `DocumentNode`, since any public use of `DocumentNode` prolongs our commitment to that AST format. Besides opening up AST options other than `DocumentNode`, another benefit of passing a string from link to link is that the final link the chain no longer needs to reprint the query in order to send it to the server, because it's already a string. That would be awesome, because it would eliminate the last place in most default Apollo Client setups where `graphql/language/printer` is required. Of course, any links that still need to transform the query can do so; they just have to parse the query string, transform it, reprint it, and pass the transformed query string to the next link in the chain. These link implementations would need to depend on some sort of parser and printer, but they would have the freedom to choose between `graphql/language/{parser,printer}` and anything else that works for their needs.

What do you think about that?

**Comment by dylanwulf** [comment]
@benjamn Sounds good! Thanks for the explanation!

**Comment by benjamn** [comment]
@fbartho Versioning the AST format with metadata sounds like a significant increase in configuration complexity, and it means we would have to keep supporting (or at least thinking about) all the different versions, which arguably takes us further from the goal of independence from any particular AST format. I'm still convinced that the best/only way to achieve that goal is to expose query strings rather than AST structures.

If you are concerned with hypothetical parsing and printing performance problems, I would recommend that you consolidate your multiple links into one link, or explore a parsing utility that can cache previous ASTs. Those choices will be entirely up to you, once we make this change.

**Comment by fbartho** [comment]
To be clear @benjamn, this isn't hypothetical with apollo-link-rest. Today we have to parse / manipulate the AST (as far as I know), because our query nodes have to be sliced out of the content being passed along to HTTPLink.

In my particular application we might have a sandwich:

```graphql
query Example {
   currentUser @rest(…) {
     id
     name
   }
   localState @client {
     …someFields
   }
}

# And localState runs a series of REST API Calls 
query Internal1 {
  someDataFromRest @rest(...) {
    …fields
  }
}
# Run some business logic
query Internal2 {
  lastDataFromRest @rest(…) {
    ...fields
}
```

With the current state of the world, the parsing of the AST should happen once at load time per query (right?).

With the discussed state of the world, we're going to have to parse and slice, and print, and parse and slice and print repeatedly, right? -- I could easily have misunderstood your proposal, so please let me know!

**Comment by abdonrd** [comment]
@benjamn @hwillson Thanks for all the work! I look forward to v3! 👏

Is there an estimated date of when the release will be?

**Comment by benjamn** [comment]
Even though AC3 is still in beta, we're hoping to publish the first release candidate soon. In the meantime, we felt increasingly uncomfortable leaving `master` pointing to AC2 code, since the old repository structure was a gigantic pain to build, test, and publish—which discouraged contributions and made it harder for us to merge PRs targeting `master` into `release-3.0`, where all of our attention is focused these days. Thanks again to @hwillson for the monumental restructuring work he did in https://github.com/apollographql/apollo-client/pull/5292 and related PRs.

**Comment by mhaylock** [comment]
@benjamn this appears to have lead to https://www.apollographql.com/docs/ now containing the v3 docs with no version dropdown to view other versions like it used to have.

Is there a way to still access the 2.x documentation?

**Comment by dmitry** [comment]
Is there are any plans on publishing the migration guide with the most important changes were done since the latest version of previous major release v2.x?

**Pull request merged**
