### PR TITLE
Working up towards 2.0 release

### PR DESCRIPTION
**Pull request by jbaxleyiii**
This PR stands to track the [2.0 milestone](https://github.com/apollographql/apollo-client/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0) and when its merged, the 2.0 will be near ready to become the official `latest`. Comment here if you have anything that is not working with the 2.0!

You can try it out by following the [upgrade guide](https://github.com/apollographql/apollo-client/blob/2.0/Upgrade.md) and installing `apollo-client@next` and `apollo-cache-inmemory@next`

*Note* going to merge this and tack the last few issues into smaller PR's so the docs can be part of master

### CODE REVIEW

**Comment by langpavel** [comment]
Hello there.

In previous version I have a [client instance on server with custom network interface like this](https://github.com/kriasoft/react-starter-kit/blob/feature/apollo/src/core/createApolloClient/createApolloClient.server.js).

The point of doing this is that isomorphic application should not waste with server resources (extra HTTP loop can be expensive) and can evaluate graphql in single server request lifecycle directly.

Can anybody give me a hint, pointing me to relevant documentation or source code where I can inspire?

Thanks!
*I'm maintainer of [`feature-apollo` branch](https://github.com/kriasoft/react-starter-kit/tree/feature/apollo) in still [`react-starter-kit`](https://github.com/kriasoft/react-starter-kit)*

**Comment by jbaxleyiii** [comment]
@langpavel it would look something like this!

```js
import { ApolloLink, Observable } from 'apollo-link';
import { graphql } from 'graphql';

const link = new ApolloLink(operation =>
  new Observable(observer => {
    const { query, variables, operationName } = operation;
    graphql(schema, print(query), {}, {}, variables, operationName)
      .then(result => {
        observer.next(result);
        observer.complete(result);
      })
      .catch(e => observer.error(e));
  }));
```

**Comment by langpavel** [comment]
@jbaxleyiii Wow It needs heavy mind shift! I know, there are some blog posts, do you remember some relevant one?
I think migration guide will be needed in cases where API changed...

**Comment by langpavel** [comment]
I have another question related to abandoned redux.
In previous version I used actions to count up/down queries in fly and show state using `react-redux-loading-bar`.
Will be there an example how to bind queries in fly to redux, for example? :-)

**Comment by jbaxleyiii** [comment]
@langpavel there is a starting point for the upgrade [here](https://github.com/apollographql/apollo-client/blob/26e0141794205946d8ccf4b158bab07867aa0c87/Upgrade.md) and we will flesh this more out with official docs once the 2.0 is ready (should be this week / early next week).

> n previous version I used actions to count up/down queries in fly and show state using react-redux-loading-bar.
Can you not just use the loading state on the query itself to do that?

**Comment by stubailo** [comment]
> Can you not just use the loading state on the query itself to do that?

I think he means for all queries.

Thankfully this can also be very easily done with Apollo Link! We'll post some code snippets here soon :]

**Comment by huangbong** [comment]
I'm trying to test out `apollo-client@2.0.0-rc.1` but when I do

`import ApolloClient, { createBatchingNetworkInterface } from 'apollo-client';`

I'm getting

`TypeError: (0 , _reactApollo.createBatchingNetworkInterface) is not a function`

Also, any way you can update `react-apollo@2.0.0-beta.0` to have the latest `apollo-client` RC release? So I don't have to install `apollo-client@2.0.0-rc.1` separately. :)

**Comment by davidblurton** [comment]
The Apollo client dev tools don't work for me with v2. We're using rc.2, although they haven't worked for any version so far. The dev tools inspector show the following error 

```
"TypeError: Cannot read property 'query' of undefined
    at ApolloClient.window.__APOLLO_CLIENT__.makeGraphiqlQuery (<anonymous>:12:60)
    at <anonymous>:4:41
    at <anonymous>:11:7"
```
I opened an issue on the dev tools repo but I haven't had a response. 
https://github.com/apollographql/apollo-client-devtools/issues/78

We found the dev tools really useful when we were using the v1 client, so I hope this is something that will work for v2 as well.

**Comment by jbaxleyiii** [comment]
@davidblurton 👋 yep that is fixed here! https://github.com/apollographql/apollo-client-devtools/pull/79 We are working to get it released!

**Comment by huangbong** [comment]
Did setting cache with

```
new ApolloClient({
  cache: new InMemoryCache()
})
```
change in API? I'm running `apollo.cache.extract()`, and it says can't read extract of undefined.

**Comment by jbaxleyiii** [comment]
Deploy preview ready!

Built with commit 816a61df19d6e0da0133d27cdfe5c97907570aa5

https://deploy-preview-2281--apollo-client-docs.netlify.com

**Pull request merged**
