### PR TITLE
Remove "[GraphQL|Network] error" from error messages

### PR DESCRIPTION
**Pull request by lorensr**
Implements FR: https://github.com/apollographql/apollo-feature-requests/issues/46

For consistency, strips the prefix from both GraphQL and Network errors. See "Stripping prefix" in https://github.com/apollographql/apollo-client/issues/1812#issuecomment-416011965

### CODE REVIEW

**Comment by lorensr** [comment]
Oops, thanks—the commit hook got me! It's working for me after adding `--no-config`, if that's okay?

**Comment by benjamn** [comment]
@lorensr @hwillson Honestly I think we should remove the auto-`git add` prettier behavior [here](https://github.com/apollographql/apollo-client/blob/3f336d296b687616af822b462bc226c9e872cfb3/package.json#L75). It totally undermines the expectation that `git` should only commit code that you `git add`ed.

**Comment by hwillson** [comment]
@benjamn Totally agree - this has thrown me off multiple times. Noted and I'll take care of it shortly (unless you beat me to it). Thanks!

**Comment by hwillson** [comment]
Just re-visiting this a bit @benjamn; if we drop the `git add`, then we're no longer enforcing staged file prettier cleanup. We're currently doing this on all of our main repos, so this might be a larger discussion. For now though I think @lorensr's suggestion of making sure the pre-commit `prettier` hook doesn't use a local config if one exists (since we don't want it to), makes sense.

**Comment by abernix** [comment]
Just as a flag, Node.js usually flags changes to error `message` properties as breaking changes which must be included in semver-major releases.  I don't know if we need to subscribe to that, but it's worth mentioning.

**Comment by hwillson** [comment]
That's a really great point @abernix. People could be relying on the error `message` prefix to drive application logic. I think it makes sense to follow Node's lead here, so I'll add this to the `Release 3.0` milestone. Thanks!

**Comment by ScreamZ** [comment]
Will this will be merged soon?

**Comment by mattdavenport** [comment]
Any updates here? This would be really valuable in displaying errors much more efficiently. Thanks!

**Comment by ScreamZ** [comment]
@benjamn @hwillson

**Comment by austinChappell** [comment]
Any updates on this?

**Pull request merged**
