### PR TITLE
Setup all-contributors-cli

### PR DESCRIPTION
**Pull request by b-barry**
### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by stubailo** [comment]
How do we add the contributor list to the README?

**Comment by b-barry** [comment]
If you we run 'generate' command, it will append it at the end.
Do you prefer an other file ?

**Comment by jbaxleyiii** [comment]
@b-barry either the readme or a redo of the current authors file could work!

**Comment by b-barry** [comment]
@jbaxleyiii Do I  gather all the code contributors and run the "generate" command on the Readme?
It is not part of the PR. I have just setup the all-contributors-cli

**Comment by peggyrayzis** [comment]
Hey @b-barry! I set up `all-contributors-cli` in one of my projects, so I can answer your questions about the workflow.

Did you run `all-contributors init`? That command will add a template to the README and walk you through a series of prompts (like size of avatars, etc).

Here's [how to add contributors](https://github.com/jfmengels/all-contributors-cli#addupdate-contributors) to the README. This process is very manual though 😭 

An alternative is adding contributors to the [] in `.all-contributorsrc`. The template for a contributor looks like this:
```
    {
      "login": "peggyrayzis",
      "name": "Peggy Rayzis",
      "avatar_url": "https://avatars1.githubusercontent.com/u/18017067?v=4",
      "profile": "https://twitter.com/peggyrayzis",
      "contributions": [
        "code",
        "doc",
        "review"
      ]
    }
```
We could probably query the Github GraphQL API for our contributors & their info. What do you think?

**Comment by stubailo** [comment]
> We could probably query the Github GraphQL API for our contributors & their info. What do you think?

I think that would be a great idea!

**Comment by jbaxleyiii** [comment]
> I think that would be a great idea!

If only we had a graphql client....

**Comment by b-barry** [comment]
Hey @peggyrayzis, I ran it but didn't commit the README file because I don't know if the README will be the right file.
Querying the Github API will help to gather all code contributors and create a script that we could run before every push for example

**Comment by jbaxleyiii** [comment]
@b-barry I think we can take what you have done here and work on running it for contributors! We may even be able to setup some level of commit hook to do it automatically? I think we merge this in for now and can run it manually for the time being as part of the release process

**Comment by b-barry** [comment]
@jbaxleyiii Thanks for the merging.
Do I perform the same PR for all others repo ?

**Pull request merged**
