### PR TITLE
reset last results on new observer subscribe

### PR DESCRIPTION
**Pull request by roycclu**
### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@roycclu what is the goal with this?

**Comment by roycclu** [comment]
@jbaxleyiii  solving issue #2774 #2513 
It seems without resetting the query for results from network. Queries are getting stale results through the queryRecycler mechanism.

**Comment by viggyfresh** [comment]
Could be totally mistaken, but I believe this addresses https://github.com/apollographql/react-apollo/issues/1385 as well! Any reason why this hasn't gone in yet? Thanks everyone!

**Comment by nfantone** [comment]
@jbaxleyiii There are a _ton_ of issues about this both at this repo and `react-apollo`'s. 

https://github.com/apollographql/apollo-client/issues/2513
https://github.com/apollographql/react-apollo/issues/1389
https://github.com/apollographql/apollo-client/issues/2774
https://github.com/apollographql/react-apollo/issues/1229
https://github.com/apollographql/react-apollo/issues/1466
https://github.com/apollographql/apollo-client/issues/2669
https://github.com/apollographql/apollo-client/issues/2687

And people coming up with [quick fixes](https://github.com/apollographql/react-apollo/pull/1531) and [alternative packages](https://github.com/apollographql/apollo-client/issues/2513#issuecomment-349055304).

I'm respectfully surprised at your question.

**Comment by jbaxleyiii** [comment]
@nfantone all of those issues should be fixed with the new react apollo. The QueryRecycler was a nightmare that made a ton of issues like this a problem. 

As for in Apollo Client, the question to me is should we resetResults when new subscribers add on. I don't think so. A simple case shows where this is a problem:
```
const obs = client.watchQuery({ query ));
obs.subscribe((data) => {
  // when we have data, create a new subscription (its like mounting a sub component)
  client.watchQuery({ query }).subscribe((result) => {
    // why would this reset the last results since its just a cache read
  });
});
```

What I would love to see here for a core change is a failing test showing the behavoir that isn't working currently or a reproduction with the latest updates showing this is still a problem.

**Comment by hwillson** [comment]
Thanks for contributing this PR @roycclu! As mentioned in https://github.com/apollographql/apollo-client/pull/2871#issuecomment-375719794, a lot (maybe all) of the issues listed in this thread should now be fixed, with recent versions of `apollo-client` and `react-apollo`. As also mentioned in that comment, there are scenarios where the changes you've submitted in this PR will likely cause problems. If you're able to put together some failing tests or a reproduction that shows this problem, and how your PR helps address it (without impacting the rest of the codebase), then that would help move this PR along. For now though since there hasn't been any traction here in a while, I'll close this off. Thanks again for your work on this!

**Comment by sjnonweb** [comment]
@hwillson  Is this released on NPM, because i'm still facing this issue, These are the latest packages i'm using:

- `react-apollo: 2.1.9`
- `apollo-client: 2.3.7`

**Comment by gandhiamarnadh** [comment]
@sjnonweb these versions fixed for me, just a note make sure you have apollo-client 2.3.7 in node modules

**Comment by gandhiamarnadh** [comment]
@hwillson I also dont see this code on master can you please confirm on which version is this deployed on

**Pull request closed without merging**
