### PR TITLE
Websocket support (WIP)

### PR DESCRIPTION
**Pull request by DxCx**
Notes:
 1. **This PR adds support for websocket transport, pending support on server: apollographql/graphql-server#308**
2. It's not ready yet, but i've opened the PR so you can start review and see changes.
3. This implementation uses browser native WebSocket client, therefore no extra dependancies are needed (Only websocket polyfill for node for testing)
4. because we eventually want to create a repo for all network interfaces, i think it can just be apart of apollo client until then..
5. query is just a wrap of _query which supports Observable response. so when Observable query will be supported, that's a quick fix.
6. (@helfer) as we discussed, middlewares are not supported atm, as websocket doesn't initiate a new request for each packet. let's think how and if we want to support them.

TODO:

- [ ] Make Online instance of SWAPI GraphQL-WebSocket.
    - [ ] Pending Merge and release of `graphql-server-ws` - apollographql/graphql-server#308
- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Need to add documentation - @helfer which needs update?
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Update CHANGELOG.md with your change
- [x] General Polish + Unit testing
- [x] Add HTTP+WS Hybrid mode.
- [x] Analyze Binary size and reduce it:
   - [x] BUG: websocket library is being bundled
   - [x] url lib is too big, better to split string manually then pay for the size.
- [x] Pass options as 'init' message.
- [x] Add your name and email to the AUTHORS file (optional)
- [x] Implement subscriptions.
- [X] Make sure all of the significant new logic is covered by tests
- [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
Thanks for the PR @DxCx ! As discussed in person, let's break this into a separate package and a small PR that just adds observable support to the current Network interface API, and makes sure the API is aligned with the fetcher used in graphiql. Basically, the PR to Apollo Client should only make the following changes:

1. Make sure all places where Apollo Client calls the Network Interface can accept either a promise or an observable as a return value.
2. Make sure all places where Apollo calls the network interface can deal with two kinds of network interface: 1) the old one, which has a `query` method on it that is used for queries and mutations, and 2) the new one, which has only an `execute` function that takes arguments in the same shape as the GraphiQL fetcher ( https://github.com/graphql/graphiql ).

For the rest of this PR, one part of it should go into the subscriptions transport, which we'll rename to `graphql-transport-ws` once it supports all operations ( if @Urigo is okay with that).

The other part should go into a separate WS network interface package, which has the new `execute` function on it and always returns an observable.

I'm really excited about these changes, and I think we can put together a really cool demo once we have all the pieces in place! 😀

**Comment by smolinari** [comment]
Has the `graphql-transport-ws` change been moving forward somewhere else as suggested? I'd like to keep track of any updates. I too am excited for these changes. 👍 

Thanks. 

Scott

**Comment by DxCx** [comment]
We are working on that :)

**Comment by smolinari** [comment]
Super news! Thanks for the update. Any rough ETA? No worries, I won't hold you to it. I just need a rough idea of the timeline. 

Scott

**Comment by DxCx** [comment]
actually i didn't have much time to do the PR myself,
but thanks to @mistic client side is pretty much ready, we are working on server.
and then we will need to refine the testing abit.
i believe in the next week we will open a PR in `graphql-transport-ws`

**Pull request closed without merging**
