### PR TITLE
Support extensions in useSubscription

### PR DESCRIPTION
**Pull request by jcostello-atlassian**
This adds optional support for extensions in useSubscription following the graphql-ws spec:

https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

### CODE REVIEW

**Comment by phryneas** [comment]
Thank you for the PR!

I'm gonna be honest, the two of us have the worst timing: I'm in the middle of rewriting that hook right now (you can see the current progress over here: https://github.com/apollographql/apollo-client/pull/11511/files#diff-aa77d592927baae676cedc8e3fda943bf63744e885b0328371c6ebd9d18aebdb) because previously it was breaking multiple rules of hooks and I can't find a minimal angle of fixing it.

Looking at this, I'm already happy that most of your changes are in the core. Phew 😅 

I just wanted to let you know - we'll look at this, but before that we have to figure out #11511, I hope that's okay!

**Comment by jcostello-atlassian** [comment]
Thanks for the heads up @phryneas! I'll close this for now and will raise an issue for future reference:

https://github.com/apollographql/apollo-client/issues/11856

**Comment by phryneas** [comment]
No, please keep it open - you put a lot of work into this and I believe we'll be able to salvage most of it!

It just might take a while :)

**Comment by phryneas** [comment]
Hey @jcostello-atlassian!
It has been a while, but the https://github.com/apollographql/apollo-client/tree/release-3.11 branch now contains the new `useSubscription` implementation - could you please update this PR for that? :)

**Review by jerelmiller — APPROVED** [review]
This looks great to me! Thanks for getting this added!!! 🔥

**Pull request merged**
