### PR TITLE
Refactor to use unfetch instead of whatwg-fetch

### PR DESCRIPTION
**Pull request by calebmer**
This is something we may consider instead of removing `whatwg-fetch` given that [`unfetch`](https://www.npmjs.com/package/unfetch) is only 500 bytes.

### CODE REVIEW

**Comment by helfer** [comment]
This is neat, but was the size of whatwg-fetch ever a real issue?

**Comment by stubailo** [comment]
This seems to be missing some critical features of `fetch` such as `cors`, cookie controls, etc.

**Comment by stubailo** [comment]
I could be in favor of enabling people to somehow use `unfetch` instead of `fetch` though - although they are only going to save like 2kb on the bundle.

**Comment by calebmer** [comment]
Thought it was cute, figured it was also worth a discussion since we’ve discussed removing `whatwg-fetch` before. I’ll close because missing `cors` is a big one.

**Pull request closed without merging**
