### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**
### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by hwillson** [comment]
Thanks for this PR @DanielRuf! I'm a bit undecided on the best way forward with this. Yes, I understand the advantages of making sure we're testing `apollo-client` against both Node 8 and Node 10, but we'll be slowing down our CI by using both environments. Also, we don't really gain much by running our tooling/docs jobs (`Danger`, `Filesize`, `Typecheck`, `Docs`) against Node 8 and Node 10. I'll think about this a bit more, but we might just want to move ahead to Node 10 across the board. More details shortly - thanks again!

**Comment by hwillson** [comment]
Looks like the additional CI time needed isn't that much. So, let's do it!

**Comment by DanielRuf** [comment]
Right. Also using the build matrix feature might be a good idea.

**Comment by DanielRuf** [comment]
Hm, seems this does just use the second image entry and does not test both. I might have to duplicate tasks and leverage the build matrix feature.

**Comment by DanielRuf** [comment]
See https://circleci.com/gh/apollographql/apollo-client/14253?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Shall we revert and redo the PR? Sorry, I guess I mixed this with Travis CI in my mind.
Duplicating the jobs + adding "10" to the job names should be sufficient.

**Comment by hwillson** [comment]
Interesting - thanks for the heads up @DanielRuf. Let's keep the PR in place as is. I'll re-visit all of this shortly, since I'd like to adjust some of the CircleCI parallelization (and we're thinking of adding more containers). Thanks for your help with this!

**Pull request merged**
