### PR TITLE
Fixed flow annotations

### PR DESCRIPTION
**Pull request by dozoisch**
- `[Object]` means array of length 1 with Object. Instead we want `Array<Object>`
- ___* were typos. The correct values from code is __*

---

Follow up of https://github.com/apollographql/react-apollo/pull/952 :)

### CODE REVIEW

**Comment by stubailo** [comment]
Could you add a small note to the changelog please?

**Comment by dozoisch** [comment]
Will sure do! Probably going to happen later today

**Comment by stubailo** [comment]
Thank you!

**Comment by dozoisch** [comment]
@stubailo done

**Pull request merged**
