### PR TITLE
Adding package.json browser attribute pointing towards browser bundle…

### PR DESCRIPTION
**Pull request by schrepfler**
… and reusing current webpack setup and destination.

TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
No new logic
- [ ] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by stubailo** [comment]
Why is this necessary? Does this fix some issue you were encountering?

**Comment by calebmer** [comment]
Why do you need this? You are pointing it towards our analyze bundle which is used for internal development bundle size analysis _only_. It is not a production bundle in the slightest.

Please submit an issue so we can help diagnose your issue 😊

**Comment by schrepfler** [comment]
Sure, I'll point to you https://github.com/apollographql/subscriptions-transport-ws/pull/77 and before that https://github.com/apollographql/subscriptions-transport-ws/pull/48
In essence, if you provide a "browser" element in package.json then people can just reference the npm module in https://unpkg.com/#/ and users will be automatically able to use your lib liked as a script and delivered from the unpkg cdn. Not everybody uses node and people like to experiment just by linking stuff.
I used the analyze bundle just not to duplicate anything, it should fit the bill and can be re-used.

**Comment by calebmer** [comment]
We provide the UMD bundle as `main`: https://unpkg.com/apollo-client@0.8.7

Why is this not sufficient?

**Comment by stubailo** [comment]
Yeah looks like unpkg already works!

**Comment by schrepfler** [comment]
Awesome, wasn't aware it can work without a browser entry, cool 👍 
Closing.

**Comment by schrepfler** [comment]
Hi guys

**Comment by stubailo** [comment]
@schrepfler can you give it a shot? This isn't a supported way to use Apollo Client but if you figure out how to use it it will be helpful for others.

**Comment by schrepfler** [comment]
I can see there are some things in the window object but not quite certain if that's the way to get it from (Java guy here.) Thinking of the wider apollo ecosystem, I think it would be nice if there's a unified way to expose browser-type modules between apollo-client and the subscription(-ws) modules.
I'll continue experimenting but feel free for anyone to step in.

**Comment by calebmer** [comment]
There are a couple of things I’d like to change about the build system, and this is one of them. How important is this for you @schrepfler? Any reason you can’t setup Webpack as this would be much easier at the moment and more powerful for you as a user.

**Comment by schrepfler** [comment]
I certainly can but I think there are two kinds of people, those who use build systems and those which just want to experiment with the API's via a simple linked script. The thing which made me wish this is that I wanted to simply reference a module via cdn and unpkg allowed me to do so so I started to contribute to subscriptions-transport-ws but then I realised one woul also need the apollo client and maybe graphql and apollo subscriptions...
I don't think this is strictly needed but I'd say  to you apollo that you should think about this dev tier as well and provide a consistently exposed module namespace and some examples mainly because ease of use.

**Comment by helfer** [comment]
We can't merge the PR in this form, but we'll work on improving our build process to make this much easier to do. Expect to see some movement on that soon.

**Comment by schrepfler** [comment]
That's OK, if it sparks some movement that's great. My only desire is that whatever is delivered can be somehow used directly via unpkg.

**Pull request closed without merging**
