### PR TITLE
Pass context to link chain when doing a mutation

### PR DESCRIPTION
**Pull request by manueliglesias**
### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
Deploy preview ready!

Built with commit ee2adf6615efc26f8e9d505e4155850833ed317b

https://deploy-preview-2419--apollo-client-docs.netlify.com

**Comment by jbaxleyiii** [comment]
@manueliglesias would you be able to add a changelog entry under apollo-client package and a test to ensure the context is present for mutations?

I had thought this was already working via https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/__tests__/QueryManager/links.ts#L237-L274 and https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L187-L193

Are you having issues with this?

I do think we need to add it to they TypeScript types for mutation though!

**Comment by manueliglesias** [comment]
@jbaxleyiii Unit test added, changelog entry too

**Comment by manueliglesias** [comment]
@jbaxleyiii  Context was not being passed from `client.mutate()`. Let me know if I need to add something else to this PR

**Comment by Hendrixer** [comment]
@manueliglesias can you update your PR so we can get this merged?

**Comment by gdi2290** [comment]
+1 we need this PR. if anyone needs a workaround you can create a context object in variables then remove it later in link before apollo makes the xhr request

**Comment by manueliglesias** [comment]
@Hendrixer PR updated :D

**Comment by jbaxleyiii** [comment]
Yippee! Thank you so much!

**Comment by gdi2290** [comment]
awesome, what version will this be released?

**Comment by yuricamara** [comment]
I have just updated to the new release 2.0.3, @gdi2290.
Now this issue is solved.
Thank you very much @manueliglesias

**Pull request merged**
