### PR TITLE
[apollo-boost] Support apollo-link-http's useGETForQueries option

### PR DESCRIPTION
**Pull request by ikesyo**
Ref: https://github.com/apollographql/apollo-link/pull/510

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by ikesyo** [comment]
Can someone review this?

**Comment by ikesyo** [comment]
@hwillson Is this not a feature or enhancement?

**Comment by hwillson** [comment]
@ikesyo The `feature` label was removed because it's no longer being used in this repo at all. That won't affect this PR though. We'll have it reviewed shortly. Thanks!

**Comment by ikesyo** [comment]
Thanks for the clarification @hwillson!

**Comment by hwillson** [comment]
Thanks very much for working on this @ikesyo! Hopefully this doesn’t discourage you from contributing in the future, but we’ve decided to no longer accept PR’s for Apollo Boost functionality changes. We’re going to be deprecating `apollo-boost` shortly, and will be merging its functionality back into `apollo-client`, for the upcoming 3.0 release. Your best bet to use `useGETForQueries` is to use the full blown version of `apollo-client`. See the [Apollo Boost migration](https://www.apollographql.com/docs/react/advanced/boost-migration.html) section of the docs for details outlining how to switch from Apollo Boost to Apollo Client. Thanks again for your work on this!

**Comment by ikesyo** [comment]
> We’re going to be deprecating apollo-boost shortly

Thanks for the explanation, I understand. 👍

**Pull request closed without merging**
