### PR TITLE
Rewrite documentation for custom pagination with field policies

### PR DESCRIPTION
**Pull request by benjamn**
This is a long-overdue rewrite of the https://www.apollographql.com/docs/react/data/pagination/ documentation (the first item in #6711), to reflect the new tools that Apollo Client 3 provides.

I welcome your feedback in the form of comments, but I'm not looking for a PR review just yet, because the rewriting is still very much in progress!

Quick link to the deploy preview: https://deploy-preview-7175--apollo-client-docs.netlify.app/docs/react/data/pagination/

### CODE REVIEW

**Comment by MarkellRichards** [comment]
Hi Benjamin,

Thanks for posting the preview. I'm trying to make sense of it. I'm running into the same issue where I have two separate entries in the cache based on the arcs. Maybe you could provide guidance? 

https://stackoverflow.com/questions/64421566/data-not-merging-apollo-3-pagination-with-field-policies

**Comment by hwillson** [comment]
@StephenBarlow can you let me know when you're done with your edits? I'll hold off on reviewing until your changes are in. Thanks!

**Comment by hwillson** [comment]
Disregard @StephenBarlow - I talked to @benjamn and know the plan is to hold off on further edits until after this is merged.

**Comment by benjamn** [comment]
@StephenBarlow @hwillson I split the content about `keyArgs` out into a separate [page](https://deploy-preview-7175--apollo-client-docs.netlify.app/docs/react/pagination/key-args/), and added some additional context as an introduction to that page. I feel like the new text I added may be unnecessarily complicated, but I'm not sure how to simplify it without discarding useful information. Please feel free to leave comments or propose changes, though I expect we will continue iterating on this documentation even after this PR has been merged.

**Comment by StephenBarlow** [comment]
@benjamn The keyArgs split-out looks good! If you're happy with the content-completeness of these docs, I think we should go ahead and get them out there. I think a steady stream of improvements over the next few weeks will do the trick.

**Review by hwillson — APPROVED** [review]
This is really great @benjamn!

**Pull request merged**
