### PR TITLE
Fix: queryDeduplication from context

### PR DESCRIPTION
**Pull request by Kujawadl**
This is the same as #6261, except with the target branch set to version-2.6 in the hopes that we can get a 2.6 release with this included. Our team is not ready to transition to v3, but we still need this bug fixed.

Please let me know if this isn't typically how things are done here.

### CODE REVIEW

**Comment by thomasobrienglobality** [comment]
Thanks for this @Kujawadl. We need this fix as well.

**Comment by Kujawadl** [comment]
@benjamn sorry to bug you, just wanted to make sure this didn't fall off your radar over the holiday weekend. There's a lot of new and updated tests here, but the fix itself is really small, so I was hoping this could get released as a 2.6 fix at some point. 

I've got a meeting tomorrow to discuss workarounds with our team in the meanwhile, but let me know if there's anything I can do to get this released.

**Comment by Kujawadl** [comment]
I saw that this got released to @apollo/client@3.1.0-pre.0, is there any chance we could get a 2.6.11 release as well? Thanks so much for all your help :)

**Comment by Kujawadl** [comment]
Any word on a 2.6.11 release? Sorry to be a bother 😅

**Pull request merged**
