### PR TITLE
Update mockLink.ts

### PR DESCRIPTION
**Pull request by crisys11**
### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by crisys11** [comment]
Hello @alessbell, sometimes we need to re-use mocks, especially when we are working with storybook, so would be great if we can have a configuration params that allow that.

Let me know if i was clear or if you need more details 😄

**Comment by alessbell** [comment]
That makes perfect sense, @crisys11 😀

> especially when we are working with storybook

How is your team using Storybook with Apollo Client? Are you using [this addon](https://github.com/lifeiscontent/storybook-addon-apollo-client), or something custom?

**Comment by crisys11** [comment]
@alessbell we are using this storybook addon https://storybook.js.org/addons/storybook-addon-apollo-client 

We use the MocketProvider
image

and then we pass the mocks to the addon in the story

image

**Comment by alessbell** [comment]
TIL there's an Apollo Client Storybook addon, that's neat and very good to know :) Thanks for sharing that info about how you're using it @crisys11! The pain point you're experiencing with `MockedProvider` is a piece of feedback we've gotten before and one of the main motivations behind improving our testing utilities - we definitely hear you there.

With respect to the approach you've taken with `preserveMocks`, I appreciate that it's backward-compatible since it's disabled by default, but by giving developers the option to reuse mocks indefinitely in their tests, we'd run into different issues. For example, you couldn't write a test where the same query returns two different results, e.g. where a query succeeds the first time it's run but returns an error on refetch. The first mocked response (success case) would always match if we set `preserveMocks` to true. (You can see many examples of this if you enable `preserveMocks` before running Apollo Client's test suite.)

You could toggle this on/off per test, but the way the `preserveMocks: true` tests would be written would be fundamentally incompatible with the default setting, so you'd essentially be forking your entire test codebase between two different mental models of how mocking works in Apollo Client.

While I recognize there's a genuine need for more flexibility here, I think there's more we can do to give developers flexibility _and_ control in the next phase of Apollo Client testing tools. Subscribe to issue https://github.com/apollographql/apollo-client/issues/9738 for updates, we'd love to hear your thoughts/feedback as we begin work in this area.

**Pull request closed without merging**
