### PR TITLE
[docs] Repair import file path for `GraphQLWsLink`

### PR DESCRIPTION
**Pull request by c4lliope**
I received errors while obeying the documentation for setting up the GraphQLWsLink;
this is my guess on a repair.

On the second hand, I could be using an old version? Need someone to chime in here.

### Checklist:

- [ ] ~If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~
- [ ] ~Make sure all of the significant new logic is covered by tests~

### CODE REVIEW

**Comment by c4lliope** [comment]
I'm also seeing an error with:

```js
const wsLink = new WebSocketLink(
  createClient({ url: 'ws://localhost:4000/subscriptions' })
)
```

> Argument of type 'Client' is not assignable to parameter of type 'Configuration | SubscriptionClient'.

Are there more changes needed to keep this document in good shape?

**Comment by benjamn** [comment]
This seems to be undoing the documentation changes that were intentionally made in #9369 and #9453, so it would help to have some explanation of your motivation for the changes, at least.

If you are able to update to the latest version (3.5.10), I would recommend using the `@apollo/client/link/subscriptions` link instead of `@apollo/client/link/ws` (which does still exist, and is [still documented](https://www.apollographql.com/docs/react/data/subscriptions#the-older-subscriptions-transport-ws-library)).

**Comment by c4lliope** [comment]
I'm on 3.5.9, and there is no `@apollo/client/link/subscriptions` at all. Is this an error?

**Comment by c4lliope** [comment]
Yeah, I guess this is only in 3.5.10 - all good, I'll close this.

**Pull request closed without merging**
