### PR TITLE
document updateQuery/updateFragment

### PR DESCRIPTION
**Pull request by brainkim**
Closes https://github.com/apollographql/apollo-client/issues/8698

### CODE REVIEW

**Review by hwillson — APPROVED** [review]
Awesome @brainkim - thanks!

**Review by benjamn — APPROVED** [review]
Content all looks great to me, though it would be nice to trigger a new build to fix the Netlify docs preview, since the [error messages](https://app.netlify.com/sites/apollo-client-docs/deploys/6154e02056e6b500076243b7#L140) mention code added in this PR.

**Comment by brainkim** [comment]
@benjamn Looks like an mdx error. Give me a sec while I pair every html tag in the entire document.

BTW I think writings docs is incredibly painful. How do people manage?

**Comment by hwillson** [comment]
Vodka.

**Review by StephenBarlow — APPROVED** [review]
Approved to merge whenever 3.5 is a thing

**Pull request merged**
