### PR TITLE
graphql-anyhwere propType typechecking is not run while data is loading

### PR DESCRIPTION
**Pull request by mechanical-turk**
the `{propType}` export of `graphql-anywhere` throws errors while the data is loading, because the type-checked part of the data does not exist at the time of running the check.

therefore, it made sense personally to avoid running the typecheck while the data is still loading. hope you guys will find it useful & helpful as well.

### CODE REVIEW

**Comment by mechanical-turk** [comment]
I'd be happy to improve this code if someone were to guide me in how to write the changelog and make travis pass.

**Comment by mechanical-turk** [comment]
@jbaxleyiii hi james. i just realized that you were assigned to most of the PRs, so I thought mentioning you here to get your attention might be appropriate (sorry if it isn't, im not really familiar with the decorum here)

I've been dying to start contributing to apollo-client. would you care to give me some guidance here? I recently found this error while working on a feature for my company. it's a one-liner fix, but it does fix the issue.  i'd be really happy if i could get some feedback here as to how i should proceed. thank you.

**Comment by jbaxleyiii** [comment]
@mechanical-turk I think this changes makes sense to me! If you can add some info to the graphql-anywhere changelog the errors should go away and I can merge and release it!

**Comment by mechanical-turk** [comment]
@jbaxleyiii thanks for the response :) the changelog is updated. i'm still seeing a failed check: Benchmark. It doesnt let me see the details, but do let me know if that's something I can fix. Cheers.

**Pull request merged**
